/****************************************************************************
** QWidget meta object code from reading C++ file 'qwidget.h'
**
** Created: Fri Apr 20 02:02:07 2001
**      by: The Qt MOC ($Id$)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#if !defined(Q_MOC_OUTPUT_REVISION)
#define Q_MOC_OUTPUT_REVISION 9
#elif Q_MOC_OUTPUT_REVISION != 9
#error "Moc format conflict - please regenerate all moc files"
#endif

#include "qwidget.h"
#include <qmetaobject.h>
#include <qapplication.h>



const char *QWidget::className() const
{
    return "QWidget";
}

QMetaObject *QWidget::metaObj = 0;

void QWidget::initMetaObject()
{
    if ( metaObj )
	return;
    if ( qstrcmp(QObject::className(), "QObject") != 0 )
	badSuperclassWarning("QWidget","QObject");
    (void) staticMetaObject();
}

#ifndef QT_NO_TRANSLATION

QString QWidget::tr(const char* s)
{
    return qApp->translate( "QWidget", s, 0 );
}

QString QWidget::tr(const char* s, const char * c)
{
    return qApp->translate( "QWidget", s, c );
}

#endif // QT_NO_TRANSLATION

QMetaObject* QWidget::staticMetaObject()
{
    if ( metaObj )
	return metaObj;
    (void) QObject::staticMetaObject();
#ifndef QT_NO_PROPERTIES
    QMetaEnum* enum_tbl = QMetaObject::new_metaenum( 4 );
    enum_tbl[0].name = "BackgroundMode";
    enum_tbl[0].count = 18;
    enum_tbl[0].items = QMetaObject::new_metaenum_item( 18 );
    enum_tbl[0].set = FALSE;
    enum_tbl[0].items[0].key = "FixedColor";
    enum_tbl[0].items[0].value = (int) QWidget::FixedColor;
    enum_tbl[0].items[1].key = "FixedPixmap";
    enum_tbl[0].items[1].value = (int) QWidget::FixedPixmap;
    enum_tbl[0].items[2].key = "NoBackground";
    enum_tbl[0].items[2].value = (int) QWidget::NoBackground;
    enum_tbl[0].items[3].key = "PaletteForeground";
    enum_tbl[0].items[3].value = (int) QWidget::PaletteForeground;
    enum_tbl[0].items[4].key = "PaletteButton";
    enum_tbl[0].items[4].value = (int) QWidget::PaletteButton;
    enum_tbl[0].items[5].key = "PaletteLight";
    enum_tbl[0].items[5].value = (int) QWidget::PaletteLight;
    enum_tbl[0].items[6].key = "PaletteMidlight";
    enum_tbl[0].items[6].value = (int) QWidget::PaletteMidlight;
    enum_tbl[0].items[7].key = "PaletteDark";
    enum_tbl[0].items[7].value = (int) QWidget::PaletteDark;
    enum_tbl[0].items[8].key = "PaletteMid";
    enum_tbl[0].items[8].value = (int) QWidget::PaletteMid;
    enum_tbl[0].items[9].key = "PaletteText";
    enum_tbl[0].items[9].value = (int) QWidget::PaletteText;
    enum_tbl[0].items[10].key = "PaletteBrightText";
    enum_tbl[0].items[10].value = (int) QWidget::PaletteBrightText;
    enum_tbl[0].items[11].key = "PaletteBase";
    enum_tbl[0].items[11].value = (int) QWidget::PaletteBase;
    enum_tbl[0].items[12].key = "PaletteBackground";
    enum_tbl[0].items[12].value = (int) QWidget::PaletteBackground;
    enum_tbl[0].items[13].key = "PaletteShadow";
    enum_tbl[0].items[13].value = (int) QWidget::PaletteShadow;
    enum_tbl[0].items[14].key = "PaletteHighlight";
    enum_tbl[0].items[14].value = (int) QWidget::PaletteHighlight;
    enum_tbl[0].items[15].key = "PaletteHighlightedText";
    enum_tbl[0].items[15].value = (int) QWidget::PaletteHighlightedText;
    enum_tbl[0].items[16].key = "PaletteButtonText";
    enum_tbl[0].items[16].value = (int) QWidget::PaletteButtonText;
    enum_tbl[0].items[17].key = "X11ParentRelative";
    enum_tbl[0].items[17].value = (int) QWidget::X11ParentRelative;
    enum_tbl[1].name = "PropagationMode";
    enum_tbl[1].count = 4;
    enum_tbl[1].items = QMetaObject::new_metaenum_item( 4 );
    enum_tbl[1].set = FALSE;
    enum_tbl[1].items[0].key = "NoChildren";
    enum_tbl[1].items[0].value = (int) QWidget::NoChildren;
    enum_tbl[1].items[1].key = "AllChildren";
    enum_tbl[1].items[1].value = (int) QWidget::AllChildren;
    enum_tbl[1].items[2].key = "SameFont";
    enum_tbl[1].items[2].value = (int) QWidget::SameFont;
    enum_tbl[1].items[3].key = "SamePalette";
    enum_tbl[1].items[3].value = (int) QWidget::SamePalette;
    enum_tbl[2].name = "FocusPolicy";
    enum_tbl[2].count = 5;
    enum_tbl[2].items = QMetaObject::new_metaenum_item( 5 );
    enum_tbl[2].set = FALSE;
    enum_tbl[2].items[0].key = "NoFocus";
    enum_tbl[2].items[0].value = (int) QWidget::NoFocus;
    enum_tbl[2].items[1].key = "TabFocus";
    enum_tbl[2].items[1].value = (int) QWidget::TabFocus;
    enum_tbl[2].items[2].key = "ClickFocus";
    enum_tbl[2].items[2].value = (int) QWidget::ClickFocus;
    enum_tbl[2].items[3].key = "StrongFocus";
    enum_tbl[2].items[3].value = (int) QWidget::StrongFocus;
    enum_tbl[2].items[4].key = "WheelFocus";
    enum_tbl[2].items[4].value = (int) QWidget::WheelFocus;
    enum_tbl[3].name = "BackgroundOrigin";
    enum_tbl[3].count = 2;
    enum_tbl[3].items = QMetaObject::new_metaenum_item( 2 );
    enum_tbl[3].set = FALSE;
    enum_tbl[3].items[0].key = "WidgetOrigin";
    enum_tbl[3].items[0].value = (int) QWidget::WidgetOrigin;
    enum_tbl[3].items[1].key = "ParentOrigin";
    enum_tbl[3].items[1].value = (int) QWidget::ParentOrigin;
#endif // QT_NO_PROPERTIES
#ifndef QT_NO_PROPERTIES
    typedef bool (QWidget::*m3_t0)()const;
    typedef bool (QObject::*om3_t0)()const;
    typedef bool (QWidget::*m3_t3)()const;
    typedef bool (QObject::*om3_t3)()const;
    typedef bool (QWidget::*m3_t6)()const;
    typedef bool (QObject::*om3_t6)()const;
    typedef bool (QWidget::*m3_t9)()const;
    typedef bool (QObject::*om3_t9)()const;
    typedef bool (QWidget::*m3_t12)()const;
    typedef bool (QObject::*om3_t12)()const;
    typedef void (QWidget::*m3_t13)(bool);
    typedef void (QObject::*om3_t13)(bool);
    typedef const QRect& (QWidget::*m3_t15)()const;
    typedef const QRect& (QObject::*om3_t15)()const;
    typedef void (QWidget::*m3_t16)(const QRect&);
    typedef void (QObject::*om3_t16)(const QRect&);
    typedef QRect (QWidget::*m3_t18)()const;
    typedef QRect (QObject::*om3_t18)()const;
    typedef int (QWidget::*m3_t21)()const;
    typedef int (QObject::*om3_t21)()const;
    typedef int (QWidget::*m3_t24)()const;
    typedef int (QObject::*om3_t24)()const;
    typedef QPoint (QWidget::*m3_t27)()const;
    typedef QPoint (QObject::*om3_t27)()const;
    typedef QSize (QWidget::*m3_t30)()const;
    typedef QSize (QObject::*om3_t30)()const;
    typedef QSize (QWidget::*m3_t33)()const;
    typedef QSize (QObject::*om3_t33)()const;
    typedef void (QWidget::*m3_t34)(const QSize&);
    typedef void (QObject::*om3_t34)(const QSize&);
    typedef int (QWidget::*m3_t36)()const;
    typedef int (QObject::*om3_t36)()const;
    typedef int (QWidget::*m3_t39)()const;
    typedef int (QObject::*om3_t39)()const;
    typedef QRect (QWidget::*m3_t42)()const;
    typedef QRect (QObject::*om3_t42)()const;
    typedef QRect (QWidget::*m3_t45)()const;
    typedef QRect (QObject::*om3_t45)()const;
    typedef QRegion (QWidget::*m3_t48)()const;
    typedef QRegion (QObject::*om3_t48)()const;
    typedef QSizePolicy (QWidget::*m3_t51)()const;
    typedef QSizePolicy (QObject::*om3_t51)()const;
    typedef void (QWidget::*m3_t52)(QSizePolicy);
    typedef void (QObject::*om3_t52)(QSizePolicy);
    typedef QSize (QWidget::*m3_t54)()const;
    typedef QSize (QObject::*om3_t54)()const;
    typedef void (QWidget::*m3_t55)(const QSize&);
    typedef void (QObject::*om3_t55)(const QSize&);
    typedef QSize (QWidget::*m3_t57)()const;
    typedef QSize (QObject::*om3_t57)()const;
    typedef void (QWidget::*m3_t58)(const QSize&);
    typedef void (QObject::*om3_t58)(const QSize&);
    typedef int (QWidget::*m3_t60)()const;
    typedef int (QObject::*om3_t60)()const;
    typedef void (QWidget::*m3_t61)(int);
    typedef void (QObject::*om3_t61)(int);
    typedef int (QWidget::*m3_t63)()const;
    typedef int (QObject::*om3_t63)()const;
    typedef void (QWidget::*m3_t64)(int);
    typedef void (QObject::*om3_t64)(int);
    typedef int (QWidget::*m3_t66)()const;
    typedef int (QObject::*om3_t66)()const;
    typedef void (QWidget::*m3_t67)(int);
    typedef void (QObject::*om3_t67)(int);
    typedef int (QWidget::*m3_t69)()const;
    typedef int (QObject::*om3_t69)()const;
    typedef void (QWidget::*m3_t70)(int);
    typedef void (QObject::*om3_t70)(int);
    typedef QSize (QWidget::*m3_t72)()const;
    typedef QSize (QObject::*om3_t72)()const;
    typedef void (QWidget::*m3_t73)(const QSize&);
    typedef void (QObject::*om3_t73)(const QSize&);
    typedef QSize (QWidget::*m3_t75)()const;
    typedef QSize (QObject::*om3_t75)()const;
    typedef void (QWidget::*m3_t76)(const QSize&);
    typedef void (QObject::*om3_t76)(const QSize&);
    typedef BackgroundMode (QWidget::*m3_t78)()const;
    typedef BackgroundMode (QObject::*om3_t78)()const;
    typedef void (QWidget::*m3_t79)(BackgroundMode);
    typedef void (QObject::*om3_t79)(BackgroundMode);
    typedef const QColor& (QWidget::*m3_t81)()const;
    typedef const QColor& (QObject::*om3_t81)()const;
    typedef void (QWidget::*m3_t82)(const QColor&);
    typedef void (QObject::*om3_t82)(const QColor&);
    typedef const QColor& (QWidget::*m3_t84)()const;
    typedef const QColor& (QObject::*om3_t84)()const;
    typedef const QPixmap* (QWidget::*m3_t87)()const;
    typedef const QPixmap* (QObject::*om3_t87)()const;
    typedef void (QWidget::*m3_t88)(const QPixmap&);
    typedef void (QObject::*om3_t88)(const QPixmap&);
    typedef const QColorGroup& (QWidget::*m3_t90)()const;
    typedef const QColorGroup& (QObject::*om3_t90)()const;
    typedef const QPalette& (QWidget::*m3_t93)()const;
    typedef const QPalette& (QObject::*om3_t93)()const;
    typedef void (QWidget::*m3_t94)(const QPalette&);
    typedef void (QObject::*om3_t94)(const QPalette&);
    typedef void (QWidget::*m3_t95)();
    typedef void (QObject::*om3_t95)();
    typedef bool (QWidget::*m3_t96)()const;
    typedef bool (QObject::*om3_t96)()const;
    typedef QFont (QWidget::*m3_t99)()const;
    typedef QFont (QObject::*om3_t99)()const;
    typedef void (QWidget::*m3_t100)(const QFont&);
    typedef void (QObject::*om3_t100)(const QFont&);
    typedef void (QWidget::*m3_t101)();
    typedef void (QObject::*om3_t101)();
    typedef bool (QWidget::*m3_t102)()const;
    typedef bool (QObject::*om3_t102)()const;
    typedef const QCursor& (QWidget::*m3_t105)()const;
    typedef const QCursor& (QObject::*om3_t105)()const;
    typedef void (QWidget::*m3_t106)(const QCursor&);
    typedef void (QObject::*om3_t106)(const QCursor&);
    typedef void (QWidget::*m3_t107)();
    typedef void (QObject::*om3_t107)();
    typedef bool (QWidget::*m3_t108)()const;
    typedef bool (QObject::*om3_t108)()const;
    typedef QString (QWidget::*m3_t111)()const;
    typedef QString (QObject::*om3_t111)()const;
    typedef void (QWidget::*m3_t112)(const QString&);
    typedef void (QObject::*om3_t112)(const QString&);
    typedef const QPixmap* (QWidget::*m3_t114)()const;
    typedef const QPixmap* (QObject::*om3_t114)()const;
    typedef void (QWidget::*m3_t115)(const QPixmap&);
    typedef void (QObject::*om3_t115)(const QPixmap&);
    typedef QString (QWidget::*m3_t117)()const;
    typedef QString (QObject::*om3_t117)()const;
    typedef void (QWidget::*m3_t118)(const QString&);
    typedef void (QObject::*om3_t118)(const QString&);
    typedef bool (QWidget::*m3_t120)()const;
    typedef bool (QObject::*om3_t120)()const;
    typedef void (QWidget::*m3_t121)(bool);
    typedef void (QObject::*om3_t121)(bool);
    typedef bool (QWidget::*m3_t123)()const;
    typedef bool (QObject::*om3_t123)()const;
    typedef bool (QWidget::*m3_t126)()const;
    typedef bool (QObject::*om3_t126)()const;
    typedef FocusPolicy (QWidget::*m3_t129)()const;
    typedef FocusPolicy (QObject::*om3_t129)()const;
    typedef void (QWidget::*m3_t130)(FocusPolicy);
    typedef void (QObject::*om3_t130)(FocusPolicy);
    typedef bool (QWidget::*m3_t132)()const;
    typedef bool (QObject::*om3_t132)()const;
    typedef bool (QWidget::*m3_t135)()const;
    typedef bool (QObject::*om3_t135)()const;
    typedef void (QWidget::*m3_t136)(bool);
    typedef void (QObject::*om3_t136)(bool);
    typedef bool (QWidget::*m3_t138)()const;
    typedef bool (QObject::*om3_t138)()const;
    typedef QRect (QWidget::*m3_t141)()const;
    typedef QRect (QObject::*om3_t141)()const;
    typedef bool (QWidget::*m3_t144)()const;
    typedef bool (QObject::*om3_t144)()const;
    typedef bool (QWidget::*m3_t147)()const;
    typedef bool (QObject::*om3_t147)()const;
    typedef QSize (QWidget::*m3_t150)()const;
    typedef QSize (QObject::*om3_t150)()const;
    typedef QSize (QWidget::*m3_t153)()const;
    typedef QSize (QObject::*om3_t153)()const;
    typedef QRect (QWidget::*m3_t156)()const;
    typedef QRect (QObject::*om3_t156)()const;
    typedef bool (QWidget::*m3_t159)()const;
    typedef bool (QObject::*om3_t159)()const;
    typedef void (QWidget::*m3_t160)(bool);
    typedef void (QObject::*om3_t160)(bool);
    typedef bool (QWidget::*m3_t162)()const;
    typedef bool (QObject::*om3_t162)()const;
    typedef void (QWidget::*m3_t163)(bool);
    typedef void (QObject::*om3_t163)(bool);
    typedef BackgroundOrigin (QWidget::*m3_t165)()const;
    typedef BackgroundOrigin (QObject::*om3_t165)()const;
    typedef void (QWidget::*m3_t166)(BackgroundOrigin);
    typedef void (QObject::*om3_t166)(BackgroundOrigin);
    typedef bool (QWidget::*m3_t168)()const;
    typedef bool (QObject::*om3_t168)()const;
    m3_t0 v3_0 = &QWidget::isTopLevel;
    om3_t0 ov3_0 = (om3_t0)v3_0;
    m3_t3 v3_3 = &QWidget::isModal;
    om3_t3 ov3_3 = (om3_t3)v3_3;
    m3_t6 v3_6 = &QWidget::isPopup;
    om3_t6 ov3_6 = (om3_t6)v3_6;
    m3_t9 v3_9 = &QWidget::isDesktop;
    om3_t9 ov3_9 = (om3_t9)v3_9;
    m3_t12 v3_12 = &QWidget::isEnabled;
    om3_t12 ov3_12 = (om3_t12)v3_12;
    m3_t13 v3_13 = &QWidget::setEnabled;
    om3_t13 ov3_13 = (om3_t13)v3_13;
    m3_t15 v3_15 = &QWidget::geometry;
    om3_t15 ov3_15 = (om3_t15)v3_15;
    m3_t16 v3_16 = &QWidget::setGeometry;
    om3_t16 ov3_16 = (om3_t16)v3_16;
    m3_t18 v3_18 = &QWidget::frameGeometry;
    om3_t18 ov3_18 = (om3_t18)v3_18;
    m3_t21 v3_21 = &QWidget::x;
    om3_t21 ov3_21 = (om3_t21)v3_21;
    m3_t24 v3_24 = &QWidget::y;
    om3_t24 ov3_24 = (om3_t24)v3_24;
    m3_t27 v3_27 = &QWidget::pos;
    om3_t27 ov3_27 = (om3_t27)v3_27;
    m3_t30 v3_30 = &QWidget::frameSize;
    om3_t30 ov3_30 = (om3_t30)v3_30;
    m3_t33 v3_33 = &QWidget::size;
    om3_t33 ov3_33 = (om3_t33)v3_33;
    m3_t34 v3_34 = &QWidget::resize;
    om3_t34 ov3_34 = (om3_t34)v3_34;
    m3_t36 v3_36 = &QWidget::width;
    om3_t36 ov3_36 = (om3_t36)v3_36;
    m3_t39 v3_39 = &QWidget::height;
    om3_t39 ov3_39 = (om3_t39)v3_39;
    m3_t42 v3_42 = &QWidget::rect;
    om3_t42 ov3_42 = (om3_t42)v3_42;
    m3_t45 v3_45 = &QWidget::childrenRect;
    om3_t45 ov3_45 = (om3_t45)v3_45;
    m3_t48 v3_48 = &QWidget::childrenRegion;
    om3_t48 ov3_48 = (om3_t48)v3_48;
    m3_t51 v3_51 = &QWidget::sizePolicy;
    om3_t51 ov3_51 = (om3_t51)v3_51;
    m3_t52 v3_52 = &QWidget::setSizePolicy;
    om3_t52 ov3_52 = (om3_t52)v3_52;
    m3_t54 v3_54 = &QWidget::minimumSize;
    om3_t54 ov3_54 = (om3_t54)v3_54;
    m3_t55 v3_55 = &QWidget::setMinimumSize;
    om3_t55 ov3_55 = (om3_t55)v3_55;
    m3_t57 v3_57 = &QWidget::maximumSize;
    om3_t57 ov3_57 = (om3_t57)v3_57;
    m3_t58 v3_58 = &QWidget::setMaximumSize;
    om3_t58 ov3_58 = (om3_t58)v3_58;
    m3_t60 v3_60 = &QWidget::minimumWidth;
    om3_t60 ov3_60 = (om3_t60)v3_60;
    m3_t61 v3_61 = &QWidget::setMinimumWidth;
    om3_t61 ov3_61 = (om3_t61)v3_61;
    m3_t63 v3_63 = &QWidget::minimumHeight;
    om3_t63 ov3_63 = (om3_t63)v3_63;
    m3_t64 v3_64 = &QWidget::setMinimumHeight;
    om3_t64 ov3_64 = (om3_t64)v3_64;
    m3_t66 v3_66 = &QWidget::maximumWidth;
    om3_t66 ov3_66 = (om3_t66)v3_66;
    m3_t67 v3_67 = &QWidget::setMaximumWidth;
    om3_t67 ov3_67 = (om3_t67)v3_67;
    m3_t69 v3_69 = &QWidget::maximumHeight;
    om3_t69 ov3_69 = (om3_t69)v3_69;
    m3_t70 v3_70 = &QWidget::setMaximumHeight;
    om3_t70 ov3_70 = (om3_t70)v3_70;
    m3_t72 v3_72 = &QWidget::sizeIncrement;
    om3_t72 ov3_72 = (om3_t72)v3_72;
    m3_t73 v3_73 = &QWidget::setSizeIncrement;
    om3_t73 ov3_73 = (om3_t73)v3_73;
    m3_t75 v3_75 = &QWidget::baseSize;
    om3_t75 ov3_75 = (om3_t75)v3_75;
    m3_t76 v3_76 = &QWidget::setBaseSize;
    om3_t76 ov3_76 = (om3_t76)v3_76;
    m3_t78 v3_78 = &QWidget::backgroundMode;
    om3_t78 ov3_78 = (om3_t78)v3_78;
    m3_t79 v3_79 = &QWidget::setBackgroundMode;
    om3_t79 ov3_79 = (om3_t79)v3_79;
    m3_t81 v3_81 = &QWidget::backgroundColor;
    om3_t81 ov3_81 = (om3_t81)v3_81;
    m3_t82 v3_82 = &QWidget::setBackgroundColor;
    om3_t82 ov3_82 = (om3_t82)v3_82;
    m3_t84 v3_84 = &QWidget::foregroundColor;
    om3_t84 ov3_84 = (om3_t84)v3_84;
    m3_t87 v3_87 = &QWidget::backgroundPixmap;
    om3_t87 ov3_87 = (om3_t87)v3_87;
    m3_t88 v3_88 = &QWidget::setBackgroundPixmap;
    om3_t88 ov3_88 = (om3_t88)v3_88;
    m3_t90 v3_90 = &QWidget::colorGroup;
    om3_t90 ov3_90 = (om3_t90)v3_90;
    m3_t93 v3_93 = &QWidget::palette;
    om3_t93 ov3_93 = (om3_t93)v3_93;
    m3_t94 v3_94 = &QWidget::setPalette;
    om3_t94 ov3_94 = (om3_t94)v3_94;
    m3_t95 v3_95 = &QWidget::unsetPalette;
    om3_t95 ov3_95 = (om3_t95)v3_95;
    m3_t96 v3_96 = &QWidget::ownPalette;
    om3_t96 ov3_96 = (om3_t96)v3_96;
    m3_t99 v3_99 = &QWidget::font;
    om3_t99 ov3_99 = (om3_t99)v3_99;
    m3_t100 v3_100 = &QWidget::setFont;
    om3_t100 ov3_100 = (om3_t100)v3_100;
    m3_t101 v3_101 = &QWidget::unsetFont;
    om3_t101 ov3_101 = (om3_t101)v3_101;
    m3_t102 v3_102 = &QWidget::ownFont;
    om3_t102 ov3_102 = (om3_t102)v3_102;
    m3_t105 v3_105 = &QWidget::cursor;
    om3_t105 ov3_105 = (om3_t105)v3_105;
    m3_t106 v3_106 = &QWidget::setCursor;
    om3_t106 ov3_106 = (om3_t106)v3_106;
    m3_t107 v3_107 = &QWidget::unsetCursor;
    om3_t107 ov3_107 = (om3_t107)v3_107;
    m3_t108 v3_108 = &QWidget::ownCursor;
    om3_t108 ov3_108 = (om3_t108)v3_108;
    m3_t111 v3_111 = &QWidget::caption;
    om3_t111 ov3_111 = (om3_t111)v3_111;
    m3_t112 v3_112 = &QWidget::setCaption;
    om3_t112 ov3_112 = (om3_t112)v3_112;
    m3_t114 v3_114 = &QWidget::icon;
    om3_t114 ov3_114 = (om3_t114)v3_114;
    m3_t115 v3_115 = &QWidget::setIcon;
    om3_t115 ov3_115 = (om3_t115)v3_115;
    m3_t117 v3_117 = &QWidget::iconText;
    om3_t117 ov3_117 = (om3_t117)v3_117;
    m3_t118 v3_118 = &QWidget::setIconText;
    om3_t118 ov3_118 = (om3_t118)v3_118;
    m3_t120 v3_120 = &QWidget::hasMouseTracking;
    om3_t120 ov3_120 = (om3_t120)v3_120;
    m3_t121 v3_121 = &QWidget::setMouseTracking;
    om3_t121 ov3_121 = (om3_t121)v3_121;
    m3_t123 v3_123 = &QWidget::isActiveWindow;
    om3_t123 ov3_123 = (om3_t123)v3_123;
    m3_t126 v3_126 = &QWidget::isFocusEnabled;
    om3_t126 ov3_126 = (om3_t126)v3_126;
    m3_t129 v3_129 = &QWidget::focusPolicy;
    om3_t129 ov3_129 = (om3_t129)v3_129;
    m3_t130 v3_130 = &QWidget::setFocusPolicy;
    om3_t130 ov3_130 = (om3_t130)v3_130;
    m3_t132 v3_132 = &QWidget::hasFocus;
    om3_t132 ov3_132 = (om3_t132)v3_132;
    m3_t135 v3_135 = &QWidget::isUpdatesEnabled;
    om3_t135 ov3_135 = (om3_t135)v3_135;
    m3_t136 v3_136 = &QWidget::setUpdatesEnabled;
    om3_t136 ov3_136 = (om3_t136)v3_136;
    m3_t138 v3_138 = &QWidget::isVisible;
    om3_t138 ov3_138 = (om3_t138)v3_138;
    m3_t141 v3_141 = &QWidget::visibleRect;
    om3_t141 ov3_141 = (om3_t141)v3_141;
    m3_t144 v3_144 = &QWidget::isHidden;
    om3_t144 ov3_144 = (om3_t144)v3_144;
    m3_t147 v3_147 = &QWidget::isMinimized;
    om3_t147 ov3_147 = (om3_t147)v3_147;
    m3_t150 v3_150 = &QWidget::sizeHint;
    om3_t150 ov3_150 = (om3_t150)v3_150;
    m3_t153 v3_153 = &QWidget::minimumSizeHint;
    om3_t153 ov3_153 = (om3_t153)v3_153;
    m3_t156 v3_156 = &QWidget::microFocusHint;
    om3_t156 ov3_156 = (om3_t156)v3_156;
    m3_t159 v3_159 = &QWidget::acceptDrops;
    om3_t159 ov3_159 = (om3_t159)v3_159;
    m3_t160 v3_160 = &QWidget::setAcceptDrops;
    om3_t160 ov3_160 = (om3_t160)v3_160;
    m3_t162 v3_162 = &QWidget::autoMask;
    om3_t162 ov3_162 = (om3_t162)v3_162;
    m3_t163 v3_163 = &QWidget::setAutoMask;
    om3_t163 ov3_163 = (om3_t163)v3_163;
    m3_t165 v3_165 = &QWidget::backgroundOrigin;
    om3_t165 ov3_165 = (om3_t165)v3_165;
    m3_t166 v3_166 = &QWidget::setBackgroundOrigin;
    om3_t166 ov3_166 = (om3_t166)v3_166;
    m3_t168 v3_168 = &QWidget::customWhatsThis;
    om3_t168 ov3_168 = (om3_t168)v3_168;
    QMetaProperty *props_tbl = QMetaObject::new_metaproperty( 57 );
    props_tbl[0].t = "bool";
    props_tbl[0].n = "isTopLevel";
    props_tbl[0].get = (QMember)ov3_0;
    props_tbl[0].set = 0;
    props_tbl[0].reset = 0;
    props_tbl[0].gspec = QMetaProperty::Class;
    props_tbl[0].sspec = QMetaProperty::Unspecified;
    props_tbl[1].t = "bool";
    props_tbl[1].n = "isModal";
    props_tbl[1].get = (QMember)ov3_3;
    props_tbl[1].set = 0;
    props_tbl[1].reset = 0;
    props_tbl[1].gspec = QMetaProperty::Class;
    props_tbl[1].sspec = QMetaProperty::Unspecified;
    props_tbl[2].t = "bool";
    props_tbl[2].n = "isPopup";
    props_tbl[2].get = (QMember)ov3_6;
    props_tbl[2].set = 0;
    props_tbl[2].reset = 0;
    props_tbl[2].gspec = QMetaProperty::Class;
    props_tbl[2].sspec = QMetaProperty::Unspecified;
    props_tbl[3].t = "bool";
    props_tbl[3].n = "isDesktop";
    props_tbl[3].get = (QMember)ov3_9;
    props_tbl[3].set = 0;
    props_tbl[3].reset = 0;
    props_tbl[3].gspec = QMetaProperty::Class;
    props_tbl[3].sspec = QMetaProperty::Unspecified;
    props_tbl[4].t = "bool";
    props_tbl[4].n = "enabled";
    props_tbl[4].get = (QMember)ov3_12;
    props_tbl[4].set = (QMember)ov3_13;
    props_tbl[4].reset = 0;
    props_tbl[4].gspec = QMetaProperty::Class;
    props_tbl[4].sspec = QMetaProperty::Class;
    props_tbl[4].setFlags(QMetaProperty::StdSet);
    props_tbl[5].t = "QRect";
    props_tbl[5].n = "geometry";
    props_tbl[5].get = (QMember)ov3_15;
    props_tbl[5].set = (QMember)ov3_16;
    props_tbl[5].reset = 0;
    props_tbl[5].gspec = QMetaProperty::Reference;
    props_tbl[5].sspec = QMetaProperty::Reference;
    props_tbl[5].setFlags(QMetaProperty::StdSet);
    props_tbl[6].t = "QRect";
    props_tbl[6].n = "frameGeometry";
    props_tbl[6].get = (QMember)ov3_18;
    props_tbl[6].set = 0;
    props_tbl[6].reset = 0;
    props_tbl[6].gspec = QMetaProperty::Class;
    props_tbl[6].sspec = QMetaProperty::Unspecified;
    props_tbl[7].t = "int";
    props_tbl[7].n = "x";
    props_tbl[7].get = (QMember)ov3_21;
    props_tbl[7].set = 0;
    props_tbl[7].reset = 0;
    props_tbl[7].gspec = QMetaProperty::Class;
    props_tbl[7].sspec = QMetaProperty::Unspecified;
    props_tbl[8].t = "int";
    props_tbl[8].n = "y";
    props_tbl[8].get = (QMember)ov3_24;
    props_tbl[8].set = 0;
    props_tbl[8].reset = 0;
    props_tbl[8].gspec = QMetaProperty::Class;
    props_tbl[8].sspec = QMetaProperty::Unspecified;
    props_tbl[9].t = "QPoint";
    props_tbl[9].n = "pos";
    props_tbl[9].get = (QMember)ov3_27;
    props_tbl[9].set = 0;
    props_tbl[9].reset = 0;
    props_tbl[9].gspec = QMetaProperty::Class;
    props_tbl[9].sspec = QMetaProperty::Unspecified;
    props_tbl[10].t = "QSize";
    props_tbl[10].n = "frameSize";
    props_tbl[10].get = (QMember)ov3_30;
    props_tbl[10].set = 0;
    props_tbl[10].reset = 0;
    props_tbl[10].gspec = QMetaProperty::Class;
    props_tbl[10].sspec = QMetaProperty::Unspecified;
    props_tbl[11].t = "QSize";
    props_tbl[11].n = "size";
    props_tbl[11].get = (QMember)ov3_33;
    props_tbl[11].set = (QMember)ov3_34;
    props_tbl[11].reset = 0;
    props_tbl[11].gspec = QMetaProperty::Class;
    props_tbl[11].sspec = QMetaProperty::Reference;
    props_tbl[11].setFlags(QMetaProperty::NotDesignable);
    props_tbl[12].t = "int";
    props_tbl[12].n = "width";
    props_tbl[12].get = (QMember)ov3_36;
    props_tbl[12].set = 0;
    props_tbl[12].reset = 0;
    props_tbl[12].gspec = QMetaProperty::Class;
    props_tbl[12].sspec = QMetaProperty::Unspecified;
    props_tbl[13].t = "int";
    props_tbl[13].n = "height";
    props_tbl[13].get = (QMember)ov3_39;
    props_tbl[13].set = 0;
    props_tbl[13].reset = 0;
    props_tbl[13].gspec = QMetaProperty::Class;
    props_tbl[13].sspec = QMetaProperty::Unspecified;
    props_tbl[14].t = "QRect";
    props_tbl[14].n = "rect";
    props_tbl[14].get = (QMember)ov3_42;
    props_tbl[14].set = 0;
    props_tbl[14].reset = 0;
    props_tbl[14].gspec = QMetaProperty::Class;
    props_tbl[14].sspec = QMetaProperty::Unspecified;
    props_tbl[15].t = "QRect";
    props_tbl[15].n = "childrenRect";
    props_tbl[15].get = (QMember)ov3_45;
    props_tbl[15].set = 0;
    props_tbl[15].reset = 0;
    props_tbl[15].gspec = QMetaProperty::Class;
    props_tbl[15].sspec = QMetaProperty::Unspecified;
    props_tbl[16].t = "QRegion";
    props_tbl[16].n = "childrenRegion";
    props_tbl[16].get = (QMember)ov3_48;
    props_tbl[16].set = 0;
    props_tbl[16].reset = 0;
    props_tbl[16].gspec = QMetaProperty::Class;
    props_tbl[16].sspec = QMetaProperty::Unspecified;
    props_tbl[17].t = "QSizePolicy";
    props_tbl[17].n = "sizePolicy";
    props_tbl[17].get = (QMember)ov3_51;
    props_tbl[17].set = (QMember)ov3_52;
    props_tbl[17].reset = 0;
    props_tbl[17].gspec = QMetaProperty::Class;
    props_tbl[17].sspec = QMetaProperty::Class;
    props_tbl[17].setFlags(QMetaProperty::StdSet);
    props_tbl[18].t = "QSize";
    props_tbl[18].n = "minimumSize";
    props_tbl[18].get = (QMember)ov3_54;
    props_tbl[18].set = (QMember)ov3_55;
    props_tbl[18].reset = 0;
    props_tbl[18].gspec = QMetaProperty::Class;
    props_tbl[18].sspec = QMetaProperty::Reference;
    props_tbl[18].setFlags(QMetaProperty::StdSet);
    props_tbl[19].t = "QSize";
    props_tbl[19].n = "maximumSize";
    props_tbl[19].get = (QMember)ov3_57;
    props_tbl[19].set = (QMember)ov3_58;
    props_tbl[19].reset = 0;
    props_tbl[19].gspec = QMetaProperty::Class;
    props_tbl[19].sspec = QMetaProperty::Reference;
    props_tbl[19].setFlags(QMetaProperty::StdSet);
    props_tbl[20].t = "int";
    props_tbl[20].n = "minimumWidth";
    props_tbl[20].get = (QMember)ov3_60;
    props_tbl[20].set = (QMember)ov3_61;
    props_tbl[20].reset = 0;
    props_tbl[20].gspec = QMetaProperty::Class;
    props_tbl[20].sspec = QMetaProperty::Class;
    props_tbl[20].setFlags(QMetaProperty::NotStored|QMetaProperty::StdSet);
    props_tbl[21].t = "int";
    props_tbl[21].n = "minimumHeight";
    props_tbl[21].get = (QMember)ov3_63;
    props_tbl[21].set = (QMember)ov3_64;
    props_tbl[21].reset = 0;
    props_tbl[21].gspec = QMetaProperty::Class;
    props_tbl[21].sspec = QMetaProperty::Class;
    props_tbl[21].setFlags(QMetaProperty::NotStored|QMetaProperty::StdSet);
    props_tbl[22].t = "int";
    props_tbl[22].n = "maximumWidth";
    props_tbl[22].get = (QMember)ov3_66;
    props_tbl[22].set = (QMember)ov3_67;
    props_tbl[22].reset = 0;
    props_tbl[22].gspec = QMetaProperty::Class;
    props_tbl[22].sspec = QMetaProperty::Class;
    props_tbl[22].setFlags(QMetaProperty::NotStored|QMetaProperty::StdSet);
    props_tbl[23].t = "int";
    props_tbl[23].n = "maximumHeight";
    props_tbl[23].get = (QMember)ov3_69;
    props_tbl[23].set = (QMember)ov3_70;
    props_tbl[23].reset = 0;
    props_tbl[23].gspec = QMetaProperty::Class;
    props_tbl[23].sspec = QMetaProperty::Class;
    props_tbl[23].setFlags(QMetaProperty::NotStored|QMetaProperty::StdSet);
    props_tbl[24].t = "QSize";
    props_tbl[24].n = "sizeIncrement";
    props_tbl[24].get = (QMember)ov3_72;
    props_tbl[24].set = (QMember)ov3_73;
    props_tbl[24].reset = 0;
    props_tbl[24].gspec = QMetaProperty::Class;
    props_tbl[24].sspec = QMetaProperty::Reference;
    props_tbl[24].setFlags(QMetaProperty::StdSet);
    props_tbl[25].t = "QSize";
    props_tbl[25].n = "baseSize";
    props_tbl[25].get = (QMember)ov3_75;
    props_tbl[25].set = (QMember)ov3_76;
    props_tbl[25].reset = 0;
    props_tbl[25].gspec = QMetaProperty::Class;
    props_tbl[25].sspec = QMetaProperty::Reference;
    props_tbl[25].setFlags(QMetaProperty::StdSet);
    props_tbl[26].t = "BackgroundMode";
    props_tbl[26].n = "backgroundMode";
    props_tbl[26].get = (QMember)ov3_78;
    props_tbl[26].set = (QMember)ov3_79;
    props_tbl[26].reset = 0;
    props_tbl[26].gspec = QMetaProperty::Class;
    props_tbl[26].sspec = QMetaProperty::Class;
    props_tbl[26].enumData = &enum_tbl[0];
    props_tbl[26].setFlags(QMetaProperty::NotDesignable|QMetaProperty::StdSet);
    props_tbl[27].t = "QColor";
    props_tbl[27].n = "backgroundColor";
    props_tbl[27].get = (QMember)ov3_81;
    props_tbl[27].set = (QMember)ov3_82;
    props_tbl[27].reset = 0;
    props_tbl[27].gspec = QMetaProperty::Reference;
    props_tbl[27].sspec = QMetaProperty::Reference;
    props_tbl[27].setFlags(QMetaProperty::NotDesignable|QMetaProperty::StdSet);
    props_tbl[28].t = "QColor";
    props_tbl[28].n = "foregroundColor";
    props_tbl[28].get = (QMember)ov3_84;
    props_tbl[28].set = 0;
    props_tbl[28].reset = 0;
    props_tbl[28].gspec = QMetaProperty::Reference;
    props_tbl[28].sspec = QMetaProperty::Unspecified;
    props_tbl[29].t = "QPixmap";
    props_tbl[29].n = "backgroundPixmap";
    props_tbl[29].get = (QMember)ov3_87;
    props_tbl[29].set = (QMember)ov3_88;
    props_tbl[29].reset = 0;
    props_tbl[29].gspec = QMetaProperty::Pointer;
    props_tbl[29].sspec = QMetaProperty::Reference;
    props_tbl[29].setFlags(QMetaProperty::NotDesignable|QMetaProperty::StdSet);
    props_tbl[30].t = "QColorGroup";
    props_tbl[30].n = "colorGroup";
    props_tbl[30].get = (QMember)ov3_90;
    props_tbl[30].set = 0;
    props_tbl[30].reset = 0;
    props_tbl[30].gspec = QMetaProperty::Reference;
    props_tbl[30].sspec = QMetaProperty::Unspecified;
    props_tbl[31].t = "QPalette";
    props_tbl[31].n = "palette";
    props_tbl[31].get = (QMember)ov3_93;
    props_tbl[31].set = (QMember)ov3_94;
    props_tbl[31].reset = (QMember)ov3_95;
    props_tbl[31].gspec = QMetaProperty::Reference;
    props_tbl[31].sspec = QMetaProperty::Reference;
    props_tbl[31].setFlags(QMetaProperty::StdSet);
    props_tbl[32].t = "bool";
    props_tbl[32].n = "ownPalette";
    props_tbl[32].get = (QMember)ov3_96;
    props_tbl[32].set = 0;
    props_tbl[32].reset = 0;
    props_tbl[32].gspec = QMetaProperty::Class;
    props_tbl[32].sspec = QMetaProperty::Unspecified;
    props_tbl[33].t = "QFont";
    props_tbl[33].n = "font";
    props_tbl[33].get = (QMember)ov3_99;
    props_tbl[33].set = (QMember)ov3_100;
    props_tbl[33].reset = (QMember)ov3_101;
    props_tbl[33].gspec = QMetaProperty::Class;
    props_tbl[33].sspec = QMetaProperty::Reference;
    props_tbl[33].setFlags(QMetaProperty::StdSet);
    props_tbl[34].t = "bool";
    props_tbl[34].n = "ownFont";
    props_tbl[34].get = (QMember)ov3_102;
    props_tbl[34].set = 0;
    props_tbl[34].reset = 0;
    props_tbl[34].gspec = QMetaProperty::Class;
    props_tbl[34].sspec = QMetaProperty::Unspecified;
    props_tbl[35].t = "QCursor";
    props_tbl[35].n = "cursor";
    props_tbl[35].get = (QMember)ov3_105;
    props_tbl[35].set = (QMember)ov3_106;
    props_tbl[35].reset = (QMember)ov3_107;
    props_tbl[35].gspec = QMetaProperty::Reference;
    props_tbl[35].sspec = QMetaProperty::Reference;
    props_tbl[35].setFlags(QMetaProperty::StdSet);
    props_tbl[36].t = "bool";
    props_tbl[36].n = "ownCursor";
    props_tbl[36].get = (QMember)ov3_108;
    props_tbl[36].set = 0;
    props_tbl[36].reset = 0;
    props_tbl[36].gspec = QMetaProperty::Class;
    props_tbl[36].sspec = QMetaProperty::Unspecified;
    props_tbl[37].t = "QString";
    props_tbl[37].n = "caption";
    props_tbl[37].get = (QMember)ov3_111;
    props_tbl[37].set = (QMember)ov3_112;
    props_tbl[37].reset = 0;
    props_tbl[37].gspec = QMetaProperty::Class;
    props_tbl[37].sspec = QMetaProperty::Reference;
    props_tbl[37].setFlags(QMetaProperty::StdSet);
    props_tbl[38].t = "QPixmap";
    props_tbl[38].n = "icon";
    props_tbl[38].get = (QMember)ov3_114;
    props_tbl[38].set = (QMember)ov3_115;
    props_tbl[38].reset = 0;
    props_tbl[38].gspec = QMetaProperty::Pointer;
    props_tbl[38].sspec = QMetaProperty::Reference;
    props_tbl[38].setFlags(QMetaProperty::StdSet);
    props_tbl[39].t = "QString";
    props_tbl[39].n = "iconText";
    props_tbl[39].get = (QMember)ov3_117;
    props_tbl[39].set = (QMember)ov3_118;
    props_tbl[39].reset = 0;
    props_tbl[39].gspec = QMetaProperty::Class;
    props_tbl[39].sspec = QMetaProperty::Reference;
    props_tbl[39].setFlags(QMetaProperty::StdSet);
    props_tbl[40].t = "bool";
    props_tbl[40].n = "mouseTracking";
    props_tbl[40].get = (QMember)ov3_120;
    props_tbl[40].set = (QMember)ov3_121;
    props_tbl[40].reset = 0;
    props_tbl[40].gspec = QMetaProperty::Class;
    props_tbl[40].sspec = QMetaProperty::Class;
    props_tbl[40].setFlags(QMetaProperty::StdSet);
    props_tbl[41].t = "bool";
    props_tbl[41].n = "isActiveWindow";
    props_tbl[41].get = (QMember)ov3_123;
    props_tbl[41].set = 0;
    props_tbl[41].reset = 0;
    props_tbl[41].gspec = QMetaProperty::Class;
    props_tbl[41].sspec = QMetaProperty::Unspecified;
    props_tbl[42].t = "bool";
    props_tbl[42].n = "focusEnabled";
    props_tbl[42].get = (QMember)ov3_126;
    props_tbl[42].set = 0;
    props_tbl[42].reset = 0;
    props_tbl[42].gspec = QMetaProperty::Class;
    props_tbl[42].sspec = QMetaProperty::Unspecified;
    props_tbl[43].t = "FocusPolicy";
    props_tbl[43].n = "focusPolicy";
    props_tbl[43].get = (QMember)ov3_129;
    props_tbl[43].set = (QMember)ov3_130;
    props_tbl[43].reset = 0;
    props_tbl[43].gspec = QMetaProperty::Class;
    props_tbl[43].sspec = QMetaProperty::Class;
    props_tbl[43].enumData = &enum_tbl[2];
    props_tbl[43].setFlags(QMetaProperty::StdSet);
    props_tbl[44].t = "bool";
    props_tbl[44].n = "focus";
    props_tbl[44].get = (QMember)ov3_132;
    props_tbl[44].set = 0;
    props_tbl[44].reset = 0;
    props_tbl[44].gspec = QMetaProperty::Class;
    props_tbl[44].sspec = QMetaProperty::Unspecified;
    props_tbl[45].t = "bool";
    props_tbl[45].n = "updatesEnabled";
    props_tbl[45].get = (QMember)ov3_135;
    props_tbl[45].set = (QMember)ov3_136;
    props_tbl[45].reset = 0;
    props_tbl[45].gspec = QMetaProperty::Class;
    props_tbl[45].sspec = QMetaProperty::Class;
    props_tbl[45].setFlags(QMetaProperty::NotDesignable|QMetaProperty::StdSet);
    props_tbl[46].t = "bool";
    props_tbl[46].n = "visible";
    props_tbl[46].get = (QMember)ov3_138;
    props_tbl[46].set = 0;
    props_tbl[46].reset = 0;
    props_tbl[46].gspec = QMetaProperty::Class;
    props_tbl[46].sspec = QMetaProperty::Unspecified;
    props_tbl[47].t = "QRect";
    props_tbl[47].n = "visibleRect";
    props_tbl[47].get = (QMember)ov3_141;
    props_tbl[47].set = 0;
    props_tbl[47].reset = 0;
    props_tbl[47].gspec = QMetaProperty::Class;
    props_tbl[47].sspec = QMetaProperty::Unspecified;
    props_tbl[48].t = "bool";
    props_tbl[48].n = "hidden";
    props_tbl[48].get = (QMember)ov3_144;
    props_tbl[48].set = 0;
    props_tbl[48].reset = 0;
    props_tbl[48].gspec = QMetaProperty::Class;
    props_tbl[48].sspec = QMetaProperty::Unspecified;
    props_tbl[49].t = "bool";
    props_tbl[49].n = "minimized";
    props_tbl[49].get = (QMember)ov3_147;
    props_tbl[49].set = 0;
    props_tbl[49].reset = 0;
    props_tbl[49].gspec = QMetaProperty::Class;
    props_tbl[49].sspec = QMetaProperty::Unspecified;
    props_tbl[50].t = "QSize";
    props_tbl[50].n = "sizeHint";
    props_tbl[50].get = (QMember)ov3_150;
    props_tbl[50].set = 0;
    props_tbl[50].reset = 0;
    props_tbl[50].gspec = QMetaProperty::Class;
    props_tbl[50].sspec = QMetaProperty::Unspecified;
    props_tbl[51].t = "QSize";
    props_tbl[51].n = "minimumSizeHint";
    props_tbl[51].get = (QMember)ov3_153;
    props_tbl[51].set = 0;
    props_tbl[51].reset = 0;
    props_tbl[51].gspec = QMetaProperty::Class;
    props_tbl[51].sspec = QMetaProperty::Unspecified;
    props_tbl[52].t = "QRect";
    props_tbl[52].n = "microFocusHint";
    props_tbl[52].get = (QMember)ov3_156;
    props_tbl[52].set = 0;
    props_tbl[52].reset = 0;
    props_tbl[52].gspec = QMetaProperty::Class;
    props_tbl[52].sspec = QMetaProperty::Unspecified;
    props_tbl[53].t = "bool";
    props_tbl[53].n = "acceptDrops";
    props_tbl[53].get = (QMember)ov3_159;
    props_tbl[53].set = (QMember)ov3_160;
    props_tbl[53].reset = 0;
    props_tbl[53].gspec = QMetaProperty::Class;
    props_tbl[53].sspec = QMetaProperty::Class;
    props_tbl[53].setFlags(QMetaProperty::StdSet);
    props_tbl[54].t = "bool";
    props_tbl[54].n = "autoMask";
    props_tbl[54].get = (QMember)ov3_162;
    props_tbl[54].set = (QMember)ov3_163;
    props_tbl[54].reset = 0;
    props_tbl[54].gspec = QMetaProperty::Class;
    props_tbl[54].sspec = QMetaProperty::Class;
    props_tbl[54].setFlags(QMetaProperty::StdSet);
    props_tbl[55].t = "BackgroundOrigin";
    props_tbl[55].n = "backgroundOrigin";
    props_tbl[55].get = (QMember)ov3_165;
    props_tbl[55].set = (QMember)ov3_166;
    props_tbl[55].reset = 0;
    props_tbl[55].gspec = QMetaProperty::Class;
    props_tbl[55].sspec = QMetaProperty::Class;
    props_tbl[55].enumData = &enum_tbl[3];
    props_tbl[55].setFlags(QMetaProperty::StdSet);
    props_tbl[56].t = "bool";
    props_tbl[56].n = "customWhatsThis";
    props_tbl[56].get = (QMember)ov3_168;
    props_tbl[56].set = 0;
    props_tbl[56].reset = 0;
    props_tbl[56].gspec = QMetaProperty::Class;
    props_tbl[56].sspec = QMetaProperty::Unspecified;
#endif // QT_NO_PROPERTIES
    typedef void (QWidget::*m1_t0)(bool);
    typedef void (QObject::*om1_t0)(bool);
    typedef void (QWidget::*m1_t1)(bool);
    typedef void (QObject::*om1_t1)(bool);
    typedef void (QWidget::*m1_t2)(const QString&);
    typedef void (QObject::*om1_t2)(const QString&);
    typedef void (QWidget::*m1_t3)(const QPixmap&);
    typedef void (QObject::*om1_t3)(const QPixmap&);
    typedef void (QWidget::*m1_t4)(const QString&);
    typedef void (QObject::*om1_t4)(const QString&);
    typedef void (QWidget::*m1_t5)(bool);
    typedef void (QObject::*om1_t5)(bool);
    typedef void (QWidget::*m1_t6)();
    typedef void (QObject::*om1_t6)();
    typedef void (QWidget::*m1_t7)();
    typedef void (QObject::*om1_t7)();
    typedef void (QWidget::*m1_t8)(bool);
    typedef void (QObject::*om1_t8)(bool);
    typedef void (QWidget::*m1_t9)();
    typedef void (QObject::*om1_t9)();
    typedef void (QWidget::*m1_t10)(int,int,int,int);
    typedef void (QObject::*om1_t10)(int,int,int,int);
    typedef void (QWidget::*m1_t11)(const QRect&);
    typedef void (QObject::*om1_t11)(const QRect&);
    typedef void (QWidget::*m1_t12)();
    typedef void (QObject::*om1_t12)();
    typedef void (QWidget::*m1_t13)(bool);
    typedef void (QObject::*om1_t13)(bool);
    typedef void (QWidget::*m1_t14)(int,int,int,int,bool);
    typedef void (QObject::*om1_t14)(int,int,int,int,bool);
    typedef void (QWidget::*m1_t15)(const QRect&,bool);
    typedef void (QObject::*om1_t15)(const QRect&,bool);
    typedef void (QWidget::*m1_t16)(const QRegion&,bool);
    typedef void (QObject::*om1_t16)(const QRegion&,bool);
    typedef void (QWidget::*m1_t17)();
    typedef void (QObject::*om1_t17)();
    typedef void (QWidget::*m1_t18)();
    typedef void (QObject::*om1_t18)();
    typedef void (QWidget::*m1_t19)();
    typedef void (QObject::*om1_t19)();
    typedef void (QWidget::*m1_t20)();
    typedef void (QObject::*om1_t20)();
    typedef void (QWidget::*m1_t21)();
    typedef void (QObject::*om1_t21)();
    typedef void (QWidget::*m1_t22)();
    typedef void (QObject::*om1_t22)();
    typedef void (QWidget::*m1_t23)();
    typedef void (QObject::*om1_t23)();
    typedef void (QWidget::*m1_t24)();
    typedef void (QObject::*om1_t24)();
    typedef void (QWidget::*m1_t25)()const;
    typedef void (QObject::*om1_t25)()const;
    typedef bool (QWidget::*m1_t26)();
    typedef bool (QObject::*om1_t26)();
    typedef void (QWidget::*m1_t27)();
    typedef void (QObject::*om1_t27)();
    typedef void (QWidget::*m1_t28)();
    typedef void (QObject::*om1_t28)();
    typedef void (QWidget::*m1_t29)(QWidget*);
    typedef void (QObject::*om1_t29)(QWidget*);
    typedef void (QWidget::*m1_t30)(int,int);
    typedef void (QObject::*om1_t30)(int,int);
    typedef void (QWidget::*m1_t31)(const QPoint&);
    typedef void (QObject::*om1_t31)(const QPoint&);
    typedef void (QWidget::*m1_t32)(int,int);
    typedef void (QObject::*om1_t32)(int,int);
    typedef void (QWidget::*m1_t33)(const QSize&);
    typedef void (QObject::*om1_t33)(const QSize&);
    typedef void (QWidget::*m1_t34)(int,int,int,int);
    typedef void (QObject::*om1_t34)(int,int,int,int);
    typedef void (QWidget::*m1_t35)(const QRect&);
    typedef void (QObject::*om1_t35)(const QRect&);
    typedef void (QWidget::*m1_t36)();
    typedef void (QObject::*om1_t36)();
    m1_t0 v1_0 = &QWidget::setEnabled;
    om1_t0 ov1_0 = (om1_t0)v1_0;
    m1_t1 v1_1 = &QWidget::setDisabled;
    om1_t1 ov1_1 = (om1_t1)v1_1;
    m1_t2 v1_2 = &QWidget::setCaption;
    om1_t2 ov1_2 = (om1_t2)v1_2;
    m1_t3 v1_3 = &QWidget::setIcon;
    om1_t3 ov1_3 = (om1_t3)v1_3;
    m1_t4 v1_4 = &QWidget::setIconText;
    om1_t4 ov1_4 = (om1_t4)v1_4;
    m1_t5 v1_5 = &QWidget::setMouseTracking;
    om1_t5 ov1_5 = (om1_t5)v1_5;
    m1_t6 v1_6 = &QWidget::setFocus;
    om1_t6 ov1_6 = (om1_t6)v1_6;
    m1_t7 v1_7 = &QWidget::clearFocus;
    om1_t7 ov1_7 = (om1_t7)v1_7;
    m1_t8 v1_8 = &QWidget::setUpdatesEnabled;
    om1_t8 ov1_8 = (om1_t8)v1_8;
    m1_t9 v1_9 = &QWidget::update;
    om1_t9 ov1_9 = (om1_t9)v1_9;
    m1_t10 v1_10 = &QWidget::update;
    om1_t10 ov1_10 = (om1_t10)v1_10;
    m1_t11 v1_11 = &QWidget::update;
    om1_t11 ov1_11 = (om1_t11)v1_11;
    m1_t12 v1_12 = &QWidget::repaint;
    om1_t12 ov1_12 = (om1_t12)v1_12;
    m1_t13 v1_13 = &QWidget::repaint;
    om1_t13 ov1_13 = (om1_t13)v1_13;
    m1_t14 v1_14 = &QWidget::repaint;
    om1_t14 ov1_14 = (om1_t14)v1_14;
    m1_t15 v1_15 = &QWidget::repaint;
    om1_t15 ov1_15 = (om1_t15)v1_15;
    m1_t16 v1_16 = &QWidget::repaint;
    om1_t16 ov1_16 = (om1_t16)v1_16;
    m1_t17 v1_17 = &QWidget::show;
    om1_t17 ov1_17 = (om1_t17)v1_17;
    m1_t18 v1_18 = &QWidget::hide;
    om1_t18 ov1_18 = (om1_t18)v1_18;
    m1_t19 v1_19 = &QWidget::iconify;
    om1_t19 ov1_19 = (om1_t19)v1_19;
    m1_t20 v1_20 = &QWidget::showMinimized;
    om1_t20 ov1_20 = (om1_t20)v1_20;
    m1_t21 v1_21 = &QWidget::showMaximized;
    om1_t21 ov1_21 = (om1_t21)v1_21;
    m1_t22 v1_22 = &QWidget::showFullScreen;
    om1_t22 ov1_22 = (om1_t22)v1_22;
    m1_t23 v1_23 = &QWidget::showNormal;
    om1_t23 ov1_23 = (om1_t23)v1_23;
    m1_t24 v1_24 = &QWidget::polish;
    om1_t24 ov1_24 = (om1_t24)v1_24;
    m1_t25 v1_25 = &QWidget::constPolish;
    om1_t25 ov1_25 = (om1_t25)v1_25;
    m1_t26 v1_26 = &QWidget::close;
    om1_t26 ov1_26 = (om1_t26)v1_26;
    m1_t27 v1_27 = &QWidget::raise;
    om1_t27 ov1_27 = (om1_t27)v1_27;
    m1_t28 v1_28 = &QWidget::lower;
    om1_t28 ov1_28 = (om1_t28)v1_28;
    m1_t29 v1_29 = &QWidget::stackUnder;
    om1_t29 ov1_29 = (om1_t29)v1_29;
    m1_t30 v1_30 = &QWidget::move;
    om1_t30 ov1_30 = (om1_t30)v1_30;
    m1_t31 v1_31 = &QWidget::move;
    om1_t31 ov1_31 = (om1_t31)v1_31;
    m1_t32 v1_32 = &QWidget::resize;
    om1_t32 ov1_32 = (om1_t32)v1_32;
    m1_t33 v1_33 = &QWidget::resize;
    om1_t33 ov1_33 = (om1_t33)v1_33;
    m1_t34 v1_34 = &QWidget::setGeometry;
    om1_t34 ov1_34 = (om1_t34)v1_34;
    m1_t35 v1_35 = &QWidget::setGeometry;
    om1_t35 ov1_35 = (om1_t35)v1_35;
    m1_t36 v1_36 = &QWidget::focusProxyDestroyed;
    om1_t36 ov1_36 = (om1_t36)v1_36;
    QMetaData *slot_tbl = QMetaObject::new_metadata(37);
    QMetaData::Access *slot_tbl_access = QMetaObject::new_metaaccess(37);
    slot_tbl[0].name = "setEnabled(bool)";
    slot_tbl[0].ptr = (QMember)ov1_0;
    slot_tbl_access[0] = QMetaData::Public;
    slot_tbl[1].name = "setDisabled(bool)";
    slot_tbl[1].ptr = (QMember)ov1_1;
    slot_tbl_access[1] = QMetaData::Public;
    slot_tbl[2].name = "setCaption(const QString&)";
    slot_tbl[2].ptr = (QMember)ov1_2;
    slot_tbl_access[2] = QMetaData::Public;
    slot_tbl[3].name = "setIcon(const QPixmap&)";
    slot_tbl[3].ptr = (QMember)ov1_3;
    slot_tbl_access[3] = QMetaData::Public;
    slot_tbl[4].name = "setIconText(const QString&)";
    slot_tbl[4].ptr = (QMember)ov1_4;
    slot_tbl_access[4] = QMetaData::Public;
    slot_tbl[5].name = "setMouseTracking(bool)";
    slot_tbl[5].ptr = (QMember)ov1_5;
    slot_tbl_access[5] = QMetaData::Public;
    slot_tbl[6].name = "setFocus()";
    slot_tbl[6].ptr = (QMember)ov1_6;
    slot_tbl_access[6] = QMetaData::Public;
    slot_tbl[7].name = "clearFocus()";
    slot_tbl[7].ptr = (QMember)ov1_7;
    slot_tbl_access[7] = QMetaData::Public;
    slot_tbl[8].name = "setUpdatesEnabled(bool)";
    slot_tbl[8].ptr = (QMember)ov1_8;
    slot_tbl_access[8] = QMetaData::Public;
    slot_tbl[9].name = "update()";
    slot_tbl[9].ptr = (QMember)ov1_9;
    slot_tbl_access[9] = QMetaData::Public;
    slot_tbl[10].name = "update(int,int,int,int)";
    slot_tbl[10].ptr = (QMember)ov1_10;
    slot_tbl_access[10] = QMetaData::Public;
    slot_tbl[11].name = "update(const QRect&)";
    slot_tbl[11].ptr = (QMember)ov1_11;
    slot_tbl_access[11] = QMetaData::Public;
    slot_tbl[12].name = "repaint()";
    slot_tbl[12].ptr = (QMember)ov1_12;
    slot_tbl_access[12] = QMetaData::Public;
    slot_tbl[13].name = "repaint(bool)";
    slot_tbl[13].ptr = (QMember)ov1_13;
    slot_tbl_access[13] = QMetaData::Public;
    slot_tbl[14].name = "repaint(int,int,int,int,bool)";
    slot_tbl[14].ptr = (QMember)ov1_14;
    slot_tbl_access[14] = QMetaData::Public;
    slot_tbl[15].name = "repaint(const QRect&,bool)";
    slot_tbl[15].ptr = (QMember)ov1_15;
    slot_tbl_access[15] = QMetaData::Public;
    slot_tbl[16].name = "repaint(const QRegion&,bool)";
    slot_tbl[16].ptr = (QMember)ov1_16;
    slot_tbl_access[16] = QMetaData::Public;
    slot_tbl[17].name = "show()";
    slot_tbl[17].ptr = (QMember)ov1_17;
    slot_tbl_access[17] = QMetaData::Public;
    slot_tbl[18].name = "hide()";
    slot_tbl[18].ptr = (QMember)ov1_18;
    slot_tbl_access[18] = QMetaData::Public;
    slot_tbl[19].name = "iconify()";
    slot_tbl[19].ptr = (QMember)ov1_19;
    slot_tbl_access[19] = QMetaData::Public;
    slot_tbl[20].name = "showMinimized()";
    slot_tbl[20].ptr = (QMember)ov1_20;
    slot_tbl_access[20] = QMetaData::Public;
    slot_tbl[21].name = "showMaximized()";
    slot_tbl[21].ptr = (QMember)ov1_21;
    slot_tbl_access[21] = QMetaData::Public;
    slot_tbl[22].name = "showFullScreen()";
    slot_tbl[22].ptr = (QMember)ov1_22;
    slot_tbl_access[22] = QMetaData::Public;
    slot_tbl[23].name = "showNormal()";
    slot_tbl[23].ptr = (QMember)ov1_23;
    slot_tbl_access[23] = QMetaData::Public;
    slot_tbl[24].name = "polish()";
    slot_tbl[24].ptr = (QMember)ov1_24;
    slot_tbl_access[24] = QMetaData::Public;
    slot_tbl[25].name = "constPolish()";
    slot_tbl[25].ptr = (QMember)ov1_25;
    slot_tbl_access[25] = QMetaData::Public;
    slot_tbl[26].name = "close()";
    slot_tbl[26].ptr = (QMember)ov1_26;
    slot_tbl_access[26] = QMetaData::Public;
    slot_tbl[27].name = "raise()";
    slot_tbl[27].ptr = (QMember)ov1_27;
    slot_tbl_access[27] = QMetaData::Public;
    slot_tbl[28].name = "lower()";
    slot_tbl[28].ptr = (QMember)ov1_28;
    slot_tbl_access[28] = QMetaData::Public;
    slot_tbl[29].name = "stackUnder(QWidget*)";
    slot_tbl[29].ptr = (QMember)ov1_29;
    slot_tbl_access[29] = QMetaData::Public;
    slot_tbl[30].name = "move(int,int)";
    slot_tbl[30].ptr = (QMember)ov1_30;
    slot_tbl_access[30] = QMetaData::Public;
    slot_tbl[31].name = "move(const QPoint&)";
    slot_tbl[31].ptr = (QMember)ov1_31;
    slot_tbl_access[31] = QMetaData::Public;
    slot_tbl[32].name = "resize(int,int)";
    slot_tbl[32].ptr = (QMember)ov1_32;
    slot_tbl_access[32] = QMetaData::Public;
    slot_tbl[33].name = "resize(const QSize&)";
    slot_tbl[33].ptr = (QMember)ov1_33;
    slot_tbl_access[33] = QMetaData::Public;
    slot_tbl[34].name = "setGeometry(int,int,int,int)";
    slot_tbl[34].ptr = (QMember)ov1_34;
    slot_tbl_access[34] = QMetaData::Public;
    slot_tbl[35].name = "setGeometry(const QRect&)";
    slot_tbl[35].ptr = (QMember)ov1_35;
    slot_tbl_access[35] = QMetaData::Public;
    slot_tbl[36].name = "focusProxyDestroyed()";
    slot_tbl[36].ptr = (QMember)ov1_36;
    slot_tbl_access[36] = QMetaData::Private;
    metaObj = QMetaObject::new_metaobject(
	"QWidget", "QObject",
	slot_tbl, 37,
	0, 0,
#ifndef QT_NO_PROPERTIES
	props_tbl, 57,
	enum_tbl, 4,
#endif // QT_NO_PROPERTIES
	0, 0 );
    metaObj->set_slot_access( slot_tbl_access );
#ifndef QT_NO_PROPERTIES
#endif // QT_NO_PROPERTIES
    return metaObj;
}
