# Blank Makefile for non-compilable items (I.E Fonts, Icons etc.)
# Just set DIST_TARGET_PATH below & copy this into
# the directory you are adding.
# REMEMBER: Add the new directory to the Makefile in the parent
# directory!

# 140603 Added Vera fonts			- Kaj

DIST_TARGET_PATH := $(DIST_DIR)/atheos/sys/fonts/

all:

deps:

install:

doc:

install-doc:

dist:
	@cp -r base/* vera/*.ttf $(DIST_TARGET_PATH)

clean:

