dist:
	@echo Copying: unarj, unrar, uncab, unace, fastjar, grepjar, makeself.sh to $(DIST_DIR)/Applications/Archiver/bin
	@cp -f unarj unrar unace uncab fastjar grepjar unzip makeself.sh $(DIST_DIR)/Applications/Archiver/bin   


