#ifndef __F_CAT_sIDE_H__
#define __F_CAT_sIDE_H__
#include <util/catalog.h>
#ifndef CATALOG_NO_IDS
#define ID_MSG_PWND_TITLE 100
#define ID_MSG_PWND_MENU_APPLICATION 200
#define ID_MSG_PWND_MENU_APPLICATION_ABOUT 201
#define ID_MSG_PWND_MENU_APPLICATION_QUIT 202
#define ID_MSG_PWND_MENU_PROJECT 210
#define ID_MSG_PWND_MENU_PROJECT_NEW 211
#define ID_MSG_PWND_MENU_PROJECT_OPEN 212
#define ID_MSG_PWND_MENU_PROJECT_SAVE 213
#define ID_MSG_PWND_MENU_PROJECT_SAVEAS 214
#define ID_MSG_PWND_MENU_PROJECT_PREF 215
#define ID_MSG_PWND_MENU_PROJECT_GROUPS 216
#define ID_MSG_PWND_MENU_PROJECT_NEW_FILE 217
#define ID_MSG_PWND_MENU_PROJECT_ADD_FILE 218
#define ID_MSG_PWND_MENU_PROJECT_ADD_LIB 219
#define ID_MSG_PWND_MENU_PROJECT_REMOVE_FILE 220
#define ID_MSG_PWND_MENU_BUILD 230
#define ID_MSG_PWND_MENU_BUILD_CLEAN 231
#define ID_MSG_PWND_MENU_BUILD_MAKE 232
#define ID_MSG_PWND_MENU_BUILD_RUN 233
#define ID_MSG_PWND_MENU_BUILD_EXPORT_MAKEFILE 234
#define ID_MSG_PWND_ABOUT_TITLE 235
#define ID_MSG_PWND_ABOUT 236
#define ID_MSG_PWND_LIST_FILE 237
#define ID_MSG_PWND_LIST_TYPE 238
#define ID_MSG_PWND_NO_GROUPS 260
#define ID_MSG_PWND_COULD_NOT_OPEN_PROJ 261
#define ID_MSG_PWND_COULD_NOT_OPEN_FILE 262
#define ID_MSG_PWND_COULD_NOT_SAVE_PROJ 263
#define ID_MSG_PWND_NOT_IN_PROJ_DIR 264
#define ID_MSG_TYPE_HEADER 300
#define ID_MSG_TYPE_C 301
#define ID_MSG_TYPE_CPP 302
#define ID_MSG_TYPE_LIB 303
#define ID_MSG_TYPE_OTHER 304
#define ID_MSG_TYPE_RES 305
#define ID_MSG_TYPE_CATALOG 306
#define ID_MSG_TYPE_IF 307
#define ID_MSG_TYPE_UNKNOWN 308
#define ID_MSG_BUTTON_OK 400
#define ID_MSG_BUTTON_CANCEL 401
#define ID_MSG_BUTTON_UP 402
#define ID_MSG_BUTTON_DOWN 403
#define ID_MSG_BUTTON_ADD 404
#define ID_MSG_BUTTON_REMOVE 405
#define ID_MSG_ADDWND_TITLE 500
#define ID_MSG_ADDWND_NAME 501
#define ID_MSG_ADDWND_FILE 502
#define ID_MSG_NEWWND_TITLE 600
#define ID_MSG_NEWWND_PROJECTS 601
#define ID_MSG_NEWWND_NAME 602
#define ID_MSG_NEWWMD_DIR 603
#define ID_MSG_NEWWND_ERR_TITLE 604
#define ID_MSG_NEWWND_ERR_EXTR 605
#define ID_MSG_NEWWND_NO_LOC_NAME 606
#define ID_MSG_NEWWND_NO_LOC 607
#define ID_MSG_NEWWND_NO_NAME 608
#define ID_MSG_NEWWND_NO_DIR 609
#define ID_MSG_NEWWND_NO_DIR_1 610
#define ID_MSG_NEWWND_NO_DIR_2 611
#define ID_MSG_PPREF_TITLE 700
#define ID_MSG_PPREF_TARGET 701
#define ID_MSG_PPREF_CATEGORY 702
#define ID_MSG_PPREF_INSTALL_PATH 703
#define ID_MSG_PPREF_CFLAGS 704
#define ID_MSG_PPREF_LFLAGS 705
#define ID_MSG_GROUPS_TITLE 800
#define ID_MSG_GROUPS_LIST 801
#define ID_MSG_ADDLIB_TITLE 900
#define ID_MSG_ADDLIB_SELECT 901
#define ID_MSG_ADDLIB_CUSTOM 902
#define ID_MSG_ADDLIB_GROUP 903
#endif
#ifndef CATALOG_NO_LSTRINGS
#define MSG_PWND_TITLE os::LString( 100 )
#define MSG_PWND_MENU_APPLICATION os::LString( 200 )
#define MSG_PWND_MENU_APPLICATION_ABOUT os::LString( 201 )
#define MSG_PWND_MENU_APPLICATION_QUIT os::LString( 202 )
#define MSG_PWND_MENU_PROJECT os::LString( 210 )
#define MSG_PWND_MENU_PROJECT_NEW os::LString( 211 )
#define MSG_PWND_MENU_PROJECT_OPEN os::LString( 212 )
#define MSG_PWND_MENU_PROJECT_SAVE os::LString( 213 )
#define MSG_PWND_MENU_PROJECT_SAVEAS os::LString( 214 )
#define MSG_PWND_MENU_PROJECT_PREF os::LString( 215 )
#define MSG_PWND_MENU_PROJECT_GROUPS os::LString( 216 )
#define MSG_PWND_MENU_PROJECT_NEW_FILE os::LString( 217 )
#define MSG_PWND_MENU_PROJECT_ADD_FILE os::LString( 218 )
#define MSG_PWND_MENU_PROJECT_ADD_LIB os::LString( 219 )
#define MSG_PWND_MENU_PROJECT_REMOVE_FILE os::LString( 220 )
#define MSG_PWND_MENU_BUILD os::LString( 230 )
#define MSG_PWND_MENU_BUILD_CLEAN os::LString( 231 )
#define MSG_PWND_MENU_BUILD_MAKE os::LString( 232 )
#define MSG_PWND_MENU_BUILD_RUN os::LString( 233 )
#define MSG_PWND_MENU_BUILD_EXPORT_MAKEFILE os::LString( 234 )
#define MSG_PWND_ABOUT_TITLE os::LString( 235 )
#define MSG_PWND_ABOUT os::LString( 236 )
#define MSG_PWND_LIST_FILE os::LString( 237 )
#define MSG_PWND_LIST_TYPE os::LString( 238 )
#define MSG_PWND_NO_GROUPS os::LString( 260 )
#define MSG_PWND_COULD_NOT_OPEN_PROJ os::LString( 261 )
#define MSG_PWND_COULD_NOT_OPEN_FILE os::LString( 262 )
#define MSG_PWND_COULD_NOT_SAVE_PROJ os::LString( 263 )
#define MSG_PWND_NOT_IN_PROJ_DIR os::LString( 264 )
#define MSG_TYPE_HEADER os::LString( 300 )
#define MSG_TYPE_C os::LString( 301 )
#define MSG_TYPE_CPP os::LString( 302 )
#define MSG_TYPE_LIB os::LString( 303 )
#define MSG_TYPE_OTHER os::LString( 304 )
#define MSG_TYPE_RES os::LString( 305 )
#define MSG_TYPE_CATALOG os::LString( 306 )
#define MSG_TYPE_IF os::LString( 307 )
#define MSG_TYPE_UNKNOWN os::LString( 308 )
#define MSG_BUTTON_OK os::LString( 400 )
#define MSG_BUTTON_CANCEL os::LString( 401 )
#define MSG_BUTTON_UP os::LString( 402 )
#define MSG_BUTTON_DOWN os::LString( 403 )
#define MSG_BUTTON_ADD os::LString( 404 )
#define MSG_BUTTON_REMOVE os::LString( 405 )
#define MSG_ADDWND_TITLE os::LString( 500 )
#define MSG_ADDWND_NAME os::LString( 501 )
#define MSG_ADDWND_FILE os::LString( 502 )
#define MSG_NEWWND_TITLE os::LString( 600 )
#define MSG_NEWWND_PROJECTS os::LString( 601 )
#define MSG_NEWWND_NAME os::LString( 602 )
#define MSG_NEWWMD_DIR os::LString( 603 )
#define MSG_NEWWND_ERR_TITLE os::LString( 604 )
#define MSG_NEWWND_ERR_EXTR os::LString( 605 )
#define MSG_NEWWND_NO_LOC_NAME os::LString( 606 )
#define MSG_NEWWND_NO_LOC os::LString( 607 )
#define MSG_NEWWND_NO_NAME os::LString( 608 )
#define MSG_NEWWND_NO_DIR os::LString( 609 )
#define MSG_NEWWND_NO_DIR_1 os::LString( 610 )
#define MSG_NEWWND_NO_DIR_2 os::LString( 611 )
#define MSG_PPREF_TITLE os::LString( 700 )
#define MSG_PPREF_TARGET os::LString( 701 )
#define MSG_PPREF_CATEGORY os::LString( 702 )
#define MSG_PPREF_INSTALL_PATH os::LString( 703 )
#define MSG_PPREF_CFLAGS os::LString( 704 )
#define MSG_PPREF_LFLAGS os::LString( 705 )
#define MSG_GROUPS_TITLE os::LString( 800 )
#define MSG_GROUPS_LIST os::LString( 801 )
#define MSG_ADDLIB_TITLE os::LString( 900 )
#define MSG_ADDLIB_SELECT os::LString( 901 )
#define MSG_ADDLIB_CUSTOM os::LString( 902 )
#define MSG_ADDLIB_GROUP os::LString( 903 )
#endif
#endif /* __F_CAT_resources/sIDE_H__ */
