DIST_TARGET_PATH := $(DIST_DIR)/atheos/sys/include

all:

deps:

install:

doc:

install-doc:

dist:
	@cp -pr * $(DIST_TARGET_PATH)
	rm -r $(DIST_TARGET_PATH)/CVS
	rm $(DIST_TARGET_PATH)/Makefile

clean:

