#!/bin/sh
#
# This is the initialisation script for Syllable.
# 
# ************************************************************************** #
#                            DO NOT EDIT THIS FILE!                          #
# ************************************************************************** #
#
# init.sh is called directly by the init process; do not call this file
# yourself.
# This script in turn calls /etc/profile, net_init.sh and user_init.sh  If you
# wish to modify your configuration or initialisation process you should edit
# these files instead.

# Configure basic environment
source /etc/profile

# Add a few additional symlinks which simplify navigation around the
# filesystem
ln -s /usr/glibc2/include /include
ln -s /system/include /ainc
ln -s /atheos/Applications /Applications
ln -s /home/root /root

# Silently empty the temporary directory
rm -r $TEMP/* >>/dev/null 2>&1 &

# Log local kernel output into /var/log/kernel
dbterm 8 >>/var/log/kernel &

# If the graphical login isn't available, failsafe to a standalone server and
# abort further initialisation
if [ ! -e /bin/dlogin ]
then
  aterm &
  exit 1
fi

# Start the graphical login and servers
/bin/dlogin </dev/null >>/var/log/desktop 2>&1 &
/system/mediaserver >>/dev/null &
/system/registrar >>/dev/null &

# Check for network changes & configure the network if required
/Applications/Preferences/Network --detect

if [ -e /system/net_init.sh ]
then
  source /system/net_init.sh
fi

# Do user initialisation and exit
source /system/user_init.sh

exit 0
