# Blank Makefile for non-compilable items (I.E Fonts, Icons etc.)
# Just set DIST_TARGET_PATH below & copy this into
# the directory you are adding.
# REMEMBER: Add the new directory to the Makefile in the parent
# directory!

DIST_TARGET_PATH := $(IMAGE)/system/

all:

deps:

install:

doc:

install-doc:

dist:
	cp -a *.sh $(DIST_TARGET_PATH)

clean:

