#ifndef __F_CAT_mediaplayer_H__
#define __F_CAT_mediaplayer_H__
#include <util/catalog.h>
#ifndef CATALOG_NO_IDS
#define ID_MSG_MAINWND_TITLE 100
#define ID_MSG_MAINWND_MENU_APPLICATION 200
#define ID_MSG_MAINWND_MENU_APPLICATION_ABOUT 201
#define ID_MSG_MAINWND_MENU_APPLICATION_QUIT 202
#define ID_MSG_MAINWND_MENU_FILE 300
#define ID_MSG_MAINWND_MENU_FILE_OPEN 301
#define ID_MSG_MAINWND_MENU_FILE_OPEN_INPUT 302
#define ID_MSG_MAINWND_MENU_FILE_FULLSCREEN 303
#define ID_MSG_MAINWND_MENU_TRACKS 400
#define ID_MSG_ABOUTWND_TITLE 1000
#define ID_MSG_ABOUTWND_TEXT 1001
#define ID_MSG_ABOUTWND_OK 1002
#define ID_MSG_ERRWND_TITLE 1100
#define ID_MSG_ERRWND_OK 1101
#define ID_MSG_ERRWND_CANTPLAY 1102
#define ID_MSG_TRACK_MENU_ITEM 2000
#endif
#ifndef CATALOG_NO_LSTRINGS
#define MSG_MAINWND_TITLE os::LString( 100 )
#define MSG_MAINWND_MENU_APPLICATION os::LString( 200 )
#define MSG_MAINWND_MENU_APPLICATION_ABOUT os::LString( 201 )
#define MSG_MAINWND_MENU_APPLICATION_QUIT os::LString( 202 )
#define MSG_MAINWND_MENU_FILE os::LString( 300 )
#define MSG_MAINWND_MENU_FILE_OPEN os::LString( 301 )
#define MSG_MAINWND_MENU_FILE_OPEN_INPUT os::LString( 302 )
#define MSG_MAINWND_MENU_FILE_FULLSCREEN os::LString( 303 )
#define MSG_MAINWND_MENU_TRACKS os::LString( 400 )
#define MSG_ABOUTWND_TITLE os::LString( 1000 )
#define MSG_ABOUTWND_TEXT os::LString( 1001 )
#define MSG_ABOUTWND_OK os::LString( 1002 )
#define MSG_ERRWND_TITLE os::LString( 1100 )
#define MSG_ERRWND_OK os::LString( 1101 )
#define MSG_ERRWND_CANTPLAY os::LString( 1102 )
#define MSG_TRACK_MENU_ITEM os::LString( 2000 )
#endif
#endif /* __F_CAT_mediaplayer_H__ */
