#ifndef __F_CAT_resources/Network_H__
#define __F_CAT_resources/Network_H__

#include <util/catalog.h>

#ifndef CATALOG_NO_IDS

#define ID_MSG_APP_DETECT_ALERT_TITLE 100
#define ID_MSG_APP_DETECT_ALERT_MESSAGE 101
#define ID_MSG_APP_DETECT_ALERT_CLOSE 102
#define ID_MSG_APP_DETECT_NO_CHANGE 103
#define ID_MSG_MAINWIN_TITLE 200
#define ID_MSG_MAINWIN_IFACE_COL_NAME 201
#define ID_MSG_MAINWIN_IFACE_COL_ENABLED 202
#define ID_MSG_MAINWIN_IFACE_TITLE 203
#define ID_MSG_MAINWIN_IFACE_PROPERTIES 204
#define ID_MSG_MAINWIN_IFACE_DEFAULT_GW 205
#define ID_MSG_MAINWIN_GENERAL_HOSTNAME 206
#define ID_MSG_MAINWIN_GENERAL_DOMAIN 207
#define ID_MSG_MAINWIN_GENERAL_TITLE 208
#define ID_MSG_MAINWIN_DNS_NS_FRAME 209
#define ID_MSG_MAINWIN_DNS_NS_COL 210
#define ID_MSG_MAINWIN_DNS_NS_ADD 211
#define ID_MSG_MAINWIN_DNS_NS_DELETE 212
#define ID_MSG_MAINWIN_DNS_SD_FRAME 213
#define ID_MSG_MAINWIN_DNS_SD_COL 214
#define ID_MSG_MAINWIN_DNS_SD_ADD 215
#define ID_MSG_MAINWIN_DNS_SD_DELETE 216
#define ID_MSG_MAINWIN_DNS_TITLE 217
#define ID_MSG_MAINWIN_HOSTS_COL_ADDRESS 218
#define ID_MSG_MAINWIN_HOSTS_COL_ALIASES 219
#define ID_MSG_MAINWIN_HOSTS_ADD 220
#define ID_MSG_MAINWIN_HOSTS_DELETE 221
#define ID_MSG_MAINWIN_HOSTS_TITLE 222
#define ID_MSG_MAINWIN_APPLY 223
#define ID_MSG_MAINWIN_REVERT 224
#define ID_MSG_MAINWIN_CLOSE 225
#define ID_MSG_MAINWIN_NEW_NAMESERVER 226
#define ID_MSG_MAINWIN_NEW_SEARCH_DOMAIN 227
#define ID_MSG_MAINWIN_NEW_HOST_ADDRESS 228
#define ID_MSG_MAINWIN_NEW_HOST_ALIASES 229
#define ID_MSG_MAINWIN_IFACE_ENABLED_YES 230
#define ID_MSG_MAINWIN_IFACE_ENABLED_NO 231
#define ID_MSG_IFWIN_TITLE 300
#define ID_MSG_IFWIN_TYPE 301
#define ID_MSG_IFWIN_TYPE_STATIC 302
#define ID_MSG_IFWIN_TYPE_DHCP 303
#define ID_MSG_IFWIN_ADDRESS 304
#define ID_MSG_IFWIN_NETMASK 305
#define ID_MSG_IFWIN_GATEWAY 306
#define ID_MSG_IFWIN_ENABLED 307
#define ID_MSG_IFWIN_APPLY 308
#define ID_MSG_IFWIN_CLOSE 309
#define ID_MSG_IFWIN_ERR_IP_ADDRESS 310
#define ID_MSG_IFWIN_ERR_NETMASK 311
#define ID_MSG_IFWIN_ERR_GATEWAY 312
#define ID_MSG_IFWIN_ERR_TITLE 313
#define ID_MSG_IFWIN_ERR_CLOSE 314

#endif

#ifndef CATALOG_NO_LSTRINGS

#define MSG_APP_DETECT_ALERT_TITLE os::LString( 100 )
#define MSG_APP_DETECT_ALERT_MESSAGE os::LString( 101 )
#define MSG_APP_DETECT_ALERT_CLOSE os::LString( 102 )
#define MSG_APP_DETECT_NO_CHANGE os::LString( 103 )
#define MSG_MAINWIN_TITLE os::LString( 200 )
#define MSG_MAINWIN_IFACE_COL_NAME os::LString( 201 )
#define MSG_MAINWIN_IFACE_COL_ENABLED os::LString( 202 )
#define MSG_MAINWIN_IFACE_TITLE os::LString( 203 )
#define MSG_MAINWIN_IFACE_PROPERTIES os::LString( 204 )
#define MSG_MAINWIN_IFACE_DEFAULT_GW os::LString( 205 )
#define MSG_MAINWIN_GENERAL_HOSTNAME os::LString( 206 )
#define MSG_MAINWIN_GENERAL_DOMAIN os::LString( 207 )
#define MSG_MAINWIN_GENERAL_TITLE os::LString( 208 )
#define MSG_MAINWIN_DNS_NS_FRAME os::LString( 209 )
#define MSG_MAINWIN_DNS_NS_COL os::LString( 210 )
#define MSG_MAINWIN_DNS_NS_ADD os::LString( 211 )
#define MSG_MAINWIN_DNS_NS_DELETE os::LString( 212 )
#define MSG_MAINWIN_DNS_SD_FRAME os::LString( 213 )
#define MSG_MAINWIN_DNS_SD_COL os::LString( 214 )
#define MSG_MAINWIN_DNS_SD_ADD os::LString( 215 )
#define MSG_MAINWIN_DNS_SD_DELETE os::LString( 216 )
#define MSG_MAINWIN_DNS_TITLE os::LString( 217 )
#define MSG_MAINWIN_HOSTS_COL_ADDRESS os::LString( 218 )
#define MSG_MAINWIN_HOSTS_COL_ALIASES os::LString( 219 )
#define MSG_MAINWIN_HOSTS_ADD os::LString( 220 )
#define MSG_MAINWIN_HOSTS_DELETE os::LString( 221 )
#define MSG_MAINWIN_HOSTS_TITLE os::LString( 222 )
#define MSG_MAINWIN_APPLY os::LString( 223 )
#define MSG_MAINWIN_REVERT os::LString( 224 )
#define MSG_MAINWIN_CLOSE os::LString( 225 )
#define MSG_MAINWIN_NEW_NAMESERVER os::LString( 226 )
#define MSG_MAINWIN_NEW_SEARCH_DOMAIN os::LString( 227 )
#define MSG_MAINWIN_NEW_HOST_ADDRESS os::LString( 228 )
#define MSG_MAINWIN_NEW_HOST_ALIASES os::LString( 229 )
#define MSG_MAINWIN_IFACE_ENABLED_YES os::LString( 230 )
#define MSG_MAINWIN_IFACE_ENABLED_NO os::LString( 231 )
#define MSG_IFWIN_TITLE os::LString( 300 )
#define MSG_IFWIN_TYPE os::LString( 301 )
#define MSG_IFWIN_TYPE_STATIC os::LString( 302 )
#define MSG_IFWIN_TYPE_DHCP os::LString( 303 )
#define MSG_IFWIN_ADDRESS os::LString( 304 )
#define MSG_IFWIN_NETMASK os::LString( 305 )
#define MSG_IFWIN_GATEWAY os::LString( 306 )
#define MSG_IFWIN_ENABLED os::LString( 307 )
#define MSG_IFWIN_APPLY os::LString( 308 )
#define MSG_IFWIN_CLOSE os::LString( 309 )
#define MSG_IFWIN_ERR_IP_ADDRESS os::LString( 310 )
#define MSG_IFWIN_ERR_NETMASK os::LString( 311 )
#define MSG_IFWIN_ERR_GATEWAY os::LString( 312 )
#define MSG_IFWIN_ERR_TITLE os::LString( 313 )
#define MSG_IFWIN_ERR_CLOSE os::LString( 314 )

#endif

#endif
