//
// This header file was generated by Catalog Editor.
// Do not edit by hand.
//

#ifndef __F_CAT__home_root_SettingsEditor_resources_SettingsEditor_H__
#define __F_CAT__home_root_SettingsEditor_resources_SettingsEditor_H__
#include <util/catalog.h>
#ifndef CATALOG_NO_IDS
#define ID_ID_SETTINGS_EDITOR_WINDOW                         1000
#define ID_ID_LISTVIEW_NAME                                  1010
#define ID_ID_LISTVIEW_TYPE                                  1011
#define ID_ID_LISTVIEW_VALUE                                 1012
#define ID_ID_LISTVIEW_INDEX                                 1013
#define ID_ID_MENU_FILE                                      1020
#define ID_ID_MENU_FILE_NEW                                  1021
#define ID_ID_MENU_FILE_OPEN                                 1022
#define ID_ID_MENU_FILE_SAVE                                 1023
#define ID_ID_MENU_FILE_SAVE_AS                              1024
#define ID_ID_MENU_FILE_EXIT                                 1025
#define ID_ID_MENU_EDIT_ADD                                  1030
#define ID_ID_MENU_EDIT_ADD_STRING                           1031
#define ID_ID_MENU_EDIT_ADD_INT8                             1032
#define ID_ID_MENU_EDIT_ADD_INT16                            1033
#define ID_ID_MENU_EDIT_ADD_INT32                            1034
#define ID_ID_MENU_EDIT_ADD_INT64                            1035
#define ID_ID_MENU_EDIT_ADD_FLOAT                            1036
#define ID_ID_MENU_EDIT_ADD_DOUBLE                           1037
#define ID_ID_MENU_EDIT_ADD_IRECT                            1038
#define ID_ID_MENU_EDIT_ADD_IPOINT                           1039
#define ID_ID_MENU_EDIT_ADD_RECT                             1040
#define ID_ID_MENU_EDIT_ADD_POINT                            1041
#define ID_ID_MENU_EDIT_ADD_COLOR32                          1042
#define ID_ID_MENU_EDIT_ADD_RAW                              1043
#define ID_ID_MENU_EDIT_ADD_VARIANT                          1044
#define ID_ID_MENU_EDIT_ADD_MESSAGE                          1045
#define ID_ID_MENU_EDIT                                      1046
#define ID_ID_MENU_EDIT_DELETE                               1047
#define ID_ID_ADD_DIALOG_SENTENCE                            1050
#define ID_ID_ADD_DIALOG_WINDOW_TITLE                        1051
#define ID_ID_BUTTON_SAVE                                    1060
#define ID_ID_BUTTON_CLOSE                                   1061
#define ID_ID_BUTTON_PLUS                                    1062
#define ID_ID_BUTTON_MINUS                                   1063
#define ID_ID_ERROR_UNIQUE                                   1070
#define ID_ID_ERROR_VARIABLE                                 1071
#define ID_ID_ERROR_BUTTON                                   1072
#define ID_ID_ERROR_TITLE                                    1073
#endif // CATALOG_NO_IDS
#ifndef CATALOG_NO_LSTRINGS
#define ID_SETTINGS_EDITOR_WINDOW                         os::LString( 1000 )
#define ID_LISTVIEW_NAME                                  os::LString( 1010 )
#define ID_LISTVIEW_TYPE                                  os::LString( 1011 )
#define ID_LISTVIEW_VALUE                                 os::LString( 1012 )
#define ID_LISTVIEW_INDEX                                 os::LString( 1013 )
#define ID_MENU_FILE                                      os::LString( 1020 )
#define ID_MENU_FILE_NEW                                  os::LString( 1021 )
#define ID_MENU_FILE_OPEN                                 os::LString( 1022 )
#define ID_MENU_FILE_SAVE                                 os::LString( 1023 )
#define ID_MENU_FILE_SAVE_AS                              os::LString( 1024 )
#define ID_MENU_FILE_EXIT                                 os::LString( 1025 )
#define ID_MENU_EDIT_ADD                                  os::LString( 1030 )
#define ID_MENU_EDIT_ADD_STRING                           os::LString( 1031 )
#define ID_MENU_EDIT_ADD_INT8                             os::LString( 1032 )
#define ID_MENU_EDIT_ADD_INT16                            os::LString( 1033 )
#define ID_MENU_EDIT_ADD_INT32                            os::LString( 1034 )
#define ID_MENU_EDIT_ADD_INT64                            os::LString( 1035 )
#define ID_MENU_EDIT_ADD_FLOAT                            os::LString( 1036 )
#define ID_MENU_EDIT_ADD_DOUBLE                           os::LString( 1037 )
#define ID_MENU_EDIT_ADD_IRECT                            os::LString( 1038 )
#define ID_MENU_EDIT_ADD_IPOINT                           os::LString( 1039 )
#define ID_MENU_EDIT_ADD_RECT                             os::LString( 1040 )
#define ID_MENU_EDIT_ADD_POINT                            os::LString( 1041 )
#define ID_MENU_EDIT_ADD_COLOR32                          os::LString( 1042 )
#define ID_MENU_EDIT_ADD_RAW                              os::LString( 1043 )
#define ID_MENU_EDIT_ADD_VARIANT                          os::LString( 1044 )
#define ID_MENU_EDIT_ADD_MESSAGE                          os::LString( 1045 )
#define ID_MENU_EDIT                                      os::LString( 1046 )
#define ID_MENU_EDIT_DELETE                               os::LString( 1047 )
#define ID_ADD_DIALOG_SENTENCE                            os::LString( 1050 )
#define ID_ADD_DIALOG_WINDOW_TITLE                        os::LString( 1051 )
#define ID_BUTTON_SAVE                                    os::LString( 1060 )
#define ID_BUTTON_CLOSE                                   os::LString( 1061 )
#define ID_BUTTON_PLUS                                    os::LString( 1062 )
#define ID_BUTTON_MINUS                                   os::LString( 1063 )
#define ID_ERROR_UNIQUE                                   os::LString( 1070 )
#define ID_ERROR_VARIABLE                                 os::LString( 1071 )
#define ID_ERROR_BUTTON                                   os::LString( 1072 )
#define ID_ERROR_TITLE                                    os::LString( 1073 )
#endif // CATALOG_NO_LSTRINGS
#endif // End of file
