#ifndef __F_CAT_LogMonitor_H__
#define __F_CAT_LogMonitor_H__
#include <util/catalog.h>
#ifndef CATALOG_NO_IDS
#define ID_STR_OPTION_DESKTOP 1000
#define ID_STR_OPTION_FULLSCREEN 1001
#define ID_STR_OPTION_HELP 1002
#define ID_STR_OPTION_VERSION 1003
#define ID_STR_OPTION_LEFT 1004
#define ID_STR_OPTION_TOP 1005
#define ID_STR_OPTION_WIDTH 1006
#define ID_STR_OPTION_HEIGHT 1007
#define ID_STR_USAGE 1100
#define ID_STR_EXAMPLE 1101
#define ID_STR_ERROR_DESKTOP_NUMBER 2000
#define ID_STR_ERROR_WINDOW_HEIGHT 2001
#define ID_STR_ERROR_WINDOW_WIDTH 2002
#define ID_STR_ERROR_FILE_SIZE 2003
#define ID_STR_ERROR_SAVEFILE_TEXT 2004
#define ID_STR_ERROR_SAVEFILE_TITLE 2005
#define ID_STR_ERROR_SAVEFILE_OKBUTTON 2006
#define ID_STR_ABOUT 3000
#define ID_STR_ABOUT_WINTITLE 3001
#define ID_STR_ABOUT_OKBUTTON 3002
#define ID_STR_POPUPMENU_COPY 4000
#define ID_STR_POPUPMENU_CLEAR 4001
#define ID_STR_POPUPMENU_SAVE 4002
#define ID_STR_POPUPMENU_ABOUT 4003
#define ID_STR_POPUPMENU_QUIT 4004
#define ID_STR_POPUPMENU_OPEN 4005
#define ID_STR_POPUPMENU_COPY_SH 4100
#define ID_STR_POPUPMENU_CLEAR_SH 4101
#define ID_STR_POPUPMENU_SAVE_SH 4102
#define ID_STR_POPUPMENU_ABOUT_SH 4103
#define ID_STR_POPUPMENU_QUIT_SH 4104
#define ID_STR_POPUPMENU_OPEN_SH 4105
#endif
#ifndef CATALOG_NO_LSTRINGS
#define STR_OPTION_DESKTOP os::LString( 1000 )
#define STR_OPTION_FULLSCREEN os::LString( 1001 )
#define STR_OPTION_HELP os::LString( 1002 )
#define STR_OPTION_VERSION os::LString( 1003 )
#define STR_OPTION_LEFT os::LString( 1004 )
#define STR_OPTION_TOP os::LString( 1005 )
#define STR_OPTION_WIDTH os::LString( 1006 )
#define STR_OPTION_HEIGHT os::LString( 1007 )
#define STR_USAGE os::LString( 1100 )
#define STR_EXAMPLE os::LString( 1101 )
#define STR_ERROR_DESKTOP_NUMBER os::LString( 2000 )
#define STR_ERROR_WINDOW_HEIGHT os::LString( 2001 )
#define STR_ERROR_WINDOW_WIDTH os::LString( 2002 )
#define STR_ERROR_FILE_SIZE os::LString( 2003 )
#define STR_ERROR_SAVEFILE_TEXT os::LString( 2004 )
#define STR_ERROR_SAVEFILE_TITLE os::LString( 2005 )
#define STR_ERROR_SAVEFILE_OKBUTTON os::LString( 2006 )
#define STR_ABOUT os::LString( 3000 )
#define STR_ABOUT_WINTITLE os::LString( 3001 )
#define STR_ABOUT_OKBUTTON os::LString( 3002 )
#define STR_POPUPMENU_COPY os::LString( 4000 )
#define STR_POPUPMENU_CLEAR os::LString( 4001 )
#define STR_POPUPMENU_SAVE os::LString( 4002 )
#define STR_POPUPMENU_ABOUT os::LString( 4003 )
#define STR_POPUPMENU_QUIT os::LString( 4004 )
#define STR_POPUPMENU_OPEN os::LString( 4005 )
#define STR_POPUPMENU_COPY_SH os::LString( 4100 )
#define STR_POPUPMENU_CLEAR_SH os::LString( 4101 )
#define STR_POPUPMENU_SAVE_SH os::LString( 4102 )
#define STR_POPUPMENU_ABOUT_SH os::LString( 4103 )
#define STR_POPUPMENU_QUIT_SH os::LString( 4104 )
#define STR_POPUPMENU_OPEN_SH os::LString( 4105 )
#endif
#endif /* __F_CAT_LogMonitor_H__ */
