#ifndef __F_CAT_aedit_H__
#define __F_CAT_aedit_H__
#include <util/catalog.h>
#ifndef CATALOG_NO_IDS
#define ID_MSG_APPWND_TITLE 0
#define ID_MSG_APPWND_TITLE_NEW_FILE 1
#define ID_MSG_MENU_APPLICATION 100
#define ID_MSG_MENU_APPLICATION_QUIT 101
#define ID_MSG_MENU_APPLICATION_ABOUT 102
#define ID_MSG_MENU_FILE 200
#define ID_MSG_MENU_FILE_NEW 201
#define ID_MSG_MENU_FILE_OPEN 202
#define ID_MSG_MENU_FILE_SAVE 203
#define ID_MSG_MENU_FILE_SAVE_AS 204
#define ID_MSG_MENU_EDIT 300
#define ID_MSG_MENU_EDIT_CUT 301
#define ID_MSG_MENU_EDIT_COPY 302
#define ID_MSG_MENU_EDIT_PASTE 303
#define ID_MSG_MENU_EDIT_SELECT_ALL 304
#define ID_MSG_MENU_EDIT_UNDO 305
#define ID_MSG_MENU_EDIT_REDO 306
#define ID_MSG_MENU_FIND 400
#define ID_MSG_MENU_FIND_FIND 401
#define ID_MSG_MENU_FIND_REPLACE 402
#define ID_MSG_MENU_FIND_GOTO_LINE 403
#define ID_MSG_MENU_FONT 500
#define ID_MSG_MENU_FONT_SIZE 501
#define ID_MSG_MENU_SETTINGS 600
#define ID_MSG_MENU_SETTINGS_SAVE_ON_CLOSE 601
#define ID_MSG_MENU_SETTINGS_SAVE_NOW 602
#define ID_MSG_MENU_SETTINGS_RESET 603
#define ID_MSG_MENU_HELP 700
#define ID_MSG_MENU_HELP_TABLE_OF_CONTENTS 701
#define ID_MSG_MENU_HELP_HOMEPAGE 702
#define ID_MSG_ABOUT_TITLE 800
#define ID_MSG_ABOUT_TEXT 801
#define ID_MSG_ABOUT_CLOSE 802
#define ID_MSG_ERROR_TITLE 900
#define ID_MSG_ERROR_CANT_SAVE 901
#define ID_MSG_ERROR_CLOSE 902
#define ID_MSG_FIND_TITLE 1000
#define ID_MSG_FIND_FIND_LABEL 1001
#define ID_MSG_FIND_CASE_SENSITIVE 1002
#define ID_MSG_FIND_FIND 1003
#define ID_MSG_FIND_FIND_NEXT 1004
#define ID_MSG_FIND_CLOSE 1005
#define ID_MSG_GOTO_TITLE 1100
#define ID_MSG_GOTO_GOTO 1101
#define ID_MSG_GOTO_CLOSE 1102
#define ID_MSG_REPLACE_TITLE 1200
#define ID_MSG_REPLACE_LBLFIND 1201
#define ID_MSG_REPLACE_WITH 1202
#define ID_MSG_REPLACE_CASE_SENSITIVE 1203
#define ID_MSG_REPLACE_FIND 1204
#define ID_MSG_REPLACE_FIND_NEXT 1205
#define ID_MSG_REPLACE_REPLACE 1206
#define ID_MSG_REPLACE_CLOSE 1207
#endif
#ifndef CATALOG_NO_LSTRINGS
#define MSG_APPWND_TITLE os::LString( 0 )
#define MSG_APPWND_TITLE_NEW_FILE os::LString( 1 )
#define MSG_MENU_APPLICATION os::LString( 100 )
#define MSG_MENU_APPLICATION_QUIT os::LString( 101 )
#define MSG_MENU_APPLICATION_ABOUT os::LString( 102 )
#define MSG_MENU_FILE os::LString( 200 )
#define MSG_MENU_FILE_NEW os::LString( 201 )
#define MSG_MENU_FILE_OPEN os::LString( 202 )
#define MSG_MENU_FILE_SAVE os::LString( 203 )
#define MSG_MENU_FILE_SAVE_AS os::LString( 204 )
#define MSG_MENU_EDIT os::LString( 300 )
#define MSG_MENU_EDIT_CUT os::LString( 301 )
#define MSG_MENU_EDIT_COPY os::LString( 302 )
#define MSG_MENU_EDIT_PASTE os::LString( 303 )
#define MSG_MENU_EDIT_SELECT_ALL os::LString( 304 )
#define MSG_MENU_EDIT_UNDO os::LString( 305 )
#define MSG_MENU_EDIT_REDO os::LString( 306 )
#define MSG_MENU_FIND os::LString( 400 )
#define MSG_MENU_FIND_FIND os::LString( 401 )
#define MSG_MENU_FIND_REPLACE os::LString( 402 )
#define MSG_MENU_FIND_GOTO_LINE os::LString( 403 )
#define MSG_MENU_FONT os::LString( 500 )
#define MSG_MENU_FONT_SIZE os::LString( 501 )
#define MSG_MENU_SETTINGS os::LString( 600 )
#define MSG_MENU_SETTINGS_SAVE_ON_CLOSE os::LString( 601 )
#define MSG_MENU_SETTINGS_SAVE_NOW os::LString( 602 )
#define MSG_MENU_SETTINGS_RESET os::LString( 603 )
#define MSG_MENU_HELP os::LString( 700 )
#define MSG_MENU_HELP_TABLE_OF_CONTENTS os::LString( 701 )
#define MSG_MENU_HELP_HOMEPAGE os::LString( 702 )
#define MSG_ABOUT_TITLE os::LString( 800 )
#define MSG_ABOUT_TEXT os::LString( 801 )
#define MSG_ABOUT_CLOSE os::LString( 802 )
#define MSG_ERROR_TITLE os::LString( 900 )
#define MSG_ERROR_CANT_SAVE os::LString( 901 )
#define MSG_ERROR_CLOSE os::LString( 902 )
#define MSG_FIND_TITLE os::LString( 1000 )
#define MSG_FIND_FIND_LABEL os::LString( 1001 )
#define MSG_FIND_CASE_SENSITIVE os::LString( 1002 )
#define MSG_FIND_FIND os::LString( 1003 )
#define MSG_FIND_FIND_NEXT os::LString( 1004 )
#define MSG_FIND_CLOSE os::LString( 1005 )
#define MSG_GOTO_TITLE os::LString( 1100 )
#define MSG_GOTO_GOTO os::LString( 1101 )
#define MSG_GOTO_CLOSE os::LString( 1102 )
#define MSG_REPLACE_TITLE os::LString( 1200 )
#define MSG_REPLACE_LBLFIND os::LString( 1201 )
#define MSG_REPLACE_WITH os::LString( 1202 )
#define MSG_REPLACE_CASE_SENSITIVE os::LString( 1203 )
#define MSG_REPLACE_FIND os::LString( 1204 )
#define MSG_REPLACE_FIND_NEXT os::LString( 1205 )
#define MSG_REPLACE_REPLACE os::LString( 1206 )
#define MSG_REPLACE_CLOSE os::LString( 1207 )
#endif
#endif /* __F_CAT_aedit_H__ */
