/* Automatically generated by po2tbl.sed from fileutils.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"invalid argument %s for `%s'", 2},
  {"ambiguous argument %s for `%s'", 3},
  {"Valid arguments are:", 4},
  {"write error", 5},
  {"Unknown system error", 6},
  {"%s: option `%s' is ambiguous\n", 7},
  {"%s: option `--%s' doesn't allow an argument\n", 8},
  {"%s: option `%c%s' doesn't allow an argument\n", 9},
  {"%s: option `%s' requires an argument\n", 10},
  {"%s: unrecognized option `--%s'\n", 11},
  {"%s: unrecognized option `%c%s'\n", 12},
  {"%s: illegal option -- %c\n", 13},
  {"%s: invalid option -- %c\n", 14},
  {"%s: option requires an argument -- %c\n", 15},
  {"%s: option `-W %s' is ambiguous\n", 16},
  {"%s: option `-W %s' doesn't allow an argument\n", 17},
  {"block size", 18},
  {"cannot create directory %s", 19},
  {"%s exists but is not a directory", 20},
  {"cannot change owner and/or group of %s", 21},
  {"cannot chdir to directory, %s", 22},
  {"cannot change permissions of %s", 23},
  {"memory exhausted", 24},
  {"`", 25},
  {"'", 26},
  {"^[yY]", 27},
  {"^[nN]", 28},
  {"cannot output U+%04X: iconv function not usable", 29},
  {"U+%04X: character out of range", 30},
  {"cannot convert U+%04X to local character set", 31},
  {"cannot output U+%04X: iconv function not available", 32},
  {"invalid user", 33},
  {"invalid group", 34},
  {"cannot get the login group of a numeric UID", 35},
  {"cannot omit both user and group", 36},
  {"Copyright (C) 2001 Free Software Foundation, Inc.", 37},
  {"Written by %s.\n", 38},
  {"\
This is free software; see the source for copying conditions.  There is NO\n\
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n", 39},
  {"cannot change to null group", 40},
  {"invalid group name %s", 41},
  {"group number", 42},
  {"invalid group number %s", 43},
  {"Try `%s --help' for more information.\n", 44},
  {"\
Usage: %s [OPTION]... GROUP FILE...\n\
  or:  %s [OPTION]... --reference=RFILE FILE...\n", 45},
  {"\
Change the group membership of each FILE to GROUP.\n\
\n\
  -c, --changes          like verbose but report only when a change is made\n\
      --dereference      affect the referent of each symbolic link, rather\n\
                         than the symbolic link itself\n\
  -h, --no-dereference   affect symbolic links instead of any referenced \
file\n\
                         (available only on systems that can change the\n\
                         ownership of a symlink)\n\
  -f, --silent, --quiet  suppress most error messages\n\
      --reference=RFILE  use RFILE's group rather than the specified\n\
                         GROUP value\n\
  -R, --recursive        operate on files and directories recursively\n\
  -v, --verbose          output a diagnostic for every file processed\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n", 46},
  {"\
\n\
Report bugs to <bug-fileutils@gnu.org>.", 47},
  {"too few arguments", 48},
  {"getting attributes of %s", 49},
  {"getting new attributes of %s", 50},
  {"mode of %s changed to %04lo (%s)\n", 51},
  {"failed to change mode of %s to %04lo (%s)\n", 52},
  {"mode of %s retained as %04lo (%s)\n", 53},
  {"changing permissions of %s", 54},
  {"\
Usage: %s [OPTION]... MODE[,MODE]... FILE...\n\
  or:  %s [OPTION]... OCTAL-MODE FILE...\n\
  or:  %s [OPTION]... --reference=RFILE FILE...\n", 55},
  {"\
Change the mode of each FILE to MODE.\n\
\n\
  -c, --changes           like verbose but report only when a change is \
made\n\
  -f, --silent, --quiet   suppress most error messages\n\
  -v, --verbose           output a diagnostic for every file processed\n\
      --reference=RFILE   use RFILE's mode instead of MODE values\n\
  -R, --recursive         change files and directories recursively\n\
      --help              display this help and exit\n\
      --version           output version information and exit\n\
\n\
Each MODE is one or more of the letters ugoa, one of the symbols +-= and\n\
one or more of the letters rwxXstugo.\n", 56},
  {"invalid character %s in mode string %s", 57},
  {"invalid mode string: %s", 58},
  {"neither symbolic link %s nor referent has been changed\n", 59},
  {"changed ownership of %s to %s\n", 60},
  {"changed group of %s to %s\n", 61},
  {"failed to change ownership of %s to %s\n", 62},
  {"failed to change group of %s to %s\n", 63},
  {"ownership of %s retained as %s\n", 64},
  {"group of %s retained as %s\n", 65},
  {"changing ownership of %s", 66},
  {"changing group of %s", 67},
  {"unable to restore permissions of %s", 68},
  {"\
Usage: %s [OPTION]... OWNER[:[GROUP]] FILE...\n\
  or:  %s [OPTION]... :GROUP FILE...\n\
  or:  %s [OPTION]... --reference=RFILE FILE...\n", 69},
  {"\
Change the owner and/or group of each FILE to OWNER and/or GROUP.\n\
\n\
  -c, --changes          like verbose but report only when a change is made\n\
      --dereference      affect the referent of each symbolic link, rather\n\
                         than the symbolic link itself\n\
  -h, --no-dereference   affect symbolic links instead of any referenced \
file\n\
                         (available only on systems that can change the\n\
                         ownership of a symlink)\n\
      --from=CURRENT_OWNER:CURRENT_GROUP\n\
                         change the owner and/or group of each file only if\n\
                         its current owner and/or group match those \
specified\n\
                         here.  Either may be omitted, in which case a \
match\n\
                         is not required for the omitted attribute.\n\
  -f, --silent, --quiet  suppress most error messages\n\
      --reference=RFILE  use RFILE's owner and group rather than\n\
                         the specified OWNER:GROUP values\n\
  -R, --recursive        operate on files and directories recursively\n\
  -v, --verbose          output a diagnostic for every file processed\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n\
\n", 70},
  {"\
Owner is unchanged if missing.  Group is unchanged if missing, but changed\n\
to login group if implied by a `:'.  OWNER and GROUP may be numeric as well\n\
as symbolic.\n", 71},
  {"cannot access %s", 72},
  {"%s and %s are the same file", 73},
  {"cannot open %s for reading", 74},
  {"cannot remove %s", 75},
  {"cannot create regular file %s", 76},
  {"cannot fstat %s", 77},
  {"reading %s", 78},
  {"cannot lseek %s", 79},
  {"writing %s", 80},
  {"closing %s", 81},
  {"cannot stat %s", 82},
  {"omitting directory %s", 83},
  {"cannot overwrite non-directory %s with directory %s", 84},
  {"cannot overwrite directory %s with non-directory", 85},
  {"%s: overwrite %s, overriding mode %04lo? ", 86},
  {"%s: overwrite %s? ", 87},
  {"cannot overwrite directory %s", 88},
  {"cannot move directory onto non-directory: %s -> %s", 89},
  {"backing up %s would destroy source;  %s not moved", 90},
  {"backing up %s would destroy source;  %s not copied", 91},
  {"cannot backup %s", 92},
  {" (backup: %s)", 93},
  {"cannot copy a directory, %s, into itself, %s", 94},
  {"will not create hard link %s to directory %s", 95},
  {"cannot create hard link %s to %s", 96},
  {"cannot move %s to a subdirectory of itself, %s", 97},
  {"cannot move %s to %s", 98},
  {"cannot copy cyclic symbolic link %s", 99},
  {"%s: can make relative symbolic links only in current directory", 100},
  {"cannot create symbolic link %s to %s", 101},
  {"cannot create link %s", 102},
  {"cannot create fifo %s", 103},
  {"cannot create special file %s", 104},
  {"cannot read symbolic link %s", 105},
  {"cannot create symbolic link %s", 106},
  {"preserving ownership for %s", 107},
  {"%s has unknown file type", 108},
  {"preserving times for %s", 109},
  {"setting permissions for %s", 110},
  {"cannot un-backup %s", 111},
  {"%s -> %s (unbackup)\n", 112},
  {"\
Usage: %s [OPTION]... SOURCE DEST\n\
  or:  %s [OPTION]... SOURCE... DIRECTORY\n\
  or:  %s [OPTION]... --target-directory=DIRECTORY SOURCE...\n", 113},
  {"\
Copy SOURCE to DEST, or multiple SOURCE(s) to DIRECTORY.\n\
\n\
  -a, --archive                same as -dpR\n\
      --backup[=CONTROL]       make a backup of each existing destination \
file\n\
  -b                           like --backup but does not accept an \
argument\n\
  -d, --no-dereference         never follow symbolic links\n\
  -f, --force                  if an existing destination file cannot be\n\
                                   opened, remove it and try again\n\
  -i, --interactive            prompt before overwrite\n\
  -H                           follow command-line symbolic links\n\
  -l, --link                   link files instead of copying\n\
  -L, --dereference            always follow symbolic links\n\
  -p, --preserve               preserve file attributes if possible\n\
      --parents                append source path to DIRECTORY\n\
  -P                           same as `--parents' for now; soon to change \
to\n\
                                 `--no-dereference' to conform to POSIX\n\
  -r                           copy recursively, non-directories as files\n\
                                 WARNING: use -R instead when you might \
copy\n\
                                 special files like FIFOs or /dev/zero\n\
      --remove-destination     remove each existing destination file before\n\
                                 attempting to open it (contrast with --\
force)\n", 114},
  {"\
      --sparse=WHEN            control creation of sparse files\n\
  -R, --recursive              copy directories recursively\n\
      --strip-trailing-slashes remove any trailing slashes from each SOURCE\n\
                                 argument\n\
  -s, --symbolic-link          make symbolic links instead of copying\n\
  -S, --suffix=SUFFIX          override the usual backup suffix\n\
      --target-directory=DIRECTORY  move all SOURCE arguments into \
DIRECTORY\n\
  -u, --update                 copy only when the SOURCE file is newer\n\
                                 than the destination file or when the\n\
                                 destination file is missing\n\
  -v, --verbose                explain what is being done\n\
  -x, --one-file-system        stay on this file system\n\
      --help                   display this help and exit\n\
      --version                output version information and exit\n\
\n\
By default, sparse SOURCE files are detected by a crude heuristic and the\n\
corresponding DEST file is made sparse as well.  That is the behavior\n\
selected by --sparse=auto.  Specify --sparse=always to create a sparse DEST\n\
file whenever the SOURCE file contains a long enough sequence of zero \
bytes.\n\
Use --sparse=never to inhibit creation of sparse files.\n\
\n", 115},
  {"\
The backup suffix is `~', unless set with --suffix or SIMPLE_BACKUP_SUFFIX.\n\
The version control method may be selected via the --backup option or \
through\n\
the VERSION_CONTROL environment variable.  Here are the values:\n\
\n\
  none, off       never make backups (even if --backup is given)\n\
  numbered, t     make numbered backups\n\
  existing, nil   numbered if numbered backups exist, simple otherwise\n\
  simple, never   always make simple backups\n", 116},
  {"\
\n\
As a special case, cp makes a backup of SOURCE when the force and backup\n\
options are given and SOURCE and DEST are the same name for an existing,\n\
regular file.\n", 117},
  {"preserving permissions for %s", 118},
  {"cannot make directory %s", 119},
  {"missing file arguments", 120},
  {"missing destination file", 121},
  {"accessing %s", 122},
  {"specified target, %s is not a directory", 123},
  {"copying multiple files, but last argument %s is not a directory", 124},
  {"when preserving paths, the destination must be a directory", 125},
  {"\
warning: --version-control (-V) is obsolete;  support for it\n\
will be removed in some future release.  Use --backup=%s instead.", 126},
  {"symbolic links are not supported on this system", 127},
  {"cannot make both hard and symbolic links", 128},
  {"\
Warning: the meaning of `-P' will change in the future to conform to POSIX.\n\
Use `--parents' for the old meaning, and `--no-dereference' for the new one.", 129},
  {"backup type", 130},
  {"Usage: %s [OPTION]... [FILE]\n", 131},
  {"\
Output commands to set the LS_COLORS environment variable.\n\
\n\
Determine format of output:\n\
  -b, --sh, --bourne-shell    output Bourne shell code to set LS_COLORS\n\
  -c, --csh, --c-shell        output C shell code to set LS_COLORS\n\
  -p, --print-database        output defaults\n\
      --help                  display this help and exit\n\
      --version               output version information and exit\n\
\n\
If FILE is specified, read it to determine which colors to use for which\n\
file types and extensions.  Otherwise, a precompiled database is used.\n\
For details on the format of these files, run `dircolors --print-database'.\n", 132},
  {"%s:%lu: invalid line;  missing second token", 133},
  {"%s:%lu: unrecognized keyword %s", 134},
  {"<internal>", 135},
  {"\
the options to output dircolors' internal database and\n\
to select a shell syntax are mutually exclusive", 136},
  {"\
no FILE arguments may be used with the option to output\n\
dircolors' internal database", 137},
  {"too many arguments", 138},
  {"no SHELL environment variable, and no shell type option given", 139},
  {"standard input", 140},
  {"Usage: %s [OPTION]...\n", 141},
  {"\
Copy a file, converting and formatting according to the options.\n\
\n\
  bs=BYTES        force ibs=BYTES and obs=BYTES\n\
  cbs=BYTES       convert BYTES bytes at a time\n\
  conv=KEYWORDS   convert the file as per the comma separated keyword list\n\
  count=BLOCKS    copy only BLOCKS input blocks\n\
  ibs=BYTES       read BYTES bytes at a time\n\
  if=FILE         read from FILE instead of stdin\n\
  obs=BYTES       write BYTES bytes at a time\n\
  of=FILE         write to FILE instead of stdout\n\
  seek=BLOCKS     skip BLOCKS obs-sized blocks at start of output\n\
  skip=BLOCKS     skip BLOCKS ibs-sized blocks at start of input\n\
      --help      display this help and exit\n\
      --version   output version information and exit\n\
\n\
BLOCKS and BYTES may be followed by the following multiplicative suffixes:\n\
xM M, c 1, w 2, b 512, kD 1000, k 1024, MD 1,000,000, M 1,048,576,\n\
GD 1,000,000,000, G 1,073,741,824, and so on for T, P, E, Z, Y.\n\
Each KEYWORD may be:\n\
\n\
  ascii     from EBCDIC to ASCII\n\
  ebcdic    from ASCII to EBCDIC\n\
  ibm       from ASCII to alternated EBCDIC\n\
  block     pad newline-terminated records with spaces to cbs-size\n\
  unblock   replace trailing spaces in cbs-size records with newline\n\
  lcase     change upper case to lower case\n\
  notrunc   do not truncate the output file\n\
  ucase     change lower case to upper case\n\
  swab      swap every pair of input bytes\n\
  noerror   continue after read errors\n\
  sync      pad every input block with NULs to ibs-size; when used\n\
              with block or unblock, pad with spaces rather than NULs\n", 142},
  {"%s+%s records in\n", 143},
  {"%s+%s records out\n", 144},
  {"truncated record", 145},
  {"truncated records", 146},
  {"closing input file %s", 147},
  {"closing output file %s", 148},
  {"writing to %s", 149},
  {"invalid conversion: %s", 150},
  {"unrecognized option %s", 151},
  {"unrecognized option %s=%s", 152},
  {"invalid number %s", 153},
  {"\
only one conv in {ascii,ebcdic,ibm}, {lcase,ucase}, {block,unblock}, \
{unblock,sync}", 154},
  {"opening %s", 155},
  {"file offset out of range", 156},
  {"advancing past %s bytes in output file %s", 157},
  {"standard output", 158},
  {"Filesystem ", 159},
  {"   Type", 160},
  {"    Inodes   IUsed   IFree IUse%%", 161},
  {"    Size  Used Avail Use%%", 162},
  {" %4d-blocks      Used Available Capacity", 163},
  {" %4s-blocks      Used Available Use%%", 164},
  {" Mounted on\n", 165},
  {"Usage: %s [OPTION]... [FILE]...\n", 166},
  {"\
Show information about the filesystem on which each FILE resides,\n\
or all filesystems by default.\n\
\n\
  -a, --all             include filesystems having 0 blocks\n\
      --block-size=SIZE use SIZE-byte blocks\n\
  -h, --human-readable  print sizes in human readable format (e.g., 1K 234M \
2G)\n\
  -H, --si              likewise, but use powers of 1000 not 1024\n\
  -i, --inodes          list inode information instead of block usage\n\
  -k, --kilobytes       like --block-size=1024\n\
  -l, --local           limit listing to local filesystems\n\
  -m, --megabytes       like --block-size=1048576\n\
      --no-sync         do not invoke sync before getting usage info \
(default)\n\
  -P, --portability     use the POSIX output format\n\
      --sync            invoke sync before getting usage info\n\
  -t, --type=TYPE       limit listing to filesystems of type TYPE\n\
  -T, --print-type      print filesystem type\n\
  -x, --exclude-type=TYPE   limit listing to filesystems not of type TYPE\n\
  -v                    (ignored)\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n", 167},
  {"file system type %s both selected and excluded", 168},
  {"Warning: ", 169},
  {"%scannot read table of mounted filesystems", 170},
  {"\
Summarize disk usage of each FILE, recursively for directories.\n\
\n\
  -a, --all             write counts for all files, not just directories\n\
      --block-size=SIZE use SIZE-byte blocks\n\
  -b, --bytes           print size in bytes\n\
  -c, --total           produce a grand total\n\
  -D, --dereference-args  dereference PATHs when symbolic link\n\
  -h, --human-readable  print sizes in human readable format (e.g., 1K 234M \
2G)\n\
  -H, --si              likewise, but use powers of 1000 not 1024\n\
  -k, --kilobytes       like --block-size=1024\n\
  -l, --count-links     count sizes many times if hard linked\n\
  -L, --dereference     dereference all symbolic links\n\
  -m, --megabytes       like --block-size=1048576\n\
  -S, --separate-dirs   do not include size of subdirectories\n\
  -s, --summarize       display only a total for each argument\n\
  -x, --one-file-system  skip directories on different filesystems\n\
  -X FILE, --exclude-from=FILE  Exclude files that match any pattern in \
FILE.\n\
      --exclude=PAT     Exclude files that match PAT.\n\
      --max-depth=N     print the total for a directory (or file, with --\
all)\n\
                          only if it is N or fewer levels below the command\n\
                          line argument;  --max-depth=0 is the same as\n\
                          --summarize\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n", 171},
  {"cannot change to `..' from directory %s", 172},
  {"cannot change to directory %s", 173},
  {"total", 174},
  {"invalid maximum depth %s", 175},
  {"cannot both summarize and show all entries", 176},
  {"warning: summarizing is the same as using --max-depth=0", 177},
  {"warning: summarizing conflicts with --max-depth=%d", 178},
  {"the strip option may not be used when installing a directory", 179},
  {"invalid mode %s", 180},
  {"creating directory %s", 181},
  {"installing multiple files, but last argument, %s is not a directory", 182},
  {"%s is a directory", 183},
  {"cannot obtain time stamps for %s", 184},
  {"cannot set time stamps for %s", 185},
  {"cannot fork", 186},
  {"cannot run strip", 187},
  {"strip failed", 188},
  {"invalid user %s", 189},
  {"invalid group %s", 190},
  {"\
Usage: %s [OPTION]... SOURCE DEST           (1st format)\n\
  or:  %s [OPTION]... SOURCE... DIRECTORY   (2nd format)\n\
  or:  %s -d [OPTION]... DIRECTORY...       (3rd format)\n", 191},
  {"\
In the first two formats, copy SOURCE to DEST or multiple SOURCE(s) to\n\
the existing DIRECTORY, while setting permission modes and owner/group.\n\
In the third format, create all components of the given DIRECTORY(ies).\n\
\n\
      --backup[=CONTROL] make a backup of each existing destination file\n\
  -b                  like --backup but does not accept an argument\n\
  -c                  (ignored)\n\
  -d, --directory     treat all arguments as directory names; create all\n\
                        components of the specified directories\n\
  -D                  create all leading components of DEST except the \
last,\n\
                        then copy SOURCE to DEST;  useful in the 1st format\n\
  -g, --group=GROUP   set group ownership, instead of process' current \
group\n\
  -m, --mode=MODE     set permission mode (as in chmod), instead of rwxr-xr-\
x\n\
  -o, --owner=OWNER   set ownership (super-user only)\n\
  -p, --preserve-timestamps   apply access/modification times of SOURCE \
files\n\
                        to corresponding destination files\n\
  -s, --strip         strip symbol tables, only for 1st and 2nd formats\n\
  -S, --suffix=SUFFIX override the usual backup suffix\n\
  -v, --verbose       print the name of each directory as it is created\n\
      --help          display this help and exit\n\
      --version       output version information and exit\n\
\n", 192},
  {"%s: warning: making a hard link to a symbolic link is not portable", 193},
  {"%s: hard link not allowed for directory", 194},
  {"%s: cannot overwrite directory", 195},
  {"%s: replace %s? ", 196},
  {"%s: File exists", 197},
  {"create symbolic link %s to %s", 198},
  {"create hard link %s to %s", 199},
  {"creating symbolic link %s to %s", 200},
  {"creating hard link %s to %s", 201},
  {"\
Usage: %s [OPTION]... TARGET [LINK_NAME]\n\
  or:  %s [OPTION]... TARGET... DIRECTORY\n\
  or:  %s [OPTION]... --target-directory=DIRECTORY TARGET...\n", 202},
  {"\
Create a link to the specified TARGET with optional LINK_NAME.\n\
If LINK_NAME is omitted, a link with the same basename as the TARGET is\n\
created in the current directory.  When using the second form with more\n\
than one TARGET, the last argument must be a directory;  create links\n\
in DIRECTORY to each TARGET.  Create hard links by default, symbolic\n\
links with --symbolic.  When creating hard links, each TARGET must exist.\n\
\n\
      --backup[=CONTROL]      make a backup of each existing destination \
file\n\
  -b                          like --backup but does not accept an argument\n\
  -d, -F, --directory         hard link directories (super-user only)\n\
  -f, --force                 remove existing destination files\n\
  -n, --no-dereference        treat destination that is a symlink to a\n\
                                directory as if it were a normal file\n\
  -i, --interactive           prompt whether to remove destinations\n\
  -s, --symbolic              make symbolic links instead of hard links\n\
  -S, --suffix=SUFFIX         override the usual backup suffix\n\
      --target-directory=DIRECTORY  specify the DIRECTORY in which to \
create\n\
                                the links\n\
  -v, --verbose               print name of each file before linking\n\
      --help                  display this help and exit\n\
      --version               output version information and exit\n\
\n", 203},
  {"missing file argument", 204},
  {"specified target directory, %s is not a directory", 205},
  {"when making multiple links, last argument must be a directory", 206},
  {"ignoring invalid width in environment variable COLUMNS: %s", 207},
  {"ignoring invalid tab size in environment variable TABSIZE: %s", 208},
  {"\
Warning: the meaning of `-H' will change in the future to conform to POSIX.\n\
Use `--si' for the old meaning.", 209},
  {"invalid line width: %s", 210},
  {"invalid tab size: %s", 211},
  {"%a %b %d %H:%M:%S %Y", 212},
  {"%b %e  %Y", 213},
  {"%b %e %H:%M", 214},
  {"unrecognized prefix: %s", 215},
  {"unparsable value for LS_COLORS environment variable", 216},
  {"\
List information about the FILEs (the current directory by default).\n\
Sort entries alphabetically if none of -cftuSUX nor --sort.\n\
\n\
  -a, --all                  do not hide entries starting with .\n\
  -A, --almost-all           do not list implied . and ..\n\
  -b, --escape               print octal escapes for nongraphic characters\n\
      --block-size=SIZE      use SIZE-byte blocks\n\
  -B, --ignore-backups       do not list implied entries ending with ~\n\
  -c                         with -lt: sort by, and show, ctime (time of \
last\n\
                               modification of file status information)\n\
                               with -l: show ctime and sort by name\n\
                               otherwise: sort by ctime\n\
  -C                         list entries by columns\n\
      --color[=WHEN]         control whether color is used to distinguish \
file\n\
                               types.  WHEN may be `never', `always', or \
`auto'\n\
  -d, --directory            list directory entries instead of contents\n\
  -D, --dired                generate output designed for Emacs' dired mode\n\
  -f                         do not sort, enable -aU, disable -lst\n\
  -F, --classify             append indicator (one of */=@|) to entries\n\
      --format=WORD          across -x, commas -m, horizontal -x, long -l,\n\
                               single-column -1, verbose -l, vertical -C\n\
      --full-time            list both full date and full time\n", 217},
  {"\
  -g                         (ignored)\n\
  -G, --no-group             inhibit display of group information\n\
  -h, --human-readable  print sizes in human readable format (e.g., 1K 234M \
2G)\n\
      --si                   likewise, but use powers of 1000 not 1024\n\
  -H                         same as `--si' for now; soon to change\n\
                               to conform to POSIX\n\
      --indicator-style=WORD append indicator with style WORD to entry \
names:\n\
                               none (default), classify (-F), file-type (-\
p)\n\
  -i, --inode                print index number of each file\n\
  -I, --ignore=PATTERN       do not list implied entries matching shell \
PATTERN\n\
  -k, --kilobytes            like --block-size=1024\n\
  -l                         use a long listing format\n\
  -L, --dereference          list entries pointed to by symbolic links\n\
  -m                         fill width with a comma separated list of \
entries\n\
  -n, --numeric-uid-gid      list numeric UIDs and GIDs instead of names\n\
  -N, --literal              print raw entry names (don't treat e.g. \
control\n\
                               characters specially)\n\
  -o                         use long listing format without group info\n\
  -p, --file-type            append indicator (one of /=@|) to entries\n\
  -q, --hide-control-chars   print ? instead of non graphic characters\n\
      --show-control-chars   show non graphic characters as-is (default\n\
                             unless program is `ls' and output is a \
terminal)\n\
  -Q, --quote-name           enclose entry names in double quotes\n\
      --quoting-style=WORD   use quoting style WORD for entry names:\n\
                               literal, locale, shell, shell-always, c, \
escape\n\
  -r, --reverse              reverse order while sorting\n\
  -R, --recursive            list subdirectories recursively\n\
  -s, --size                 print size of each file, in blocks\n", 218},
  {"\
  -S                         sort by file size\n\
      --sort=WORD            extension -X, none -U, size -S, time -t,\n\
                               version -v\n\
                             status -c, time -t, atime -u, access -u, use -\
u\n\
      --time=WORD            show time as WORD instead of modification \
time:\n\
                               atime, access, use, ctime or status; use\n\
                               specified time as sort key if --sort=time\n\
  -t                         sort by modification time\n\
  -T, --tabsize=COLS         assume tab stops at each COLS instead of 8\n\
  -u                         with -lt: sort by, and show, access time\n\
                               with -l: show access time and sort by name\n\
                               otherwise: sort by access time\n\
  -U                         do not sort; list entries in directory order\n\
  -v                         sort by version\n\
  -w, --width=COLS           assume screen width instead of current value\n\
  -x                         list entries by lines instead of by columns\n\
  -X                         sort alphabetically by entry extension\n\
  -1                         list one file per line\n\
      --help                 display this help and exit\n\
      --version              output version information and exit\n\
\n\
By default, color is not used to distinguish types of files.  That is\n\
equivalent to using --color=none.  Using the --color option without the\n\
optional WHEN argument is equivalent to using --color=always.  With\n\
--color=auto, color codes are output only if standard output is connected\n\
to a terminal (tty).\n", 219},
  {"Usage: %s [OPTION] DIRECTORY...\n", 220},
  {"\
Create the DIRECTORY(ies), if they do not already exist.\n\
\n\
  -m, --mode=MODE   set permission mode (as in chmod), not rwxrwxrwx - \
umask\n\
  -p, --parents     no error if existing, make parent directories as needed\n\
  -v, --verbose     print a message for each created directory\n\
      --help        display this help and exit\n\
      --version     output version information and exit\n", 221},
  {"created directory %s", 222},
  {"cannot set permissions of directory %s", 223},
  {"Usage: %s [OPTION] NAME...\n", 224},
  {"\
Create named pipes (FIFOs) with the given NAMEs.\n\
\n\
  -m, --mode=MODE   set permission mode (as in chmod), not a=rw - umask\n\
      --help        display this help and exit\n\
      --version     output version information and exit\n", 225},
  {"fifo files not supported", 226},
  {"invalid mode", 227},
  {"cannot create fifo `%s'", 228},
  {"cannot set permissions of fifo `%s'", 229},
  {"Usage: %s [OPTION]... NAME TYPE [MAJOR MINOR]\n", 230},
  {"\
Create the special file NAME of the given TYPE.\n\
\n\
  -m, --mode=MODE   set permission mode (as in chmod), not a=rw - umask\n\
      --help        display this help and exit\n\
      --version     output version information and exit\n\
\n\
MAJOR MINOR are forbidden for TYPE p, mandatory otherwise.  TYPE may be:\n\
\n\
  b      create a block (buffered) special file\n\
  c, u   create a character (unbuffered) special file\n\
  p      create a FIFO\n", 231},
  {"wrong number of arguments", 232},
  {"block special files not supported", 233},
  {"\
when creating block special files, major and minor device\n\
numbers must be specified", 234},
  {"invalid major device number %s", 235},
  {"invalid minor device number %s", 236},
  {"character special files not supported", 237},
  {"\
when creating character special files, major and minor device\n\
numbers must be specified", 238},
  {"major and minor device numbers may not be specified for fifo files", 239},
  {"cannot set permissions of `%s'", 240},
  {"\
Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY.\n\
\n\
      --backup[=CONTROL]       make a backup of each existing destination \
file\n\
  -b                           like --backup but does not accept an \
argument\n\
  -f, --force                  never prompt before overwriting\n\
  -i, --interactive            prompt before overwrite\n\
      --strip-trailing-slashes  remove any trailing slashes from each \
SOURCE\n\
                                 argument\n\
  -S, --suffix=SUFFIX          override the usual backup suffix\n\
      --target-directory=DIRECTORY  move all SOURCE arguments into \
DIRECTORY\n\
  -u, --update                 move only older or brand new non-directories\n\
  -v, --verbose                explain what is being done\n\
      --help                   display this help and exit\n\
      --version                output version information and exit\n\
\n", 241},
  {"when moving multiple files, last argument must be a directory", 242},
  {"cannot open directory %s", 243},
  {"closing directory %s", 244},
  {"%s: remove write-protected directory %s? ", 245},
  {"%s: remove write-protected file %s? ", 246},
  {"%s: remove directory %s? ", 247},
  {"%s: remove %s? ", 248},
  {"removing %s\n", 249},
  {"cannot unlink %s", 250},
  {"%s: directory %s is write protected; descend into it anyway? ", 251},
  {"%s: descend into directory %s? ", 252},
  {"removing all entries of directory %s\n", 253},
  {"cannot lstat `.' in %s", 254},
  {"\
ERROR: the directory %s initially had device/inode\n\
numbers %lu/%lu, but now (after a chdir into it), the numbers for `.'\n\
are %lu/%lu.  That means that while rm was running, the directory\n\
was replaced with either another directory or a link to another directory.", 255},
  {"cannot change back to directory %s via `..'", 256},
  {"%s: remove directory %s%s? ", 257},
  {" (might be nonempty)", 258},
  {"removing the directory itself: %s\n", 259},
  {"cannot remove current directory %s", 260},
  {"cannot remove directory %s", 261},
  {"cannot remove `.' or `..'", 262},
  {"\
WARNING: Circular directory structure.\n\
This almost certainly means that you have a corrupted file system.\n\
NOTIFY YOUR SYSTEM MANAGER.\n\
The following two directories have the same inode number:\n", 263},
  {"continue? ", 264},
  {"Usage: %s [OPTION]... FILE...\n", 265},
  {"\
Remove (unlink) the FILE(s).\n\
\n\
  -d, --directory       unlink directory, even if non-empty (super-user \
only)\n\
  -f, --force           ignore nonexistent files, never prompt\n\
  -i, --interactive     prompt before any removal\n\
  -r, -R, --recursive   remove the contents of directories recursively\n\
  -v, --verbose         explain what is being done\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n\
\n\
To remove a file whose name starts with a `-', for example `-foo',\n\
use one of these commands:\n\
  %s -- -foo\n\
\n\
  %s ./-foo\n\
\n\
Note that if you use rm to remove a file, it is usually possible to recover\n\
the contents of that file.  If you want more assurance that the contents \
are\n\
truly unrecoverable, consider using shred.\n", 266},
  {"removing directory, %s", 267},
  {"Usage: %s [OPTION]... DIRECTORY...\n", 268},
  {"\
Remove the DIRECTORY(ies), if they are empty.\n\
\n\
      --ignore-fail-on-non-empty\n\
                  ignore each failure that is solely because a directory\n\
                  is non-empty\n\
  -p, --parents   remove DIRECTORY, then try to remove each directory\n\
                  component of that path name.  E.g., `rmdir -p a/b/c' is\n\
                  similar to `rmdir a/b/c a/b a'.\n\
  -v, --verbose   output a diagnostic for every directory processed\n\
      --help      display this help and exit\n\
      --version   output version information and exit\n", 269},
  {"Usage: %s [OPTIONS] FILE [...]\n", 270},
  {"\
Overwrite the specified FILE(s) repeatedly, in order to make it harder\n\
for even very expensive hardware probing to recover the data.\n\
\n\
  -f, --force    change permissions to allow writing if necessary\n\
  -n, --iterations=N  Overwrite N times instead of the default (%d)\n\
  -s, --size=N   shred this many bytes (suffixes like k, M, G accepted)\n\
  -u, --remove   truncate and remove file after overwriting\n\
  -v, --verbose  show progress\n\
  -x, --exact    do not round file sizes up to the next full block\n\
  -z, --zero     add a final overwrite with zeros to hide shredding\n\
  -              shred standard output\n\
      --help     display this help and exit\n\
      --version  print version information and exit\n\
\n\
Delete FILE(s) if --remove (-u) is specified.  The default is not to remove\n\
the files because it is common to operate on device files like /dev/hda,\n\
and those files usually should not be removed.  When operating on regular\n\
files, most people use the --remove option.\n\
\n\
CAUTION: Note that shred relies on a very important assumption:\n\
that the filesystem overwrites data in place.  This is the traditional\n\
way to do things, but many modern filesystem designs do not satisfy this\n\
assumption.  The following are examples of filesystems on which shred is\n\
not effective:\n\
\n\
* log-structured or journaled filesystems, such as those supplied with\n\
  AIX and Solaris (and JFS, ReiserFS, XFS, etc.)\n\
\n\
* filesystems that write redundant data and carry on even if some writes\n\
  fail, such as RAID-based filesystems\n\
\n\
* filesystems that make snapshots, such as Network Appliance's NFS server\n\
\n\
* filesystems that cache in temporary locations, such as NFS\n\
  version 3 clients\n\
\n\
* compressed filesystems\n", 271},
  {"%s: cannot rewind", 272},
  {"%s: pass %lu/%lu (%s)...", 273},
  {"%s: error writing at offset %s", 274},
  {"%s: file too large", 275},
  {"%s: pass %lu/%lu (%s)...%s/%s", 276},
  {"%s: pass %lu/%lu (%s)...%s", 277},
  {"%s: invalid file type", 278},
  {"%s: file has negative size", 279},
  {"%s: error truncating", 280},
  {"%s: cannot shred append-only file descriptor", 281},
  {"%s: removing", 282},
  {"%s: renamed to %s", 283},
  {"%s: removed", 284},
  {"%s: cannot remove", 285},
  {"%s: invalid number of passes", 286},
  {"%s: invalid file size", 287},
  {"Usage: %s [OPTION]\n", 288},
  {"\
Force changed blocks to disk, update the super block.\n\
\n\
  --help      display this help and exit\n\
  --version   output version information and exit\n", 289},
  {"ignoring all arguments", 290},
  {"creating %s", 291},
  {"setting times of %s", 292},
  {"  or:  %s [-acm] MMDDhhmm[YY] FILE... (obsolescent)\n", 293},
  {"\
Update the access and modification times of each FILE to the current time.\n\
\n\
  -a                     change only the access time\n\
  -c, --no-create        do not create any files\n\
  -d, --date=STRING      parse STRING and use it instead of current time\n\
  -f                     (ignored)\n\
  -m                     change only the modification time\n\
  -r, --reference=FILE   use this file's times instead of current time\n\
  -t STAMP               use [[CC]YY]MMDDhhmm[.ss] instead of current time\n\
  --time=WORD            set time given by WORD: access atime use (same as -\
a)\n\
                           modify mtime (same as -m)\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n\
\n\
Note that the three time-date formats recognized for the -d and -t options\n\
and for the obsolescent argument are all different.\n", 294},
  {"invalid date format %s", 295},
  {"cannot specify times from more than one source", 296},
  {"file arguments missing", 297},
};

int _msg_tbl_length = 297;
