m_pcRoot = new os::VLayoutNode( "Root" );
m_pcVRoot = new os::VLayoutNode( "VRoot", 1.000000 );
m_pcVRoot->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcRoot->AddChild( m_pcVRoot );
m_pcMenuNode = new os::VLayoutNode( "MenuNode", 0.000001 );
m_pcMenuNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcVRoot->AddChild( m_pcMenuNode );
m_pcMenu = new os::Menu( os::Rect(), "Menu", os::ITEMS_IN_ROW );
os::Menu* pcMenuApplicationMenu = new os::Menu( os::Rect(), MSG_MAINWND_MENU_APPLICATION, os::ITEMS_IN_COLUMN );
pcMenuApplicationMenu->AddItem( MSG_MAINWND_MENU_APPLICATION_QUIT, new Message( M_MENU_QUIT ) );
pcMenuApplicationMenu->AddItem( new MenuSeparator() );
pcMenuApplicationMenu->AddItem( MSG_MAINWND_MENU_APPLICATION_HELP, new Message( M_MENU_HELP ) );
pcMenuApplicationMenu->AddItem( MSG_MAINWND_MENU_APPLICATION_WEBSITE, new Message( M_MENU_WEB ) );
pcMenuApplicationMenu->AddItem( new MenuSeparator() );
pcMenuApplicationMenu->AddItem( MSG_MAINWND_MENU_APPLICATION_ABOUT, new Message( M_MENU_ABOUT ) );
m_pcMenu->AddItem( pcMenuApplicationMenu );
os::Menu* pcMenuContactsMenu = new os::Menu( os::Rect(), MSG_MAINWND_MENU_CONTACTS, os::ITEMS_IN_COLUMN );
pcMenuContactsMenu->AddItem( MSG_MAINWND_MENU_CONTACTS_SAVE, new Message( M_MENU_SAVE ) );
pcMenuContactsMenu->AddItem( new MenuSeparator() );
pcMenuContactsMenu->AddItem( MSG_MAINWND_MENU_CONTACTS_NEWCONTACT, new Message( M_MENU_NEW ) );
pcMenuContactsMenu->AddItem( MSG_MAINWND_MENU_CONTACTS_DELCONTACT, new Message( M_MENU_DELETE ) );
m_pcMenu->AddItem( pcMenuContactsMenu );
m_pcMenu->SetTargetForItems(this);
m_pcMenuNode->AddChild( m_pcMenu, 1.000000 );
os::ToolBar* pcToolBar = new os::ToolBar( Rect(), "button_bar");
os::File cToolbarNewButtonFile( open_image_file( get_image_id() ) );
os::Resources cToolbarNewButtonResources( &cToolbarNewButtonFile );
os::ResStream* pcToolbarNewButtonStream = cToolbarNewButtonResources.GetResourceStream( "toolbar-new.png" );
os::ImageButton* pcImageNew = new os::ImageButton( Rect(),  "appwindow_new", MSG_MAINWND_TOOLBAR_NEW, new os::Message(M_TOOLBAR_NEW), new os::BitmapImage( pcToolbarNewButtonStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcToolbarNewButtonStream );
pcToolBar->AddChild( pcImageNew, ToolBar::TB_FIXED_WIDTH );
os::File cToolbarDeleteButtonFile( open_image_file( get_image_id() ) );
os::Resources cToolbarDeleteButtonResources( &cToolbarDeleteButtonFile );
os::ResStream* pcToolbarDeleteButtonStream = cToolbarDeleteButtonResources.GetResourceStream( "toolbar-delete.png" );
os::ImageButton* pcImageDelete = new os::ImageButton( Rect(),  "appwindow_delete", MSG_MAINWND_TOOLBAR_DELETE, new os::Message(M_TOOLBAR_DELETE), new os::BitmapImage( pcToolbarDeleteButtonStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcToolbarDeleteButtonStream );
pcToolBar->AddChild( pcImageDelete, ToolBar::TB_FIXED_WIDTH );
pcToolBar->AddSeparator( "button_bar" );
os::File cToolbarSaveButtonFile( open_image_file( get_image_id() ) );
os::Resources cToolbarSaveButtonResources( &cToolbarSaveButtonFile );
os::ResStream* pcToolbarSaveButtonStream = cToolbarSaveButtonResources.GetResourceStream( "toolbar-save.png" );
os::ImageButton* pcImageSave = new os::ImageButton( Rect(),  "appwindow_save", MSG_MAINWND_TOOLBAR_SAVE, new os::Message(M_TOOLBAR_SAVE), new os::BitmapImage( pcToolbarSaveButtonStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcToolbarSaveButtonStream );
pcToolBar->AddChild( pcImageSave, ToolBar::TB_FIXED_WIDTH );
m_pcMenuNode->AddChild( pcToolBar );
m_pcMainNode = new os::HLayoutNode( "MainNode", 2.000000 );
m_pcMainNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcVRoot->AddChild( m_pcMainNode );
m_pcContactNode = new os::VLayoutNode( "ContactNode", 1.000000 );
m_pcContactNode->SetBorders( os::Rect( 5.000000, 0.000000, 0.000000, 5.000000 ) );
m_pcMainNode->AddChild( m_pcContactNode );
m_pcSearchFrame = new os::FrameView( os::Rect(), "SearchFrame", MSG_MAINWND_CONTACT_SEARCH );
m_pcSearchFrameLayout = new os::VLayoutNode( "SearchFrameLayout" );
m_pcSearchFrameLayout->SetBorders( os::Rect( 3.000000, 0.000000, 0.000000, 3.000000 ) );
m_pcContactNode->AddChild( m_pcSearchFrame, 1.000000 );
m_pcSearchDropdown = new os::DropdownMenu( os::Rect(), "SearchDropdown" );
m_pcSearchDropdown->SetSelectionMessage( new os::Message( M_SEARCH_TYPE ) );
m_pcSearchDropdown->SetReadOnly( true );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_ALL );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_FIRSTNAME );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_MIDDLENAME );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_LASTNAME );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_NICKNAME );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_COMPANY );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_ADDRESS );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_ZIP );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_CITY );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_STATE );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_COUNTRY );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_PHONE );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_CELLPHONE );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_FAX );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_PAGER );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_EMAIL );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_ICQ );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_MSN );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_JABBER );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_YAHOO );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_AOL );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_SKYPE );
m_pcSearchDropdown->AppendItem( MSG_MAINWND_CONTACT_SEARCHTYPES_WEBSITE );
m_pcSearchDropdown->SetSelection( (int) 0 );
m_pcSearchFrameLayout->AddChild( m_pcSearchDropdown, 1.000000 );
m_pcSearchData = new os::TextView( os::Rect(), "SearchData", "" );
m_pcSearchFrameLayout->AddChild( m_pcSearchData, 1.000000 );
m_pcSearchSpacer = new os::VLayoutSpacer( "SearchSpacer", 5.000000, 5.000000, NULL, 1.000000 );
m_pcSearchFrameLayout->AddChild( m_pcSearchSpacer );
m_pcSearchButton = new os::HLayoutNode( "SearchButton", 1.000000 );
m_pcSearchButton->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcSearchFrameLayout->AddChild( m_pcSearchButton );
os::File cSearchNowFile( open_image_file( get_image_id() ) );
os::Resources cSearchNowResources( &cSearchNowFile );
os::ResStream* pcSearchNowStream = cSearchNowResources.GetResourceStream( "contact-find.png" );
m_pcSearchNow = new os::ImageButton( os::Rect(), "SearchNow", MSG_MAINWND_CONTACT_SEARCHCONTACT, new os::Message( M_SEARCH_NOW ), new os::BitmapImage( pcSearchNowStream ), os::ImageButton::IB_TEXT_RIGHT, true, true, true );
delete( pcSearchNowStream );
m_pcSearchButton->AddChild( m_pcSearchNow, 0.000001 );
m_pcSearchButtonSpacer = new os::HLayoutSpacer( "SearchButtonSpacer", 5.000000, 100000.000000, NULL, 1.000000 );
m_pcSearchButton->AddChild( m_pcSearchButtonSpacer );
m_pcSearchFrame->SetRoot( m_pcSearchFrameLayout );
m_pcContactSpacer1 = new os::VLayoutSpacer( "ContactSpacer1", 10.000000, 10.000000, NULL, 1.000000 );
m_pcContactNode->AddChild( m_pcContactSpacer1 );
m_pcContactCategory = new os::DropdownMenu( os::Rect(), "ContactCategory" );
m_pcContactCategory->SetSelectionMessage( new os::Message( M_CONTACT_CATEGORY ) );
m_pcContactCategory->SetReadOnly( true );
m_pcContactCategory->SetTarget( this );
m_pcContactNode->AddChild( m_pcContactCategory, 1.000000 );
m_pcContactList = new os::ListView( os::Rect(), "ContactList", os::ListView::F_RENDER_BORDER | os::ListView::F_NO_HEADER );
m_pcContactList->InsertColumn( "", 100 );
m_pcContactNode->AddChild( m_pcContactList, 50.000000 );
m_pcContactSpacer2 = new os::VLayoutSpacer( "ContactSpacer2", 5.000000, 5.000000, NULL, 1.000000 );
m_pcContactNode->AddChild( m_pcContactSpacer2 );
os::File cShowContactFile( open_image_file( get_image_id() ) );
os::Resources cShowContactResources( &cShowContactFile );
os::ResStream* pcShowContactStream = cShowContactResources.GetResourceStream( "contact-show.png" );
m_pcShowContact = new os::ImageButton( os::Rect(), "ShowContact", MSG_MAINWND_CONTACT_SHOWCONTACT, new os::Message( M_CONTACT_SHOW ), new os::BitmapImage( pcShowContactStream ), os::ImageButton::IB_TEXT_LEFT, true, true, true );
delete( pcShowContactStream );
m_pcContactNode->AddChild( m_pcShowContact, 0.000001 );
m_pcMainSpacer = new os::HLayoutSpacer( "MainSpacer", 10.000000, 10.000000, NULL, 1.000000 );
m_pcMainNode->AddChild( m_pcMainSpacer );
m_pcTabView = new os::TabView( os::Rect(), "TabView" );
m_pcNameNodeTab = new os::LayoutView( os::Rect(), "NameNodeTab" );
m_pcNameNodeLayout = new os::VLayoutNode( "NameNodeLayout" );
m_pcTabView->AppendTab( MSG_MAINWND_NAME_TITLE, m_pcNameNodeTab );
m_pcInfoNodeTab = new os::LayoutView( os::Rect(), "InfoNodeTab" );
m_pcInfoNodeLayout = new os::VLayoutNode( "InfoNodeLayout" );
m_pcTabView->AppendTab( MSG_MAINWND_INFO_TITLE, m_pcInfoNodeTab );
m_pcNotesNodeTab = new os::LayoutView( os::Rect(), "NotesNodeTab" );
m_pcNotesNodeLayout = new os::VLayoutNode( "NotesNodeLayout" );
m_pcTabView->AppendTab( MSG_MAINWND_NOTES_TITLE, m_pcNotesNodeTab );
m_pcMainNode->AddChild( m_pcTabView, 10.000000 );
m_pcNameNode = new os::VLayoutNode( "NameNode", 1.000000 );
m_pcNameNode->SetBorders( os::Rect( 5.000000, 5.000000, 5.000000, 5.000000 ) );
m_pcNameNodeLayout->AddChild( m_pcNameNode );
m_pcNameFrame = new os::FrameView( os::Rect(), "NameFrame", "" );
m_pcNameFrameLayout = new os::VLayoutNode( "NameFrameLayout" );
m_pcNameFrameLayout->SetBorders( os::Rect( 5.000000, 0.000000, 5.000000, 5.000000 ) );
m_pcNameNode->AddChild( m_pcNameFrame, 1.000000 );
m_pcGeneralInfoNode = new os::HLayoutNode( "GeneralInfoNode", 1.000000 );
m_pcGeneralInfoNode->SetBorders( os::Rect( 0.000000, 10.000000, 0.000000, 0.000000 ) );
m_pcNameFrameLayout->AddChild( m_pcGeneralInfoNode );
m_pcCategoryNode = new os::VLayoutNode( "CategoryNode", 0.500000 );
m_pcCategoryNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcGeneralInfoNode->AddChild( m_pcCategoryNode );
m_pcCategoryList = new os::ListView( os::Rect(), "CategoryList", os::ListView::F_MULTI_SELECT | os::ListView::F_RENDER_BORDER | os::ListView::F_NO_HEADER );
m_pcCategoryList->InsertColumn( "Category", 1 );
m_pcCategoryNode->AddChild( m_pcCategoryList, 10.000000 );
m_pcContactCategoryDropdown = new os::DropdownMenu( os::Rect(), "ContactCategoryDropdown" );
m_pcContactCategoryDropdown->SetSelectionMessage( new os::Message( M_NAME_CATEGORY ) );
m_pcContactCategoryDropdown->SetReadOnly( true );
m_pcCategoryNode->AddChild( m_pcContactCategoryDropdown, 1.000000 );
m_pcContactCategoryText = new os::TextView( os::Rect(), "ContactCategoryText", "" );
m_pcContactCategoryText->Set( MSG_MAINWND_CATEGORY_NEWCATEGORY.c_str() );
m_pcCategoryNode->AddChild( m_pcContactCategoryText, 1.000000 );
m_pcCategoryButtons = new os::VLayoutNode( "CategoryButtons", 0.000001 );
m_pcCategoryButtons->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcGeneralInfoNode->AddChild( m_pcCategoryButtons );
m_pcCategoryButtonsSpacer1 = new os::VLayoutSpacer( "CategoryButtonsSpacer1", 0.000000, 100000.000000, NULL, 10.000000 );
m_pcCategoryButtons->AddChild( m_pcCategoryButtonsSpacer1 );
os::File cCategoryAddFile( open_image_file( get_image_id() ) );
os::Resources cCategoryAddResources( &cCategoryAddFile );
os::ResStream* pcCategoryAddStream = cCategoryAddResources.GetResourceStream( "list-add.png" );
m_pcCategoryAdd = new os::ImageButton( os::Rect(), "CategoryAdd", "", new os::Message( M_NAME_CATEGORY_ADD ), new os::BitmapImage( pcCategoryAddStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcCategoryAddStream );
m_pcCategoryButtons->AddChild( m_pcCategoryAdd, 1.000000 );
m_pcContactButtonsSpacer2 = new os::VLayoutSpacer( "ContactButtonsSpacer2", 2.000000, 2.000000, NULL, 1.000000 );
m_pcCategoryButtons->AddChild( m_pcContactButtonsSpacer2 );
os::File cCategoryRemoveFile( open_image_file( get_image_id() ) );
os::Resources cCategoryRemoveResources( &cCategoryRemoveFile );
os::ResStream* pcCategoryRemoveStream = cCategoryRemoveResources.GetResourceStream( "list-remove.png" );
m_pcCategoryRemove = new os::ImageButton( os::Rect(), "CategoryRemove", "", new os::Message( M_NAME_CATEGORY_REMOVE ), new os::BitmapImage( pcCategoryRemoveStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcCategoryRemoveStream );
m_pcCategoryButtons->AddChild( m_pcCategoryRemove, 1.000000 );
m_pcContactButtonsSpacer3 = new os::VLayoutSpacer( "ContactButtonsSpacer3", 0.000000, 100000.000000, NULL, 10.000000 );
m_pcCategoryButtons->AddChild( m_pcContactButtonsSpacer3 );
m_pcGeneralInfoSeparator = new os::Separator( os::Rect(), "GeneralInfoSeparator", os::VERTICAL );
m_pcGeneralInfoNode->AddChild( m_pcGeneralInfoSeparator, 2.000000 );
m_pcImageNode = new os::VLayoutNode( "ImageNode", 1.000000 );
m_pcImageNode->SetBorders( os::Rect( 2.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcGeneralInfoNode->AddChild( m_pcImageNode );
m_pcImage = new os::HLayoutNode( "Image", 0.000001 );
m_pcImage->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 5.000000 ) );
m_pcImageNode->AddChild( m_pcImage );
m_pcImageSpacer1 = new os::HLayoutSpacer( "ImageSpacer1", 0.000000, 100000.000000, NULL, 1.000000 );
m_pcImage->AddChild( m_pcImageSpacer1 );
os::File cContactImageFile( open_image_file( get_image_id() ) );
os::Resources cContactImageResources( &cContactImageFile );
os::ResStream* pcContactImageStream = cContactImageResources.GetResourceStream( "nouserimage.png" );
m_pcContactImage = new os::ImageButton( os::Rect(), "ContactImage", "", new os::Message( M_NAME_IMAGE ), new os::BitmapImage( pcContactImageStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcContactImageStream );
m_pcImage->AddChild( m_pcContactImage, 0.000001 );
m_pcImageSpacer2 = new os::VLayoutSpacer( "ImageSpacer2", 0.000000, 100000.000000, NULL, 1.000000 );
m_pcImageNode->AddChild( m_pcImageSpacer2 );
m_pcGenderDropdown = new os::DropdownMenu( os::Rect(), "GenderDropdown" );
m_pcGenderDropdown->SetSelectionMessage( new os::Message( M_NAME_GENDER ) );
m_pcGenderDropdown->SetReadOnly( true );
m_pcGenderDropdown->AppendItem( MSG_MAINWND_GENDER_SELECT );
m_pcGenderDropdown->AppendItem( MSG_MAINWND_GENDER_MALE );
m_pcGenderDropdown->AppendItem( MSG_MAINWND_GENDER_FEMALE );
m_pcGenderDropdown->AppendItem( MSG_MAINWND_GENDER_DUOGENDER );
m_pcGenderDropdown->AppendItem( MSG_MAINWND_GENDER_UNKNOWN );
m_pcGenderDropdown->SetSelection( (int) 0 );
m_pcImageNode->AddChild( m_pcGenderDropdown, 1.000000 );
m_pcNameSeparator1 = new os::Separator( os::Rect(), "NameSeparator1", os::HORIZONTAL );
m_pcNameFrameLayout->AddChild( m_pcNameSeparator1, 1.000000 );
m_pcNameInfoNode = new os::HLayoutNode( "NameInfoNode", 1.000000 );
m_pcNameInfoNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcNameFrameLayout->AddChild( m_pcNameInfoNode );
m_pcNameInfoStrings = new os::VLayoutNode( "NameInfoStrings", 1.000000 );
m_pcNameInfoStrings->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcNameInfoNode->AddChild( m_pcNameInfoStrings );
m_pcNameFirstNameString = new os::StringView( os::Rect(), "NameFirstNameString", MSG_MAINWND_NAME_FIRSTNAME );
m_pcNameInfoStrings->AddChild( m_pcNameFirstNameString, 1.000000 );
m_pcNameMiddleNameString = new os::StringView( os::Rect(), "NameMiddleNameString", MSG_MAINWND_NAME_MIDDLENAME );
m_pcNameInfoStrings->AddChild( m_pcNameMiddleNameString, 1.000000 );
m_pcNameLastNameString = new os::StringView( os::Rect(), "NameLastNameString", MSG_MAINWND_NAME_LASTNAME );
m_pcNameInfoStrings->AddChild( m_pcNameLastNameString, 1.000000 );
m_pcNameNicknameString = new os::StringView( os::Rect(), "NameNicknameString", MSG_MAINWND_NAME_NICKNAME );
m_pcNameInfoStrings->AddChild( m_pcNameNicknameString, 1.000000 );
m_pcNameCompanyString = new os::StringView( os::Rect(), "NameCompanyString", MSG_MAINWND_NAME_COMPANY );
m_pcNameInfoStrings->AddChild( m_pcNameCompanyString, 1.000000 );
m_pcNameInfoData = new os::VLayoutNode( "NameInfoData", 3.000000 );
m_pcNameInfoData->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcNameInfoNode->AddChild( m_pcNameInfoData );
m_pcNameInfoSpacer1 = new os::VLayoutSpacer( "NameInfoSpacer1", 2.000000, 100000.000000, NULL, 0.500000 );
m_pcNameInfoData->AddChild( m_pcNameInfoSpacer1 );
m_pcNameFirstnameNode = new os::HLayoutNode( "NameFirstnameNode", 1.000000 );
m_pcNameFirstnameNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcNameInfoData->AddChild( m_pcNameFirstnameNode );
m_pcNamePreFirstnameData = new os::TextView( os::Rect(), "NamePreFirstnameData", "" );
m_pcNameFirstnameNode->AddChild( m_pcNamePreFirstnameData, 1.000000 );
m_pcNameFirstnameData = new os::TextView( os::Rect(), "NameFirstnameData", "" );
m_pcNameFirstnameNode->AddChild( m_pcNameFirstnameData, 3.000000 );
m_pcNameInfoSpacer2 = new os::VLayoutSpacer( "NameInfoSpacer2", 2.000000, 100000.000000, NULL, 1.000000 );
m_pcNameInfoData->AddChild( m_pcNameInfoSpacer2 );
m_pcNameMiddlenameNode = new os::HLayoutNode( "NameMiddlenameNode", 1.000000 );
m_pcNameMiddlenameNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcNameInfoData->AddChild( m_pcNameMiddlenameNode );
m_pcNamePreMiddlenameData = new os::TextView( os::Rect(), "NamePreMiddlenameData", "" );
m_pcNameMiddlenameNode->AddChild( m_pcNamePreMiddlenameData, 1.000000 );
m_pcNameMiddlenameData = new os::TextView( os::Rect(), "NameMiddlenameData", "" );
m_pcNameMiddlenameNode->AddChild( m_pcNameMiddlenameData, 3.000000 );
m_pcNameInfoSpacer3 = new os::VLayoutSpacer( "NameInfoSpacer3", 2.000000, 100000.000000, NULL, 1.000000 );
m_pcNameInfoData->AddChild( m_pcNameInfoSpacer3 );
m_pcNameLastnameNode = new os::HLayoutNode( "NameLastnameNode", 1.000000 );
m_pcNameLastnameNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcNameInfoData->AddChild( m_pcNameLastnameNode );
m_pcNamePreLastnameData = new os::TextView( os::Rect(), "NamePreLastnameData", "" );
m_pcNameLastnameNode->AddChild( m_pcNamePreLastnameData, 1.000000 );
m_pcNameLastnameData = new os::TextView( os::Rect(), "NameLastnameData", "" );
m_pcNameLastnameNode->AddChild( m_pcNameLastnameData, 3.000000 );
m_pcNameInfoSpacer4 = new os::VLayoutSpacer( "NameInfoSpacer4", 2.000000, 100000.000000, NULL, 1.000000 );
m_pcNameInfoData->AddChild( m_pcNameInfoSpacer4 );
m_pcNameNicknameData = new os::TextView( os::Rect(), "NameNicknameData", "" );
m_pcNameInfoData->AddChild( m_pcNameNicknameData, 1.000000 );
m_pcNameInfoSpacer5 = new os::VLayoutSpacer( "NameInfoSpacer5", 2.000000, 100000.000000, NULL, 1.000000 );
m_pcNameInfoData->AddChild( m_pcNameInfoSpacer5 );
m_pcNameCompanyData = new os::TextView( os::Rect(), "NameCompanyData", "" );
m_pcNameInfoData->AddChild( m_pcNameCompanyData, 1.000000 );
m_pcNameInfoSpacer6 = new os::VLayoutSpacer( "NameInfoSpacer6", 2.000000, 100000.000000, NULL, 0.500000 );
m_pcNameInfoData->AddChild( m_pcNameInfoSpacer6 );
m_pcNameSeparator2 = new os::Separator( os::Rect(), "NameSeparator2", os::HORIZONTAL );
m_pcNameFrameLayout->AddChild( m_pcNameSeparator2, 1.000000 );
m_pcAddressTab = new os::TabView( os::Rect(), "AddressTab" );
m_pcPriAddressNodeTab = new os::LayoutView( os::Rect(), "PriAddressNodeTab" );
m_pcPriAddressNodeLayout = new os::VLayoutNode( "PriAddressNodeLayout" );
m_pcAddressTab->AppendTab( MSG_MAINWND_NAME_PRIMARYADDRESS, m_pcPriAddressNodeTab );
m_pcSecAddressNodeTab = new os::LayoutView( os::Rect(), "SecAddressNodeTab" );
m_pcSecAddressNodeLayout = new os::VLayoutNode( "SecAddressNodeLayout" );
m_pcAddressTab->AppendTab(  MSG_MAINWND_NAME_SECONDARYADDRESS, m_pcSecAddressNodeTab );
m_pcNameFrameLayout->AddChild( m_pcAddressTab, 1.000000 );
m_pcPriAddressNode = new os::HLayoutNode( "PriAddressNode", 1.000000 );
m_pcPriAddressNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcPriAddressNodeLayout->AddChild( m_pcPriAddressNode );
m_pcPriAddressStrings = new os::VLayoutNode( "PriAddressStrings", 1.000000 );
m_pcPriAddressStrings->SetBorders( os::Rect( 5.000000, 0.000000, 5.000000, 0.000000 ) );
m_pcPriAddressNode->AddChild( m_pcPriAddressStrings );
m_pcPriAddressAddress1String = new os::StringView( os::Rect(), "PriAddressAddress1String", MSG_MAINWND_NAME_ADDRESS1 );
m_pcPriAddressStrings->AddChild( m_pcPriAddressAddress1String, 1.000000 );
m_pcPriAddressAddress2String = new os::StringView( os::Rect(), "PriAddressAddress2String", MSG_MAINWND_NAME_ADDRESS2 );
m_pcPriAddressStrings->AddChild( m_pcPriAddressAddress2String, 1.000000 );
m_pcPriAddressAddress3String = new os::StringView( os::Rect(), "PriAddressAddress3String", MSG_MAINWND_NAME_ADDRESS3 );
m_pcPriAddressStrings->AddChild( m_pcPriAddressAddress3String, 1.000000 );
m_pcPriAddressZCSNode = new os::HLayoutNode( "PriAddressZCSNode", 1.000000 );
m_pcPriAddressZCSNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcPriAddressStrings->AddChild( m_pcPriAddressZCSNode );
m_pcPriAddressZCSDropdown = new os::DropdownMenu( os::Rect(), "PriAddressZCSDropdown" );
m_pcPriAddressZCSDropdown->SetSelectionMessage( new os::Message( M_PRIADDRESS_SELECTZCS ) );
m_pcPriAddressZCSDropdown->SetReadOnly( true );
m_pcPriAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_SELECT );
m_pcPriAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_ZCS );
m_pcPriAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_ZSC );
m_pcPriAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_CZS );
m_pcPriAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_CSZ );
m_pcPriAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_SZC );
m_pcPriAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_SCZ );
m_pcPriAddressZCSDropdown->SetSelection( (int) 0 );
m_pcPriAddressZCSNode->AddChild( m_pcPriAddressZCSDropdown, 1.000000 );
m_pcPriAddressZCSSpacer = new os::HLayoutSpacer( "PriAddressZCSSpacer", 5.000000, 100000.000000, NULL, 1.000000 );
m_pcPriAddressZCSNode->AddChild( m_pcPriAddressZCSSpacer );
m_pcPriAddressCountryString = new os::StringView( os::Rect(), "PriAddressCountryString", MSG_MAINWND_NAME_COUNTRY );
m_pcPriAddressStrings->AddChild( m_pcPriAddressCountryString, 1.000000 );
m_pcPriAddressData = new os::VLayoutNode( "PriAddressData", 10.000000 );
m_pcPriAddressData->SetBorders( os::Rect( 5.000000, 0.000000, 5.000000, 0.000000 ) );
m_pcPriAddressNode->AddChild( m_pcPriAddressData );
m_pcPriAddressSpacer1 = new os::VLayoutSpacer( "PriAddressSpacer1", 2.000000, 100000.000000, NULL, 0.500000 );
m_pcPriAddressData->AddChild( m_pcPriAddressSpacer1 );
m_pcPriAddressAddress1Data = new os::TextView( os::Rect(), "PriAddressAddress1Data", "" );
m_pcPriAddressData->AddChild( m_pcPriAddressAddress1Data, 1.000000 );
m_pcPriAddressSpacer2 = new os::VLayoutSpacer( "PriAddressSpacer2", 2.000000, 100000.000000, NULL, 1.000000 );
m_pcPriAddressData->AddChild( m_pcPriAddressSpacer2 );
m_pcPriAddressAddress2Data = new os::TextView( os::Rect(), "PriAddressAddress2Data", "" );
m_pcPriAddressData->AddChild( m_pcPriAddressAddress2Data, 1.000000 );
m_pcPriAddressSpacer3 = new os::VLayoutSpacer( "PriAddressSpacer3", 2.000000, 100000.000000, NULL, 1.000000 );
m_pcPriAddressData->AddChild( m_pcPriAddressSpacer3 );
m_pcPriAddressAddress3Data = new os::TextView( os::Rect(), "PriAddressAddress3Data", "" );
m_pcPriAddressData->AddChild( m_pcPriAddressAddress3Data, 1.000000 );
m_pcPriAddressSpacer4 = new os::VLayoutSpacer( "PriAddressSpacer4", 0.000000, 100000.000000, NULL, 1.000000 );
m_pcPriAddressData->AddChild( m_pcPriAddressSpacer4 );
m_pcPriAddressZCSData = new os::HLayoutNode( "PriAddressZCSData", 1.000000 );
m_pcPriAddressZCSData->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcPriAddressData->AddChild( m_pcPriAddressZCSData );
m_pcPriAddressZCS1Data = new os::TextView( os::Rect(), "PriAddressZCS1Data", "" );
m_pcPriAddressZCSData->AddChild( m_pcPriAddressZCS1Data, 1.000000 );
m_pcPriAddressZCSSpacer1 = new os::HLayoutSpacer( "PriAddressZCSSpacer1", 2.000000, 2.000000, NULL, 1.000000 );
m_pcPriAddressZCSData->AddChild( m_pcPriAddressZCSSpacer1 );
m_pcPriAddressZCS2Data = new os::TextView( os::Rect(), "PriAddressZCS2Data", "" );
m_pcPriAddressZCSData->AddChild( m_pcPriAddressZCS2Data, 1.000000 );
m_pcPriAddressZCSSpacer2 = new os::HLayoutSpacer( "PriAddressZCSSpacer2", 2.000000, 2.000000, NULL, 1.000000 );
m_pcPriAddressZCSData->AddChild( m_pcPriAddressZCSSpacer2 );
m_pcPriAddressZCS3Data = new os::TextView( os::Rect(), "PriAddressZCS3Data", "" );
m_pcPriAddressZCSData->AddChild( m_pcPriAddressZCS3Data, 1.000000 );
m_pcPriAddressSpacer5 = new os::VLayoutSpacer( "PriAddressSpacer5", 0.000000, 100000.000000, NULL, 1.000000 );
m_pcPriAddressData->AddChild( m_pcPriAddressSpacer5 );
m_pcPriAddressCountryData = new os::TextView( os::Rect(), "PriAddressCountryData", "" );
m_pcPriAddressData->AddChild( m_pcPriAddressCountryData, 1.000000 );
m_pcPriAddressSpacer6 = new os::VLayoutSpacer( "PriAddressSpacer6", 2.000000, 100000.000000, NULL, 0.500000 );
m_pcPriAddressData->AddChild( m_pcPriAddressSpacer6 );
m_pcSecAddressNode = new os::HLayoutNode( "SecAddressNode", 1.000000 );
m_pcSecAddressNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcSecAddressNodeLayout->AddChild( m_pcSecAddressNode );
m_pcSecAddressStrings = new os::VLayoutNode( "SecAddressStrings", 1.000000 );
m_pcSecAddressStrings->SetBorders( os::Rect( 5.000000, 0.000000, 5.000000, 0.000000 ) );
m_pcSecAddressNode->AddChild( m_pcSecAddressStrings );
m_pcSecAddressAddress1String = new os::StringView( os::Rect(), "SecAddressAddress1String", MSG_MAINWND_NAME_ADDRESS1 );
m_pcSecAddressStrings->AddChild( m_pcSecAddressAddress1String, 1.000000 );
m_pcSecAddressAddress2String = new os::StringView( os::Rect(), "SecAddressAddress2String", MSG_MAINWND_NAME_ADDRESS2 );
m_pcSecAddressStrings->AddChild( m_pcSecAddressAddress2String, 1.000000 );
m_pcSecAddressAddress3String = new os::StringView( os::Rect(), "SecAddressAddress3String", MSG_MAINWND_NAME_ADDRESS3 );
m_pcSecAddressStrings->AddChild( m_pcSecAddressAddress3String, 1.000000 );
m_pcSecAddressZCSNode = new os::HLayoutNode( "SecAddressZCSNode", 1.000000 );
m_pcSecAddressZCSNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcSecAddressStrings->AddChild( m_pcSecAddressZCSNode );
m_pcSecAddressZCSDropdown = new os::DropdownMenu( os::Rect(), "SecAddressZCSDropdown" );
m_pcSecAddressZCSDropdown->SetSelectionMessage( new os::Message( M_SECADDRESS_SELECTZCS ) );
m_pcSecAddressZCSDropdown->SetReadOnly( true );
m_pcSecAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_SELECT );
m_pcSecAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_ZCS );
m_pcSecAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_ZSC );
m_pcSecAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_CZS );
m_pcSecAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_CSZ );
m_pcSecAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_SZC );
m_pcSecAddressZCSDropdown->AppendItem( MSG_MAINWND_NAME_ZCS_SCZ );
m_pcSecAddressZCSDropdown->SetSelection( (int) 0 );
m_pcSecAddressZCSNode->AddChild( m_pcSecAddressZCSDropdown, 1.000000 );
m_pcSecAddressZCSSpacer = new os::HLayoutSpacer( "SecAddressZCSSpacer", 5.000000, 100000.000000, NULL, 1.000000 );
m_pcSecAddressZCSNode->AddChild( m_pcSecAddressZCSSpacer );
m_pcSecAddressCountryString = new os::StringView( os::Rect(), "SecAddressCountryString", MSG_MAINWND_NAME_COUNTRY );
m_pcSecAddressStrings->AddChild( m_pcSecAddressCountryString, 1.000000 );
m_pcSecAddressData = new os::VLayoutNode( "SecAddressData", 10.000000 );
m_pcSecAddressData->SetBorders( os::Rect( 5.000000, 0.000000, 5.000000, 0.000000 ) );
m_pcSecAddressNode->AddChild( m_pcSecAddressData );
m_pcSecAddressSpacer1 = new os::VLayoutSpacer( "SecAddressSpacer1", 2.000000, 100000.000000, NULL, 0.500000 );
m_pcSecAddressData->AddChild( m_pcSecAddressSpacer1 );
m_pcSecAddressAddress1Data = new os::TextView( os::Rect(), "SecAddressAddress1Data", "" );
m_pcSecAddressData->AddChild( m_pcSecAddressAddress1Data, 1.000000 );
m_pcSecAddressSpacer2 = new os::VLayoutSpacer( "SecAddressSpacer2", 2.000000, 100000.000000, NULL, 1.000000 );
m_pcSecAddressData->AddChild( m_pcSecAddressSpacer2 );
m_pcSecAddressAddress2Data = new os::TextView( os::Rect(), "SecAddressAddress2Data", "" );
m_pcSecAddressData->AddChild( m_pcSecAddressAddress2Data, 1.000000 );
m_pcSecAddressSpacer3 = new os::VLayoutSpacer( "SecAddressSpacer3", 2.000000, 100000.000000, NULL, 1.000000 );
m_pcSecAddressData->AddChild( m_pcSecAddressSpacer3 );
m_pcSecAddressAddress3Data = new os::TextView( os::Rect(), "SecAddressAddress3Data", "" );
m_pcSecAddressData->AddChild( m_pcSecAddressAddress3Data, 1.000000 );
m_pcSecAddressSpacer4 = new os::VLayoutSpacer( "SecAddressSpacer4", 0.000000, 100000.000000, NULL, 1.000000 );
m_pcSecAddressData->AddChild( m_pcSecAddressSpacer4 );
m_pcSecAddressZCSData = new os::HLayoutNode( "SecAddressZCSData", 1.000000 );
m_pcSecAddressZCSData->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcSecAddressData->AddChild( m_pcSecAddressZCSData );
m_pcSecAddressZCS1Data = new os::TextView( os::Rect(), "SecAddressZCS1Data", "" );
m_pcSecAddressZCSData->AddChild( m_pcSecAddressZCS1Data, 1.000000 );
m_pcSecAddressZCSSpacer1 = new os::HLayoutSpacer( "SecAddressZCSSpacer1", 2.000000, 2.000000, NULL, 1.000000 );
m_pcSecAddressZCSData->AddChild( m_pcSecAddressZCSSpacer1 );
m_pcSecAddressZCS2Data = new os::TextView( os::Rect(), "SecAddressZCS2Data", "" );
m_pcSecAddressZCSData->AddChild( m_pcSecAddressZCS2Data, 1.000000 );
m_pcSecAddressZCSSpacer2 = new os::HLayoutSpacer( "SecAddressZCSSpacer2", 2.000000, 2.000000, NULL, 1.000000 );
m_pcSecAddressZCSData->AddChild( m_pcSecAddressZCSSpacer2 );
m_pcSecAddressZCS3Data = new os::TextView( os::Rect(), "SecAddressZCS3Data", "" );
m_pcSecAddressZCSData->AddChild( m_pcSecAddressZCS3Data, 1.000000 );
m_pcSecAddressSpacer5 = new os::VLayoutSpacer( "SecAddressSpacer5", 0.000000, 100000.000000, NULL, 1.000000 );
m_pcSecAddressData->AddChild( m_pcSecAddressSpacer5 );
m_pcSecAddressCountryData = new os::TextView( os::Rect(), "SecAddressCountryData", "" );
m_pcSecAddressData->AddChild( m_pcSecAddressCountryData, 1.000000 );
m_pcSecAddressSpacer6 = new os::VLayoutSpacer( "SecAddressSpacer6", 2.000000, 100000.000000, NULL, 0.500000 );
m_pcSecAddressData->AddChild( m_pcSecAddressSpacer6 );
m_pcPriAddressNodeTab->SetRoot( m_pcPriAddressNodeLayout );
m_pcSecAddressNodeTab->SetRoot( m_pcSecAddressNodeLayout );
m_pcNameFrame->SetRoot( m_pcNameFrameLayout );
m_pcInfoNode = new os::VLayoutNode( "InfoNode", 1.000000 );
m_pcInfoNode->SetBorders( os::Rect( 5.000000, 5.000000, 5.000000, 5.000000 ) );
m_pcInfoNodeLayout->AddChild( m_pcInfoNode );
m_pcInfoFrame = new os::FrameView( os::Rect(), "InfoFrame", "" );
m_pcInfoFrameLayout = new os::VLayoutNode( "InfoFrameLayout" );
m_pcInfoFrameLayout->SetBorders( os::Rect( 5.000000, 0.000000, 5.000000, 5.000000 ) );
m_pcInfoNode->AddChild( m_pcInfoFrame, 1.000000 );
m_pcInfoMainNode = new os::HLayoutNode( "InfoMainNode", 1.000000 );
m_pcInfoMainNode->SetBorders( os::Rect( 0.000000, 10.000000, 0.000000, 0.000000 ) );
m_pcInfoFrameLayout->AddChild( m_pcInfoMainNode );
m_pcInfoContentNode = new os::VLayoutNode( "InfoContentNode", 25.000000 );
m_pcInfoContentNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcInfoMainNode->AddChild( m_pcInfoContentNode );
m_pcInfoList = new os::ListView( os::Rect(), "InfoList", os::ListView::F_NO_AUTO_SORT | os::ListView::F_RENDER_BORDER );
m_pcInfoList->InsertColumn( MSG_MAINWND_INFO_LIST_TYPE.c_str(), 100 );
m_pcInfoList->InsertColumn( MSG_MAINWND_INFO_LIST_WHERE.c_str(), 75 );
m_pcInfoList->InsertColumn( MSG_MAINWND_INFO_LIST_DATA.c_str(), 0 );
m_pcInfoContentNode->AddChild( m_pcInfoList, 50.000000 );
m_pcInfoSeparator = new os::Separator( os::Rect(), "InfoSeparator", os::HORIZONTAL );
m_pcInfoContentNode->AddChild( m_pcInfoSeparator, 1.000000 );
m_pcInfoAddNode = new os::HLayoutNode( "InfoAddNode", 0.100000 );
m_pcInfoAddNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcInfoContentNode->AddChild( m_pcInfoAddNode );
m_pcInfoContactTypeNode = new os::VLayoutNode( "InfoContactTypeNode", 1.000000 );
m_pcInfoContactTypeNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcInfoAddNode->AddChild( m_pcInfoContactTypeNode );
m_pcInfoContactTypeDropdown = new os::DropdownMenu( os::Rect(), "InfoContactTypeDropdown" );
m_pcInfoContactTypeDropdown->SetSelectionMessage( new os::Message( M_INFO_TYPE ) );
m_pcInfoContactTypeDropdown->SetReadOnly( true );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_CHOOSETYPE );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_NEWTYPE );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_PHONE );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_CELLPHONE );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_FAX );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_PAGER );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_EMAIL );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_ICQ );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_MSN );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_JABBER );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_YAHOO );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_AOL );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_SKYPE );
m_pcInfoContactTypeDropdown->AppendItem( MSG_MAINWND_INFO_TYPE_WEBSITE );
m_pcInfoContactTypeDropdown->SetSelection( (int) 0 );
m_pcInfoContactTypeNode->AddChild( m_pcInfoContactTypeDropdown, 1.000000 );
m_pcInfoContactTypeText = new os::TextView( os::Rect(), "InfoContactTypeText", "" );
m_pcInfoContactTypeText->Set( MSG_MAINWND_INFO_TYPE_NEWTYPE.c_str() );
m_pcInfoContactTypeNode->AddChild( m_pcInfoContactTypeText, 1.000000 );
m_pcInfoContactSpacer = new os::HLayoutSpacer( "InfoContactSpacer", 20.000000, 100000.000000, NULL, 1.000000 );
m_pcInfoAddNode->AddChild( m_pcInfoContactSpacer );
m_pcInfoContactHWONode = new os::VLayoutNode( "InfoContactHWONode", 10.000000 );
m_pcInfoContactHWONode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcInfoAddNode->AddChild( m_pcInfoContactHWONode );
m_pcInfoContactHome = new os::RadioButton( os::Rect(), "InfoContactHome", MSG_MAINWND_INFO_WHERE_HOME, new os::Message( M_INFO_RADIO_HOME ) );
m_pcInfoContactHome->SetValue( true );
m_pcInfoContactHWONode->AddChild( m_pcInfoContactHome, 1.000000 );
m_pcInfoContactWork = new os::RadioButton( os::Rect(), "InfoContactWork", MSG_MAINWND_INFO_WHERE_WORK, new os::Message( M_INFO_RADIO_WORK ) );
m_pcInfoContactHWONode->AddChild( m_pcInfoContactWork, 1.000000 );
m_pcInfoContachOtherNode = new os::HLayoutNode( "InfoContachOtherNode", 1.000000 );
m_pcInfoContachOtherNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcInfoContactHWONode->AddChild( m_pcInfoContachOtherNode );
m_pcInfoContactOther = new os::RadioButton( os::Rect(), "InfoContactOther", "", new os::Message( M_INFO_RADIO_OTHER ) );
m_pcInfoContachOtherNode->AddChild( m_pcInfoContactOther, 0.100000 );
m_pcInfoContactOtherText = new os::TextView( os::Rect(), "InfoContactOtherText", "" );
m_pcInfoContactOtherText->Set( MSG_MAINWND_INFO_WHERE_OTHER.c_str() );
m_pcInfoContachOtherNode->AddChild( m_pcInfoContactOtherText, 10.000000 );
m_pcInfoContactOtherSpacer = new os::HLayoutSpacer( "InfoContactOtherSpacer", 0.000000, 100000.000000, NULL, 10.000000 );
m_pcInfoContachOtherNode->AddChild( m_pcInfoContactOtherSpacer );
m_pcInfoContactDataNode = new os::HLayoutNode( "InfoContactDataNode", 1.000000 );
m_pcInfoContactDataNode->SetBorders( os::Rect( 0.000000, 10.000000, 0.000000, 0.000000 ) );
m_pcInfoContentNode->AddChild( m_pcInfoContactDataNode );
m_pcInfoContactDataString = new os::StringView( os::Rect(), "InfoContactDataString", MSG_MAINWND_INFO_DATA_DATA );
m_pcInfoContactDataNode->AddChild( m_pcInfoContactDataString, 1.000000 );
m_pcInfoContactDataText = new os::TextView( os::Rect(), "InfoContactDataText", "" );
m_pcInfoContactDataNode->AddChild( m_pcInfoContactDataText, 25.000000 );
m_pcInfoNaviNode = new os::VLayoutNode( "InfoNaviNode", 0.000001 );
m_pcInfoNaviNode->SetBorders( os::Rect( 5.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcInfoMainNode->AddChild( m_pcInfoNaviNode );
os::File cInfoContactButtonFile( open_image_file( get_image_id() ) );
os::Resources cInfoContactButtonResources( &cInfoContactButtonFile );
os::ResStream* pcInfoContactButtonStream = cInfoContactButtonResources.GetResourceStream( "info-copy.png" );
m_pcInfoContactButton = new os::ImageButton( os::Rect(), "InfoContactButton", "", new os::Message( M_INFO_BUTTON_CONTACT ), new os::BitmapImage( pcInfoContactButtonStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcInfoContactButtonStream );
m_pcInfoNaviNode->AddChild( m_pcInfoContactButton, 0.000001 );
m_pcInfoNaviSpacer1 = new os::VLayoutSpacer( "InfoNaviSpacer1", 100.000000, 150.000000, NULL, 10.000000 );
m_pcInfoNaviNode->AddChild( m_pcInfoNaviSpacer1 );
os::File cInfoUpButtonFile( open_image_file( get_image_id() ) );
os::Resources cInfoUpButtonResources( &cInfoUpButtonFile );
os::ResStream* pcInfoUpButtonStream = cInfoUpButtonResources.GetResourceStream( "list-up.png" );
m_pcInfoUpButton = new os::ImageButton( os::Rect(), "InfoUpButton", "", new os::Message( M_INFO_BUTTON_MOVEUP ), new os::BitmapImage( pcInfoUpButtonStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcInfoUpButtonStream );
m_pcInfoNaviNode->AddChild( m_pcInfoUpButton, 0.000001 );
m_pcInfoNaviSpacer2 = new os::VLayoutSpacer( "InfoNaviSpacer2", 2.000000, 2.000000, NULL, 10.000000 );
m_pcInfoNaviNode->AddChild( m_pcInfoNaviSpacer2 );
os::File cInfoDownButtonFile( open_image_file( get_image_id() ) );
os::Resources cInfoDownButtonResources( &cInfoDownButtonFile );
os::ResStream* pcInfoDownButtonStream = cInfoDownButtonResources.GetResourceStream( "list-down.png" );
m_pcInfoDownButton = new os::ImageButton( os::Rect(), "InfoDownButton", "", new os::Message( M_INFO_BUTTON_MOVEDOWN ), new os::BitmapImage( pcInfoDownButtonStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcInfoDownButtonStream );
m_pcInfoNaviNode->AddChild( m_pcInfoDownButton, 0.000001 );
m_pcInfoNaviSpacer3 = new os::VLayoutSpacer( "InfoNaviSpacer3", 100.000000, 150.000000, NULL, 10.000000 );
m_pcInfoNaviNode->AddChild( m_pcInfoNaviSpacer3 );
os::File cInfoRemoveButtonFile( open_image_file( get_image_id() ) );
os::Resources cInfoRemoveButtonResources( &cInfoRemoveButtonFile );
os::ResStream* pcInfoRemoveButtonStream = cInfoRemoveButtonResources.GetResourceStream( "list-remove.png" );
m_pcInfoRemoveButton = new os::ImageButton( os::Rect(), "InfoRemoveButton", "", new os::Message( M_INFO_BUTTON_REMOVE ), new os::BitmapImage( pcInfoRemoveButtonStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcInfoRemoveButtonStream );
m_pcInfoNaviNode->AddChild( m_pcInfoRemoveButton, 0.000001 );
m_pcInfoNaviSpacer4 = new os::VLayoutSpacer( "InfoNaviSpacer4", 2.000000, 2.000000, NULL, 10.000000 );
m_pcInfoNaviNode->AddChild( m_pcInfoNaviSpacer4 );
os::File cInfoAddButtonFile( open_image_file( get_image_id() ) );
os::Resources cInfoAddButtonResources( &cInfoAddButtonFile );
os::ResStream* pcInfoAddButtonStream = cInfoAddButtonResources.GetResourceStream( "list-add.png" );
m_pcInfoAddButton = new os::ImageButton( os::Rect(), "InfoAddButton", "", new os::Message( M_INFO_BUTTON_ADD ), new os::BitmapImage( pcInfoAddButtonStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcInfoAddButtonStream );
m_pcInfoNaviNode->AddChild( m_pcInfoAddButton, 0.000001 );
m_pcInfoFrame->SetRoot( m_pcInfoFrameLayout );
m_pcNotesNode = new os::VLayoutNode( "NotesNode", 1.000000 );
m_pcNotesNode->SetBorders( os::Rect( 5.000000, 5.000000, 5.000000, 5.000000 ) );
m_pcNotesNodeLayout->AddChild( m_pcNotesNode );
m_pcNotesFrame = new os::FrameView( os::Rect(), "NotesFrame", "" );
m_pcNotesFrameLayout = new os::VLayoutNode( "NotesFrameLayout" );
m_pcNotesFrameLayout->SetBorders( os::Rect( 5.000000, 0.000000, 5.000000, 5.000000 ) );
m_pcNotesNode->AddChild( m_pcNotesFrame, 1.000000 );
m_pcNotes = new os::VLayoutNode( "Notes", 1.000000 );
m_pcNotes->SetBorders( os::Rect( 0.000000, 10.000000, 0.000000, 0.000000 ) );
m_pcNotesFrameLayout->AddChild( m_pcNotes );
m_pcNotesText = new os::TextView( os::Rect(), "NotesText", "" );
m_pcNotesText->SetMultiLine( true );
m_pcNotes->AddChild( m_pcNotesText, 1.000000 );
m_pcNotesFrame->SetRoot( m_pcNotesFrameLayout );
m_pcNameNodeTab->SetRoot( m_pcNameNodeLayout );
m_pcInfoNodeTab->SetRoot( m_pcInfoNodeLayout );
m_pcNotesNodeTab->SetRoot( m_pcNotesNodeLayout );
