/* Automatically generated by po2tbl.sed from tar.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"invalid argument `%s' for `%s'", 2},
  {"ambiguous argument `%s' for `%s'", 3},
  {"Valid arguments are:", 4},
  {"Unknown system error", 5},
  {"%s: option `%s' is ambiguous\n", 6},
  {"%s: option `--%s' doesn't allow an argument\n", 7},
  {"%s: option `%c%s' doesn't allow an argument\n", 8},
  {"%s: option `%s' requires an argument\n", 9},
  {"%s: unrecognized option `--%s'\n", 10},
  {"%s: unrecognized option `%c%s'\n", 11},
  {"%s: illegal option -- %c\n", 12},
  {"%s: invalid option -- %c\n", 13},
  {"%s: option requires an argument -- %c\n", 14},
  {"%s: option `-W %s' is ambiguous\n", 15},
  {"%s: option `-W %s' doesn't allow an argument\n", 16},
  {"Memory exhausted", 17},
  {"Arithmetic overflow", 18},
  {"Total bytes written: ", 19},
  {"Cannot close file #%d", 20},
  {"Cannot close descriptor %d", 21},
  {"Cannot properly duplicate %s", 22},
  {"Cannot use compressed or remote archives", 23},
  {"Cannot open pipe", 24},
  {"Cannot fork", 25},
  {"tar (child)", 26},
  {"(child) Pipe to stdin", 27},
  {"Cannot open archive %s", 28},
  {"Archive to stdout", 29},
  {"Cannot exec %s", 30},
  {"Child cannot fork", 31},
  {"((child)) Pipe to stdout", 32},
  {"tar (grandchild)", 33},
  {"(grandchild) Pipe to stdin", 34},
  {"Cannot read from compression program", 35},
  {"(child) Pipe to stdout", 36},
  {"Archive to stdin", 37},
  {"((child)) Pipe to stdin", 38},
  {"(grandchild) Pipe to stdout", 39},
  {"Cannot write to compression program", 40},
  {"Write to compression program short %lu bytes", 41},
  {"Invalid value for record_size", 42},
  {"No archive name given", 43},
  {"Could not allocate memory for blocking factor %d", 44},
  {"Cannot verify multi-volume archives", 45},
  {"Cannot use multi-volume compressed archives", 46},
  {"Cannot verify compressed archives", 47},
  {"Cannot update compressed archives", 48},
  {"Cannot verify stdin/stdout archive", 49},
  {"Cannot open %s", 50},
  {"Archive not labelled to match `%s'", 51},
  {"Volume `%s' does not match `%s'", 52},
  {"Write checkpoint %d", 53},
  {"Cannot write to %s", 54},
  {"Only wrote %lu of %lu bytes to %s", 55},
  {"Read error on %s", 56},
  {"At beginning of tape, quitting now", 57},
  {"Too many errors, quitting", 58},
  {"Read checkpoint %d", 59},
  {"Reading %s\n", 60},
  {"WARNING: No volume header", 61},
  {"%s is not continued on this volume", 62},
  {"%s is the wrong size (%s != %s + %s)", 63},
  {"This volume is out of sequence", 64},
  {"Record size = %lu blocks", 65},
  {"Archive %s EOF not on block boundary", 66},
  {"Only read %lu bytes from archive %s", 67},
  {"WARNING: Cannot close %s (%d, %d)", 68},
  {"Could not backspace archive file; it may be unreadable without -i", 69},
  {"WARNING: Cannot truncate %s", 70},
  {"Child died with signal %d%s", 71},
  {" (core dumped)", 72},
  {"Child returned status %d", 73},
  {"Prepare volume #%d for %s and hit return: ", 74},
  {"EOF where user reply was expected", 75},
  {"WARNING: Archive is incomplete", 76},
  {"\
 n [name]   Give a new file name for the next (and subsequent) volume(s)\n\
 q          Abort tar\n\
 !          Spawn a subshell\n\
 ?          Print this list\n", 77},
  {"No new volume; exiting.\n", 78},
  {"Cannot fork!", 79},
  {"Cannot exec a shell %s", 80},
  {"Could not allocate memory for diff buffer of %lu bytes", 81},
  {"Cannot read %s", 82},
  {"Could only read %lu of %lu bytes", 83},
  {"Data differs", 84},
  {"Unexpected EOF on archive file", 85},
  {"Cannot seek to %s in file %s", 86},
  {"File does not exist", 87},
  {"Cannot stat file %s", 88},
  {"Verify ", 89},
  {"Unknown file type '%c' for %s, diffed as normal file", 90},
  {"Not a regular file", 91},
  {"Mode differs", 92},
  {"Uid differs", 93},
  {"Gid differs", 94},
  {"Mod time differs", 95},
  {"Size differs", 96},
  {"Error while closing %s", 97},
  {"Does not exist", 98},
  {"Not linked to %s", 99},
  {"No such file or directory", 100},
  {"Cannot read link %s", 101},
  {"Symlink differs", 102},
  {"Device numbers changed", 103},
  {"Mode or device-type changed", 104},
  {"No longer a directory", 105},
  {"Cannot open file %s", 106},
  {"Could not rewind archive file for verify", 107},
  {"VERIFY FAILURE: %d invalid header(s) detected", 108},
  {"%s value %s too large (max=%s); substituting %s", 109},
  {"%s value %s too large (max=%s)", 110},
  {"Removing drive spec from names in the archive", 111},
  {"Removing leading `/' from absolute path names in the archive", 112},
  {"Wrote %s of %s bytes to file %s", 113},
  {"lseek error at byte %s in file %s", 114},
  {"Read error at byte %s, reading %lu bytes, in file %s", 115},
  {"File %s shrunk, padding with zeros", 116},
  {"Cannot add file %s", 117},
  {"%s: is unchanged; not dumped", 118},
  {"%s is the archive; not dumped", 119},
  {"Removing leading `/' from absolute links", 120},
  {"Cannot remove %s", 121},
  {"File %s shrunk by %s bytes, padding with zeros", 122},
  {"%s: file changed as we read it", 123},
  {"%s: close", 124},
  {"Cannot add directory %s", 125},
  {"%s: On a different filesystem; not dumped", 126},
  {"Cannot open directory %s", 127},
  {"File name %s%s too long", 128},
  {"%s: Unknown file type; file ignored", 129},
  {"Could not re-position archive file", 130},
  {"This does not look like a tar archive", 131},
  {"Skipping to next header", 132},
  {"Deleting non-header from archive", 133},
  {"%s: Cannot change mode to %04lo", 134},
  {"%s: Could not change access and modification times", 135},
  {"%s: Cannot lchown to uid %lu gid %lu", 136},
  {"%s: Cannot chown to uid %lu gid %lu", 137},
  {"%s: Cannot change owner to uid %lu, gid %lu", 138},
  {"%s: lseek error at byte %s", 139},
  {"%s: Could not write to file", 140},
  {"%s: Could only write %s of %s bytes", 141},
  {"%s: Was unable to backup this file", 142},
  {"Extracting contiguous files as regular files", 143},
  {"%s: Could not create file", 144},
  {"%s: Could only write %lu of %lu bytes", 145},
  {"%s: Error while closing", 146},
  {"%s: Could not create symlink to `%s'", 147},
  {"Attempting extraction of symbolic links as hard links", 148},
  {"%s: Could not link to `%s'", 149},
  {"%s: Could not make node", 150},
  {"%s: Could not make fifo", 151},
  {"%s: Could not create directory", 152},
  {"Added write and execute permission to directory %s", 153},
  {"Cannot extract `%s' -- file is continued from another volume", 154},
  {"Visible long name error", 155},
  {"Unknown file type '%c' for %s, extracted as normal file", 156},
  {"Cannot stat %s", 157},
  {"Directory %s has been renamed", 158},
  {"Directory %s is new", 159},
  {"Could not get current directory", 160},
  {"Could not get current directory: %s", 161},
  {"File name %s/%s too long", 162},
  {"Device number out of range", 163},
  {"Inode number out of range", 164},
  {"Cannot chdir to %s", 165},
  {"Unexpected EOF in archive", 166},
  {"%s: Deleting %s\n", 167},
  {"Error while deleting %s", 168},
  {"Omitting %s", 169},
  {"block %s: ** Block of NULs **\n", 170},
  {"block %s: ** End of File **\n", 171},
  {"Hmm, this doesn't look like a tar archive", 172},
  {"Skipping to next file header", 173},
  {"EOF in archive file", 174},
  {"Only wrote %lu of %lu bytes to file %s", 175},
  {"Blanks in header where octal %s value expected", 176},
  {"Header contains \"%.*s\" where octal %s value expected", 177},
  {"Octal value `%.*s' is out of range for %s", 178},
  {"block %s: ", 179},
  {"Visible longname error", 180},
  {" link to %s\n", 181},
  {" unknown file type `%c'\n", 182},
  {"--Volume Header--\n", 183},
  {"--Continued at byte %s--\n", 184},
  {"--Mangled file names--\n", 185},
  {"Creating directory:", 186},
  {"Unexpected EOF in mangled names", 187},
  {"Cannot rename %s to %s", 188},
  {"Renamed %s to %s", 189},
  {"Cannot symlink %s to %s", 190},
  {"Symlinked %s to %s", 191},
  {"Unknown demangling command %s", 192},
  {"Renaming previous `%s' to `%s'\n", 193},
  {"%s: Cannot rename for backup", 194},
  {"%s: Cannot rename from backup", 195},
  {"Renaming `%s' back to `%s'\n", 196},
  {"Cannot change to directory %s", 197},
  {"Missing file name after -C", 198},
  {"%s: Not found in archive", 199},
  {"rmtd: Cannot allocate buffer space\n", 200},
  {"Cannot allocate buffer space", 201},
  {"Seek offset out of range", 202},
  {"Seek direction out of range", 203},
  {"rmtd: Premature eof\n", 204},
  {"Premature end of file", 205},
  {"rmtd: Garbage command %c\n", 206},
  {"Garbage command", 207},
  {"exec/tcp: Service not available", 208},
  {"stdin", 209},
  {"stdout", 210},
  {"Cannot execute remote shell", 211},
  {"Options `-%s' and `-%s' both want standard input", 212},
  {"Cannot read confirmation from user", 213},
  {"Try `%s --help' for more information.\n", 214},
  {"\
GNU `tar' saves many files together into a single tape or disk archive, and\n\
can restore individual files from the archive.\n", 215},
  {"\
\n\
Usage: %s [OPTION]... [FILE]...\n", 216},
  {"\
\n\
If a long option shows an argument as mandatory, then it is mandatory\n\
for the equivalent short option also.  Similarly for optional arguments.\n", 217},
  {"\
\n\
Main operation mode:\n\
  -t, --list              list the contents of an archive\n\
  -x, --extract, --get    extract files from an archive\n\
  -c, --create            create a new archive\n\
  -d, --diff, --compare   find differences between archive and file system\n\
  -r, --append            append files to the end of an archive\n\
  -u, --update            only append files newer than copy in archive\n\
  -A, --catenate          append tar files to an archive\n\
      --concatenate       same as -A\n\
      --delete            delete from the archive (not on mag tapes!)\n", 218},
  {"\
\n\
Operation modifiers:\n\
  -W, --verify               attempt to verify the archive after writing it\n\
      --remove-files         remove files after adding them to the archive\n\
  -k, --keep-old-files       don't overwrite existing files when extracting\n\
  -U, --unlink-first         remove each file prior to extracting over it\n\
      --recursive-unlink     empty hierarchies prior to extracting \
directory\n\
  -S, --sparse               handle sparse files efficiently\n\
  -O, --to-stdout            extract files to standard output\n\
  -G, --incremental          handle old GNU-format incremental backup\n\
  -g, --listed-incremental   handle new GNU-format incremental backup\n\
      --ignore-failed-read   do not exit with nonzero on unreadable files\n", 219},
  {"\
\n\
Handling of file attributes:\n\
      --owner=NAME             force NAME as owner for added files\n\
      --group=NAME             force NAME as group for added files\n\
      --mode=CHANGES           force (symbolic) mode CHANGES for added \
files\n\
      --atime-preserve         don't change access times on dumped files\n\
  -m, --modification-time      don't extract file modified time\n\
      --same-owner             try extracting files with the same ownership\n\
      --numeric-owner          always use numbers for user/group names\n\
  -p, --same-permissions       extract all protection information\n\
      --preserve-permissions   same as -p\n\
  -s, --same-order             sort names to extract to match archive\n\
      --preserve-order         same as -s\n\
      --preserve               same as both -p and -s\n", 220},
  {"\
\n\
Device selection and switching:\n\
  -f, --file=ARCHIVE             use archive file or device ARCHIVE\n\
      --force-local              archive file is local even if has a colon\n\
      --rsh-command=COMMAND      use remote COMMAND instead of rsh\n\
  -[0-7][lmh]                    specify drive and density\n\
  -M, --multi-volume             create/list/extract multi-volume archive\n\
  -L, --tape-length=NUM          change tape after writing NUM x 1024 bytes\n\
  -F, --info-script=FILE         run script at end of each tape (implies \
-M)\n\
      --new-volume-script=FILE   same as -F FILE\n\
      --volno-file=FILE          use/update the volume number in FILE\n", 221},
  {"\
\n\
Device blocking:\n\
  -b, --blocking-factor=BLOCKS   BLOCKS x 512 bytes per record\n\
      --record-size=SIZE         SIZE bytes per record, multiple of 512\n\
  -i, --ignore-zeros             ignore zeroed blocks in archive (means \
EOF)\n\
  -B, --read-full-records        reblock as we read (for 4.2BSD pipes)\n", 222},
  {"\
\n\
Archive format selection:\n\
  -V, --label=NAME                   create archive with volume name NAME\n\
              PATTERN                at list/extract time, a globbing \
PATTERN\n\
  -o, --old-archive, --portability   write a V7 format archive\n\
      --posix                        write a POSIX conformant archive\n\
  -z, --gzip, --ungzip               filter the archive through gzip\n\
  -Z, --compress, --uncompress       filter the archive through compress\n\
      --use-compress-program=PROG    filter through PROG (must accept -d)\n", 223},
  {"\
\n\
Local file selection:\n\
  -C, --directory=DIR          change to directory DIR\n\
  -T, --files-from=NAME        get names to extract or create from file \
NAME\n\
      --null                   -T reads null-terminated names, disable -C\n\
      --exclude=PATTERN        exclude files, given as a globbing PATTERN\n\
  -X, --exclude-from=FILE      exclude globbing patterns listed in FILE\n\
  -P, --absolute-names         don't strip leading `/'s from file names\n\
  -h, --dereference            dump instead the files symlinks point to\n\
      --no-recursion           avoid descending automatically in \
directories\n\
  -l, --one-file-system        stay in local file system when creating \
archive\n\
  -K, --starting-file=NAME     begin at file NAME in the archive\n", 224},
  {"\
  -N, --newer=DATE             only store files newer than DATE\n\
      --newer-mtime            compare date and time when data changed only\n\
      --after-date=DATE        same as -N\n", 225},
  {"\
      --backup[=CONTROL]       backup before removal, choose version \
control\n\
      --suffix=SUFFIX          backup before removel, override usual suffix\n", 226},
  {"\
\n\
Informative output:\n\
      --help            print this help, then exit\n\
      --version         print tar program version number, then exit\n\
  -v, --verbose         verbosely list files processed\n\
      --checkpoint      print directory names while reading the archive\n\
      --totals          print total bytes written while creating archive\n\
  -R, --block-number    show block number within archive with each message\n\
  -w, --interactive     ask for confirmation for every action\n\
      --confirmation    same as -w\n", 227},
  {"\
\n\
The backup suffix is `~', unless set with --suffix or SIMPLE_BACKUP_SUFFIX.\n\
The version control may be set with --backup or VERSION_CONTROL, values \
are:\n\
\n\
  t, numbered     make numbered backups\n\
  nil, existing   numbered if numbered backups exist, simple otherwise\n\
  never, simple   always make simple backups\n", 228},
  {"\
\n\
GNU tar cannot read nor produce `--posix' archives.  If POSIXLY_CORRECT\n\
is set in the environment, GNU extensions are disallowed with `--posix'.\n\
Support for POSIX is only partially implemented, don't count on it yet.\n\
ARCHIVE may be FILE, HOST:FILE or USER@HOST:FILE; and FILE may be a file\n\
or a device.  *This* `tar' defaults to `-f%s -b%d'.\n", 229},
  {"\
\n\
Report bugs to <tar-bugs@gnu.org>.\n", 230},
  {"You may not specify more than one `-Acdtrux' option", 231},
  {"Conflicting compression options", 232},
  {"Old option `%c' requires an argument.", 233},
  {"Obsolete option, now implied by --blocking-factor", 234},
  {"Obsolete option name replaced by --blocking-factor", 235},
  {"Invalid blocking factor", 236},
  {"Obsolete option name replaced by --read-full-records", 237},
  {"Invalid tape length", 238},
  {"Obsolete option name replaced by --touch", 239},
  {"More than one threshold date", 240},
  {"Invalid date format `%s'", 241},
  {"Conflicting archive format options", 242},
  {"Obsolete option name replaced by --absolute-names", 243},
  {"Obsolete option name replaced by --block-number", 244},
  {"Obsolete option name replaced by --backup", 245},
  {"Invalid group given on option", 246},
  {"Invalid mode given on option", 247},
  {"Invalid owner given on option", 248},
  {"Invalid record size", 249},
  {"Record size must be a multiple of %d.", 250},
  {"Options `-[0-7][lmh]' not supported by *this* tar", 251},
  {"\
\n\
Copyright (C) 1988, 92,93,94,95,96,97,98, 1999 Free Software Foundation, \
Inc.\n", 252},
  {"\
This is free software; see the source for copying conditions.  There is NO\n\
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n", 253},
  {"\
\n\
Written by John Gilmore and Jay Fenlason.\n", 254},
  {"GNU features wanted on incompatible archive format", 255},
  {"Multiple archive files requires `-M' option", 256},
  {"Cowardly refusing to create an empty archive", 257},
  {"Options `-Aru' are incompatible with `-f -'", 258},
  {"You must specify one of the `-Acdtrux' options", 259},
  {"Error exit delayed from previous errors", 260},
  {"Read error at byte %s reading %lu bytes in file %s", 261},
  {"%s: File shrunk by %s bytes, (yark!)", 262},
  {"Generate data files for GNU tar test suite.\n", 263},
  {"\
\n\
Usage: %s [OPTION]...\n", 264},
  {"\
If a long option shows an argument as mandatory, then it is mandatory\n\
for the equivalent short option also.\n\
\n\
  -l, --file-length=LENGTH   LENGTH of generated file\n\
  -p, --pattern=PATTERN      PATTERN is `default' or `zeros'\n\
      --help                 display this help and exit\n\
      --version              output version information and exit\n", 265},
  {"Ambiguous pattern `%s'", 266},
  {"Unknown pattern `%s'", 267},
  {"\
\n\
Copyright (C) 1995, 1996, 1997 Free Software Foundation, Inc.\n", 268},
  {"\
\n\
Written by François Pinard <pinard@iro.umontreal.ca>.\n", 269},
};

int _msg_tbl_length = 269;
