name				:= LibAtheOS-3
package				:= $(name).zip
system-libs-path	:= /system/libs
install-path		:= $(system-libs-path)
distro-path			:= $(DIST_DIR)/atheos/sys/libs

.PHONY: all deps clean install dist

all:

deps:

clean:

install:
	unzip $(package) -d $(install-path)

dist:
	unzip $(package) -d $(distro-path)

