SUBDIRS= Albert DiskManager aclock aedit archiver aterm aview cpumon crypt debug desktop fsutils guiprefs keymapconv launcher_1.1 locator_0.2 memmon mixer nettools pkgmanager rescopy systools users-1.0.1b NetworkPreferences
include $(ATHEOS_SRC)/recurse.rules

