SUBDIRS= DiskManager aterm cpumon crypt debug desktop fsutils guiprefs keymapconv memmon nettools rescopy systools pkgmanager users-1.0.1b aview Albert locator_0.2 
include $(ATHEOS_SRC)/recurse.rules

