#ifndef __F_CAT_libsyllable_H__
#define __F_CAT_libsyllable_H__
#include <util/catalog.h>
#ifndef CATALOG_NO_IDS
#define ID_MSG_FILEREQUESTER_LOAD_BUTTON 1000
#define ID_MSG_FILEREQUESTER_SAVE_BUTTON 1001
#define ID_MSG_FILEREQUESTER_CANCEL_BUTTON 1002
#define ID_MSG_FILEREQUESTER_FILE_NAME_LABEL 1003
#define ID_MSG_FILEREQUESTER_BROWSE_LOCATION_LABEL 1004
#define ID_MSG_FILEREQUESTER_FILE_ALREADY_EXISTS_TEXT 1005
#define ID_MSG_FILEREQUESTER_FILE_ALREADY_EXISTS_TITLE 1006
#define ID_MSG_FILEREQUESTER_FILE_ALREADY_EXISTS_YES_BUTTON 1007
#define ID_MSG_FILEREQUESTER_FILE_ALREADY_EXISTS_NO_BUTTON 1008
#define ID_MSG_ICONDIRVIEW_WINDOW_OPEN_WITH 2000
#define ID_MSG_ICONDIRVIEW_NUMBER_OF_OBJECTS_SELECTED 2001
#define ID_MSG_ICONDIRVIEW_MENU_MOUNT 2002
#define ID_MSG_ICONDIRVIEW_MENU_UNMOUNT 2003
#define ID_MSG_ICONDIRVIEW_MENU_NEW_DIRECTORY 2004
#define ID_MSG_ICONDIRVIEW_MENU_EMPTY_TRASH 2005
#define ID_MSG_ICONDIRVIEW_MENU_OPEN_WITH 2006
#define ID_MSG_ICONDIRVIEW_MENU_INFO 2007
#define ID_MSG_ICONDIRVIEW_MENU_RENAME 2008
#define ID_MSG_ICONDIRVIEW_MENU_MOVE_TO_TRASH 2009
#define ID_MSG_ICONDIRVIEW_MENU_DELETE 2010
#define ID_MSG_ICONDIRVIEW_PERCENT_FREE 2011
#define ID_MSG_ICONDIRVIEW_VOLUMENAME_UNKNOWN 2012
#define ID_MSG_FILEINFO_WINDOW_TITLE 3000
#define ID_MSG_FILEINFO_WINDOW_NAME_LABEL 3001
#define ID_MSG_FILEINFO_WINDOW_PATH_LABEL 3002
#define ID_MSG_FILEINFO_WINDOW_SIZE_LABEL 3003
#define ID_MSG_FILEINFO_WINDOW_MODIFIEDDATE_LABEL 3004
#define ID_MSG_FILEINFO_WINDOW_FILETYPE_LABEL 3005
#define ID_MSG_FILEINFO_WINDOW_FILETYPE_DROPDOWN_CURRENT_LABEL 3006
#define ID_MSG_FILEINFO_WINDOW_FILETYPE_DROPDOWN_EXECUTABLE 3007
#define ID_MSG_FILEINFO_WINDOW_OK_BUTTON 3008
#define ID_MSG_FILEINFO_FILESIZE_ZERO 3009
#define ID_MSG_FILEINFO_FILETYPE_UNKNOWN 3010
#define ID_MSG_RENAMEFILE_WINDOW_TITLE 4000
#define ID_MSG_RENAMEFILE_WINDOW_OK_BUTTON 4001
#define ID_MSG_RENAMEFILE_ERROR_TITLE 4002
#define ID_MSG_RENAMEFILE_ERROR_TEXT 4003
#define ID_MSG_RENAMEFILE_ERROR_CLOSE 4004
#define ID_MSG_NEWDIR_WINDOW_TITLE 5000
#define ID_MSG_NEWDIR_WINDOW_OK_BUTTON 5001
#define ID_MSG_NEWDIR_ERROR_TITLE 5002
#define ID_MSG_NEWDIR_ERROR_TEXT 5003
#define ID_MSG_NEWDIR_ERROR_CLOSE 5004
#define ID_MSG_MOUNT_WINDOW_TITLE 6000
#define ID_MSG_MOUNT_WINDOW_NAME_COLUMN 6001
#define ID_MSG_MOUNT_WINDOW_PATH_COLUMN 6002
#define ID_MSG_MOUNT_WINDOW_MOUNT_BUTTON 6003
#define ID_MSG_MOUNT_SCANNING_PATH 6004
#define ID_MSG_MOUNT_SCANNING 6005
#define ID_MSG_MOUNT_LOCAL_DISKS_LABEL 6006
#define ID_MSG_MOUNT_TYPE_HARDDISK 6007
#define ID_MSG_MOUNT_TYPE_CD_DVD 6008
#define ID_MSG_MOUNT_TYPE_FLOPPY 6009
#define ID_MSG_MOUNT_DEVICE_PARTITION 6010
#define ID_MSG_MOUNT_ERROR_TITLE 6011
#define ID_MSG_MOUNT_ERROR_CLOSE 6012
#define ID_MSG_MOUNT_ERROR_CREATE_MOUNTPOINT 6013
#define ID_MSG_MOUNT_ERROR_OTHER_ERROR 6014
#define ID_MSG_MOUNT_ERROR_UNMOUNT 6015
#endif
#ifndef CATALOG_NO_LSTRINGS
#define MSG_FILEREQUESTER_LOAD_BUTTON os::LString( 1000 )
#define MSG_FILEREQUESTER_SAVE_BUTTON os::LString( 1001 )
#define MSG_FILEREQUESTER_CANCEL_BUTTON os::LString( 1002 )
#define MSG_FILEREQUESTER_FILE_NAME_LABEL os::LString( 1003 )
#define MSG_FILEREQUESTER_BROWSE_LOCATION_LABEL os::LString( 1004 )
#define MSG_FILEREQUESTER_FILE_ALREADY_EXISTS_TEXT os::LString( 1005 )
#define MSG_FILEREQUESTER_FILE_ALREADY_EXISTS_TITLE os::LString( 1006 )
#define MSG_FILEREQUESTER_FILE_ALREADY_EXISTS_YES_BUTTON os::LString( 1007 )
#define MSG_FILEREQUESTER_FILE_ALREADY_EXISTS_NO_BUTTON os::LString( 1008 )
#define MSG_ICONDIRVIEW_WINDOW_OPEN_WITH os::LString( 2000 )
#define MSG_ICONDIRVIEW_NUMBER_OF_OBJECTS_SELECTED os::LString( 2001 )
#define MSG_ICONDIRVIEW_MENU_MOUNT os::LString( 2002 )
#define MSG_ICONDIRVIEW_MENU_UNMOUNT os::LString( 2003 )
#define MSG_ICONDIRVIEW_MENU_NEW_DIRECTORY os::LString( 2004 )
#define MSG_ICONDIRVIEW_MENU_EMPTY_TRASH os::LString( 2005 )
#define MSG_ICONDIRVIEW_MENU_OPEN_WITH os::LString( 2006 )
#define MSG_ICONDIRVIEW_MENU_INFO os::LString( 2007 )
#define MSG_ICONDIRVIEW_MENU_RENAME os::LString( 2008 )
#define MSG_ICONDIRVIEW_MENU_MOVE_TO_TRASH os::LString( 2009 )
#define MSG_ICONDIRVIEW_MENU_DELETE os::LString( 2010 )
#define MSG_ICONDIRVIEW_PERCENT_FREE os::LString( 2011 )
#define MSG_ICONDIRVIEW_VOLUMENAME_UNKNOWN os::LString( 2012 )
#define MSG_FILEINFO_WINDOW_TITLE os::LString( 3000 )
#define MSG_FILEINFO_WINDOW_NAME_LABEL os::LString( 3001 )
#define MSG_FILEINFO_WINDOW_PATH_LABEL os::LString( 3002 )
#define MSG_FILEINFO_WINDOW_SIZE_LABEL os::LString( 3003 )
#define MSG_FILEINFO_WINDOW_MODIFIEDDATE_LABEL os::LString( 3004 )
#define MSG_FILEINFO_WINDOW_FILETYPE_LABEL os::LString( 3005 )
#define MSG_FILEINFO_WINDOW_FILETYPE_DROPDOWN_CURRENT_LABEL os::LString( 3006 )
#define MSG_FILEINFO_WINDOW_FILETYPE_DROPDOWN_EXECUTABLE os::LString( 3007 )
#define MSG_FILEINFO_WINDOW_OK_BUTTON os::LString( 3008 )
#define MSG_FILEINFO_FILESIZE_ZERO os::LString( 3009 )
#define MSG_FILEINFO_FILETYPE_UNKNOWN os::LString( 3010 )
#define MSG_RENAMEFILE_WINDOW_TITLE os::LString( 4000 )
#define MSG_RENAMEFILE_WINDOW_OK_BUTTON os::LString( 4001 )
#define MSG_RENAMEFILE_ERROR_TITLE os::LString( 4002 )
#define MSG_RENAMEFILE_ERROR_TEXT os::LString( 4003 )
#define MSG_RENAMEFILE_ERROR_CLOSE os::LString( 4004 )
#define MSG_NEWDIR_WINDOW_TITLE os::LString( 5000 )
#define MSG_NEWDIR_WINDOW_OK_BUTTON os::LString( 5001 )
#define MSG_NEWDIR_ERROR_TITLE os::LString( 5002 )
#define MSG_NEWDIR_ERROR_TEXT os::LString( 5003 )
#define MSG_NEWDIR_ERROR_CLOSE os::LString( 5004 )
#define MSG_MOUNT_WINDOW_TITLE os::LString( 6000 )
#define MSG_MOUNT_WINDOW_NAME_COLUMN os::LString( 6001 )
#define MSG_MOUNT_WINDOW_PATH_COLUMN os::LString( 6002 )
#define MSG_MOUNT_WINDOW_MOUNT_BUTTON os::LString( 6003 )
#define MSG_MOUNT_SCANNING_PATH os::LString( 6004 )
#define MSG_MOUNT_SCANNING os::LString( 6005 )
#define MSG_MOUNT_LOCAL_DISKS_LABEL os::LString( 6006 )
#define MSG_MOUNT_TYPE_HARDDISK os::LString( 6007 )
#define MSG_MOUNT_TYPE_CD_DVD os::LString( 6008 )
#define MSG_MOUNT_TYPE_FLOPPY os::LString( 6009 )
#define MSG_MOUNT_DEVICE_PARTITION os::LString( 6010 )
#define MSG_MOUNT_ERROR_TITLE os::LString( 6011 )
#define MSG_MOUNT_ERROR_CLOSE os::LString( 6012 )
#define MSG_MOUNT_ERROR_CREATE_MOUNTPOINT os::LString( 6013 )
#define MSG_MOUNT_ERROR_OTHER_ERROR os::LString( 6014 )
#define MSG_MOUNT_ERROR_UNMOUNT os::LString( 6015 )
#endif
#endif /* __F_CAT_libsyllable_H__ */
