m_pcRoot = new os::VLayoutNode( "Root" );
m_pcVRoot = new os::VLayoutNode( "VRoot", 1.000000 );
m_pcVRoot->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcRoot->AddChild( m_pcVRoot );
m_pcMenuNode = new os::VLayoutNode( "MenuNode", 1.000000 );
m_pcMenuNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcVRoot->AddChild( m_pcMenuNode );
m_pcMenu = new os::Menu( os::Rect(), "Menu", os::ITEMS_IN_ROW );
os::Menu* pcMenuApplicationMenu = new os::Menu( os::Rect(), "Application", os::ITEMS_IN_COLUMN );
pcMenuApplicationMenu->AddItem( "Quit", new Message( M_MENU_QUIT ) );
pcMenuApplicationMenu->AddItem( new MenuSeparator() );
pcMenuApplicationMenu->AddItem( "Help...", new Message( M_MENU_HELP ) );
pcMenuApplicationMenu->AddItem( "Website...", new Message( M_MENU_WEB ) );
pcMenuApplicationMenu->AddItem( new MenuSeparator() );
pcMenuApplicationMenu->AddItem( "About...", new Message( M_MENU_ABOUT ) );
m_pcMenu->AddItem( pcMenuApplicationMenu );
os::Menu* pcMenuMediatypeMenu = new os::Menu( os::Rect(), "Media type", os::ITEMS_IN_COLUMN );
m_pcMenuMediatypeCD = new CheckMenu( "CD", new Message( M_MENU_MEDIA_CD ), bDummy );
pcMenuMediatypeMenu->AddItem( m_pcMenuMediatypeCD );
m_pcMenuMediatypeDVD = new CheckMenu( "DVD", new Message( M_MENU_MEDIA_DVD ), bDummy );
// pcMenuMediatypeMenu->AddItem( m_pcMenuMediatypeDVD );
m_pcMenuMediatypeHDDVD = new CheckMenu( "HD-DVD", new Message( M_MENU_MEDIA_HDDVD ), bDummy );
// pcMenuMediatypeMenu->AddItem( m_pcMenuMediatypeHDDVD );
m_pcMenuMediatypeBLURAY = new CheckMenu( "Blu-ray", new Message( M_MENU_MEDIA_BLURAY ), bDummy );
// pcMenuMediatypeMenu->AddItem( m_pcMenuMediatypeBLURAY );
m_pcMenu->AddItem( pcMenuMediatypeMenu );
os::Menu* pcMenuEraseMenu = new os::Menu( os::Rect(), "Erase", os::ITEMS_IN_COLUMN );
pcMenuEraseMenu->AddItem( "Fast Erase", new Message( M_MENU_ERASE_FAST ) );
pcMenuEraseMenu->AddItem( "Full Erase", new Message( M_MENU_ERASE_FULL ) );
m_pcMenu->AddItem( pcMenuEraseMenu );
os::Menu* pcMenuSettingsMenu = new os::Menu( os::Rect(), "Settings", os::ITEMS_IN_COLUMN );
pcMenuSettingsMenu->AddItem( "Save settings now", new Message( M_MENU_SETTINGS_SAVENOW ) );
m_pcMenuSaveOnExit = new CheckMenu( "Save settings on exit", new Message( M_MENU_SETTINGS_SAVEONEXIT ), bDummy );
pcMenuSettingsMenu->AddItem( m_pcMenuSaveOnExit );
m_pcMenu->AddItem( pcMenuSettingsMenu );
m_pcMenu->SetTargetForItems(this);
m_pcMenuNode->AddChild( m_pcMenu, 1.000000 );
m_pcMainNode = new os::HLayoutNode( "MainNode", 1.000000 );
m_pcMainNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcVRoot->AddChild( m_pcMainNode );
m_pcSideMenu = new os::VLayoutNode( "SideMenu", 0.000001 );
m_pcSideMenu->SetBorders( os::Rect( 5.000000, 5.000000, 5.000000, 5.000000 ) );
m_pcMainNode->AddChild( m_pcSideMenu );
m_pcSideMenuFrame = new os::FrameView( os::Rect(), "SideMenuFrame", "" );
m_pcSideMenuFrameLayout = new os::VLayoutNode( "SideMenuFrameLayout" );
m_pcSideMenuFrameLayout->SetBorders( os::Rect( 5.000000, 5.000000, 5.000000, 0.000000 ) );
m_pcSideMenu->AddChild( m_pcSideMenuFrame, 1.000000 );
os::File cSideMenuBurnFile( open_image_file( get_image_id() ) );
os::Resources cSideMenuBurnResources( &cSideMenuBurnFile );
os::ResStream* pcSideMenuBurnStream = cSideMenuBurnResources.GetResourceStream( "menu-burn.png" );
m_pcSideMenuBurn = new os::ImageButton( os::Rect(), "SideMenuBurn", "Burn CD", new os::Message( M_SIDEMENU_BURN ), new os::BitmapImage( pcSideMenuBurnStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcSideMenuBurnStream );
m_pcSideMenuFrameLayout->AddChild( m_pcSideMenuBurn, 0.000001 );
m_pcSideMenuSpacer1 = new os::VLayoutSpacer( "SideMenuSpacer1", 10.000000, 10.000000, NULL, 1.000000 );
m_pcSideMenuFrameLayout->AddChild( m_pcSideMenuSpacer1 );
os::File cSideMenuDataFile( open_image_file( get_image_id() ) );
os::Resources cSideMenuDataResources( &cSideMenuDataFile );
os::ResStream* pcSideMenuDataStream = cSideMenuDataResources.GetResourceStream( "menu-data.png" );
m_pcSideMenuData = new os::ImageButton( os::Rect(), "SideMenuData", "Data CD", new os::Message( M_SIDEMENU_DATA ), new os::BitmapImage( pcSideMenuDataStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcSideMenuDataStream );
m_pcSideMenuFrameLayout->AddChild( m_pcSideMenuData, 0.000001 );
m_pcSideMenuSpacer2 = new os::VLayoutSpacer( "SideMenuSpacer2", 10.000000, 10.000000, NULL, 1.000000 );
m_pcSideMenuFrameLayout->AddChild( m_pcSideMenuSpacer2 );
os::File cSideMenuAudioFile( open_image_file( get_image_id() ) );
os::Resources cSideMenuAudioResources( &cSideMenuAudioFile );
os::ResStream* pcSideMenuAudioStream = cSideMenuAudioResources.GetResourceStream( "menu-audio.png" );
m_pcSideMenuAudio = new os::ImageButton( os::Rect(), "SideMenuAudio", "Audio CD", new os::Message( M_SIDEMENU_AUDIO ), new os::BitmapImage( pcSideMenuAudioStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcSideMenuAudioStream );
m_pcSideMenuFrameLayout->AddChild( m_pcSideMenuAudio, 0.000001 );
m_pcSideMenuSpacer3 = new os::VLayoutSpacer( "SideMenuSpacer3", 10.000000, 10.000000, NULL, 1.000000 );
m_pcSideMenuFrameLayout->AddChild( m_pcSideMenuSpacer3 );
os::File cSideMenuVideoFile( open_image_file( get_image_id() ) );
os::Resources cSideMenuVideoResources( &cSideMenuVideoFile );
os::ResStream* pcSideMenuVideoStream = cSideMenuVideoResources.GetResourceStream( "menu-video.png" );
m_pcSideMenuVideo = new os::ImageButton( os::Rect(), "SideMenuVideo", "Video CD", new os::Message( M_SIDEMENU_VIDEO ), new os::BitmapImage( pcSideMenuVideoStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcSideMenuVideoStream );
// m_pcSideMenuFrameLayout->AddChild( m_pcSideMenuVideo, 0.000001 );
m_pcSideMenuSpacer4 = new os::VLayoutSpacer( "SideMenuSpacer4", 10.000000, 10.000000, NULL, 1.000000 );
//m_pcSideMenuFrameLayout->AddChild( m_pcSideMenuSpacer4 );
os::File cSideMenuBackupFile( open_image_file( get_image_id() ) );
os::Resources cSideMenuBackupResources( &cSideMenuBackupFile );
os::ResStream* pcSideMenuBackupStream = cSideMenuBackupResources.GetResourceStream( "menu-backup.png" );
m_pcSideMenuBackup = new os::ImageButton( os::Rect(), "SideMenuBackup", "Backup", new os::Message( M_SIDEMENU_BACKUP ), new os::BitmapImage( pcSideMenuBackupStream ), os::ImageButton::IB_TEXT_BOTTOM, true, true, true );
delete( pcSideMenuBackupStream );
m_pcSideMenuFrameLayout->AddChild( m_pcSideMenuBackup, 0.000001 );
m_pcSideMenuSpacer5 = new os::VLayoutSpacer( "SideMenuSpacer5", 0.000000, 100000.000000, NULL, 1.000000 );
m_pcSideMenuFrameLayout->AddChild( m_pcSideMenuSpacer5 );
m_pcSideMenuFrame->SetRoot( m_pcSideMenuFrameLayout );

m_pcViewMain = new os::VLayoutNode( "ViewMain", 1.000000 );
m_pcViewMain->AddChild(pcMainView = new os::LayoutView( GetBounds(), "layout_main" ));
m_pcViewMain->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcMainNode->AddChild( m_pcViewMain );

m_pcVersion = new os::VLayoutNode( "Version", 1.000000 );
m_pcVersion->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
os::File cLogoFile( open_image_file( get_image_id() ) );
os::Resources cLogoResources( &cLogoFile );
os::ResStream* pcLogoStream = cLogoResources.GetResourceStream( "logo.png" );
m_pcLogo = new os::ImageView( os::Rect(), "Logo", new os::BitmapImage( pcLogoStream ) );
delete( pcLogoStream );
m_pcVersion->AddChild( m_pcLogo, 1.000000 );
m_pcVersionSpacerTop = new os::VLayoutSpacer( "VersionSpacerTop", 0.000000, 100000.000000, NULL, 1.000000 );
m_pcVersion->AddChild( m_pcVersionSpacerTop );
m_pcVersionNode = new os::HLayoutNode( "VersionNode", 1.000000 );
m_pcVersionNode->SetBorders( os::Rect( 0.000000, 0.000000, 0.000000, 0.000000 ) );
m_pcVersion->AddChild( m_pcVersionNode );
m_pcVersionSpacerLeft = new os::HLayoutSpacer( "VersionSpacerLeft", 0.000000, 100000.000000, NULL, 1.000000 );
m_pcVersionNode->AddChild( m_pcVersionSpacerLeft );
m_pcVersionString = new os::StringView( os::Rect(), "VersionString", "Version 0.4" );
m_pcVersionNode->AddChild( m_pcVersionString, 1.000000 );
m_pcVersionSpacerBottom = new os::VLayoutSpacer( "VersionSpacerBottom", 0.000000, 100000.000000, NULL, 1.000000 );
m_pcVersion->AddChild( m_pcVersionSpacerBottom );

pcMainView->SetRoot( m_pcVersion );

