#ifndef __F_CAT_xpdf_H__
#define __F_CAT_xpdf_H__
#include <util/catalog.h>
#ifndef CATALOG_NO_IDS
#define ID_MSG_MAINWND_TITLE 100
#define ID_MSG_MAINWND_MENU_APPLICATION 200
#define ID_MSG_MAINWND_MENU_APPLICATION_ABOUT 201
#define ID_MSG_MAINWND_MENU_APPLICATION_QUIT 202
#define ID_MSG_MAINWND_MENU_FILE 300
#define ID_MSG_MAINWND_MENU_FILE_OPEN 301
#define ID_MSG_MAINWND_MENU_PAGE 400
#define ID_MSG_MAINWND_MENU_PAGE_PREV 401
#define ID_MSG_MAINWND_MENU_PAGE_NEXT 402
#define ID_MSG_MAINWND_MENU_ZOOM_PAGE 403
#define ID_MSG_MAINWND_MENU_ZOOM_WIDTH 404
#define ID_MSG_MAINWND_MENU_EDIT 500
#define ID_MSG_MAINWND_MENU_EDIT_COPY 501
#define ID_MSG_MAINWND_MENU_EDIT_FIND 502
#define ID_MSG_STATUS_PAGE 1000
#define ID_MSG_STATUS_PAGE_OF 1001
#define ID_MSG_ERRWND_CANTOPEN 2000
#endif
#ifndef CATALOG_NO_LSTRINGS
#define MSG_MAINWND_TITLE os::LString( 100 )
#define MSG_MAINWND_MENU_APPLICATION os::LString( 200 )
#define MSG_MAINWND_MENU_APPLICATION_ABOUT os::LString( 201 )
#define MSG_MAINWND_MENU_APPLICATION_QUIT os::LString( 202 )
#define MSG_MAINWND_MENU_FILE os::LString( 300 )
#define MSG_MAINWND_MENU_FILE_OPEN os::LString( 301 )
#define MSG_MAINWND_MENU_PAGE os::LString( 400 )
#define MSG_MAINWND_MENU_PAGE_PREV os::LString( 401 )
#define MSG_MAINWND_MENU_PAGE_NEXT os::LString( 402 )
#define MSG_MAINWND_MENU_ZOOM_PAGE os::LString( 403 )
#define MSG_MAINWND_MENU_ZOOM_WIDTH os::LString( 404 )
#define MSG_MAINWND_MENU_EDIT os::LString( 500 )
#define MSG_MAINWND_MENU_EDIT_COPY os::LString( 501 )
#define MSG_MAINWND_MENU_EDIT_FIND os::LString( 502 )
#define MSG_STATUS_PAGE os::LString( 1000 )
#define MSG_STATUS_PAGE_OF os::LString( 1001 )
#define MSG_ERRWND_CANTOPEN os::LString( 2000 )
#endif
#endif /* __F_CAT_xpdf_H__ */
