#ifndef __F_CAT_coldfish_H__
#define __F_CAT_coldfish_H__
#include <util/catalog.h>
#ifndef CATALOG_NO_IDS
#define ID_MSG_MAINWND_TITLE 100
#define ID_MSG_MAINWND_PLAY 101
#define ID_MSG_MAINWND_STOP 102
#define ID_MSG_MAINWND_PAUSE 103
#define ID_MSG_MAINWND_PLAYLIST 104
#define ID_MSG_MAINWND_FILE 105
#define ID_MSG_MAINWND_TRACK 106
#define ID_MSG_MAINWND_STREAM 107
#define ID_MSG_MAINWND_LENGTH 108
#define ID_MSG_MAINWND_MENU_APPLICATION 200
#define ID_MSG_MAINWND_MENU_APPLICATION_ABOUT 201
#define ID_MSG_MAINWND_MENU_APPLICATION_QUIT 202
#define ID_MSG_MAINWND_MENU_PLAYLIST 300
#define ID_MSG_MAINWND_MENU_PLAYLIST_SELECT 301
#define ID_MSG_MAINWND_MENU_PLAYLIST_INPUT 302
#define ID_MSG_MAINWND_MENU_FILE 400
#define ID_MSG_MAINWND_MENU_FILE_ADD 401
#define ID_MSG_MAINWND_MENU_FILE_REMOVE 402
#define ID_MSG_MAINWND_MENU_VIEW 500
#define ID_MSG_MAINWND_MENU_VIEW_PLAYLIST 501
#define ID_MSG_ABOUTWND_TITLE 1000
#define ID_MSG_ABOUTWND_TEXT 1001
#define ID_MSG_ABOUTWND_OK 1002
#define ID_MSG_ERRWND_TITLE 1100
#define ID_MSG_ERRWND_OK 1101
#define ID_MSG_ERRWND_CANTPLAY 1102
#define ID_MSG_ERRWND_CANTDELETE 1103
#define ID_MSG_ERRWND_NOTPLAYLIST 1104
#define ID_MSG_PLAYLIST_UNKNOWN 2000
#define ID_MSG_PLAYLISTWND_TITLE 2100
#define ID_MSG_PLAYLISTWND_FILE 2101
#define ID_MSG_PLAYLISTWND_OPEN 2102
#define ID_MSG_PLAYLISTWND_NOTE 2103
#define ID_MSG_LCD_TRACK 3000
#endif
#ifndef CATALOG_NO_LSTRINGS
#define MSG_MAINWND_TITLE os::LString( 100 )
#define MSG_MAINWND_PLAY os::LString( 101 )
#define MSG_MAINWND_STOP os::LString( 102 )
#define MSG_MAINWND_PAUSE os::LString( 103 )
#define MSG_MAINWND_PLAYLIST os::LString( 104 )
#define MSG_MAINWND_FILE os::LString( 105 )
#define MSG_MAINWND_TRACK os::LString( 106 )
#define MSG_MAINWND_STREAM os::LString( 107 )
#define MSG_MAINWND_LENGTH os::LString( 108 )
#define MSG_MAINWND_MENU_APPLICATION os::LString( 200 )
#define MSG_MAINWND_MENU_APPLICATION_ABOUT os::LString( 201 )
#define MSG_MAINWND_MENU_APPLICATION_QUIT os::LString( 202 )
#define MSG_MAINWND_MENU_PLAYLIST os::LString( 300 )
#define MSG_MAINWND_MENU_PLAYLIST_SELECT os::LString( 301 )
#define MSG_MAINWND_MENU_PLAYLIST_INPUT os::LString( 302 )
#define MSG_MAINWND_MENU_FILE os::LString( 400 )
#define MSG_MAINWND_MENU_FILE_ADD os::LString( 401 )
#define MSG_MAINWND_MENU_FILE_REMOVE os::LString( 402 )
#define MSG_MAINWND_MENU_VIEW os::LString( 500 )
#define MSG_MAINWND_MENU_VIEW_PLAYLIST os::LString( 501 )
#define MSG_ABOUTWND_TITLE os::LString( 1000 )
#define MSG_ABOUTWND_TEXT os::LString( 1001 )
#define MSG_ABOUTWND_OK os::LString( 1002 )
#define MSG_ERRWND_TITLE os::LString( 1100 )
#define MSG_ERRWND_OK os::LString( 1101 )
#define MSG_ERRWND_CANTPLAY os::LString( 1102 )
#define MSG_ERRWND_CANTDELETE os::LString( 1103 )
#define MSG_ERRWND_NOTPLAYLIST os::LString( 1104 )
#define MSG_PLAYLIST_UNKNOWN os::LString( 2000 )
#define MSG_PLAYLISTWND_TITLE os::LString( 2100 )
#define MSG_PLAYLISTWND_FILE os::LString( 2101 )
#define MSG_PLAYLISTWND_OPEN os::LString( 2102 )
#define MSG_PLAYLISTWND_NOTE os::LString( 2103 )
#define MSG_LCD_TRACK os::LString( 3000 )
#endif
#endif /* __F_CAT_coldfish_H__ */
