//
// This header file was generated by CatFish.
// Do not edit by hand.
//

#ifndef __F_CAT__boot_cvsroot_syllable_system_apps_utils_Preferences_Locale_catalog_H__
#define __F_CAT__boot_cvsroot_syllable_system_apps_utils_Preferences_Locale_catalog_H__
#include <util/catalog.h>
#ifndef CATALOG_NO_IDS
#define ID_STR_MAIN_TITLE                                    1000
#define ID_STR_MAIN_APPLY                                    1001
#define ID_STR_MAIN_REVERT                                   1002
#define ID_STR_MAIN_DEFAULT                                  1003
#define ID_STR_MAIN_LANGUAGE_TAB                             1100
#define ID_STR_MAIN_LANGUAGE_ACTIVATE                        1101
#define ID_STR_MAIN_LANGUAGE_DEACTIVATE                      1102
#define ID_STR_MAIN_LANGUAGE_AVAILABLE                       1103
#define ID_STR_MAIN_LANGUAGE_USED                            1104
#define ID_STR_MAIN_COUNTRY_TAB                              1200
#define ID_STR_ERROR_SAVE                                    2000
#endif // CATALOG_NO_IDS
#ifndef CATALOG_NO_LSTRINGS
#define STR_MAIN_TITLE                                    os::LString( 1000 )
#define STR_MAIN_APPLY                                    os::LString( 1001 )
#define STR_MAIN_REVERT                                   os::LString( 1002 )
#define STR_MAIN_DEFAULT                                  os::LString( 1003 )
#define STR_MAIN_LANGUAGE_TAB                             os::LString( 1100 )
#define STR_MAIN_LANGUAGE_ACTIVATE                        os::LString( 1101 )
#define STR_MAIN_LANGUAGE_DEACTIVATE                      os::LString( 1102 )
#define STR_MAIN_LANGUAGE_AVAILABLE                       os::LString( 1103 )
#define STR_MAIN_LANGUAGE_USED                            os::LString( 1104 )
#define STR_MAIN_COUNTRY_TAB                              os::LString( 1200 )
#define STR_ERROR_SAVE                                    os::LString( 2000 )
#endif // CATALOG_NO_LSTRINGS
#endif // End of file
